from browser_interaction import BasePage
from time import sleep
from locators.fno_200_locators import FNO200Locators
from locators.main_page_locators import MainPageLocators
from locators.fno_200_locators import FNO200LocatorsName as N


class FNO200MaxSymbolAnd0ValueCheck(BasePage):
    def __init__(self, browser):
        super().__init__(browser)
        self.browser = browser
        self.locator = FNO200Locators

    def first_page_validation(self):
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.find_element(*self.locator.TAX_PERIOD).click()
        sleep(0.3)
        self.find_element(*self.locator.TAX_PERIOD_SELECT).click()
        self.scroll('500')
        self.find_element(*self.locator.APPS).click()
        sleep(0.3)
        self.find_element(*self.locator.APPS_SELECT_ALL).click()
        self.scroll('500')
        sleep(0.3)
        self.find_element(*self.locator.RESIDENT).click()
        sleep(0.3)
        self.find_element(*self.locator.RESIDENT_SELECT).click()
        sleep(0.3)
        self.find_element(*self.locator.TAXPAYER_CATEGORY).click()
        sleep(0.3)
        self.find_element(*self.locator.TAXPAYER_CATEGORY_SELECT_A).click()
        self.find_element(*self.locator.TAXPAYER_CATEGORY_SELECT_B).click()
        self.find_element(*self.locator.TAXPAYER_CATEGORY_SELECT_C).click()
        self.find_element(*self.locator.TAXPAYER_CATEGORY_SELECT_E).click()
        sleep(0.3)
        self.max_symbol_12_input(*self.locator.FIRST_PAGE_I_MONTH, name=N.FIRST_PAGE_I_MONTH)
        self.check_zero_value_input(*self.locator.FIRST_PAGE_I_MONTH, name=N.FIRST_PAGE_I_MONTH)
        self.check_special_symbol_input(*self.locator.FIRST_PAGE_I_MONTH, name=N.FIRST_PAGE_I_MONTH)
        self.check_letter_input(*self.locator.FIRST_PAGE_I_MONTH, name=N.FIRST_PAGE_I_MONTH)

        self.max_symbol_12_input(*self.locator.FIRST_PAGE_II_MONTH, name=N.FIRST_PAGE_II_MONTH)
        self.check_zero_value_input(*self.locator.FIRST_PAGE_II_MONTH, name=N.FIRST_PAGE_II_MONTH)
        self.check_special_symbol_input(*self.locator.FIRST_PAGE_II_MONTH, name=N.FIRST_PAGE_II_MONTH)
        self.check_letter_input(*self.locator.FIRST_PAGE_II_MONTH, name=N.FIRST_PAGE_II_MONTH)

        self.max_symbol_12_input(*self.locator.FIRST_PAGE_III_MONTH, name=N.FIRST_PAGE_III_MONTH)
        self.check_zero_value_input(*self.locator.FIRST_PAGE_III_MONTH, name=N.FIRST_PAGE_III_MONTH)
        self.check_special_symbol_input(*self.locator.FIRST_PAGE_III_MONTH, name=N.FIRST_PAGE_III_MONTH)
        self.check_letter_input(*self.locator.FIRST_PAGE_III_MONTH, name=N.FIRST_PAGE_III_MONTH)
        self.find_element(*self.locator.CONFIRMATION_FIRST_PAGE_2).click()
        self.max_symbol_12_input(*self.locator.FIRST_PAGE_IV_MONTH, name=N.FIRST_PAGE_IV_MONTH)
        self.check_zero_value_input(*self.locator.FIRST_PAGE_IV_MONTH, name=N.FIRST_PAGE_IV_MONTH)
        self.check_special_symbol_input(*self.locator.FIRST_PAGE_IV_MONTH, name=N.FIRST_PAGE_IV_MONTH)
        self.check_letter_input(*self.locator.FIRST_PAGE_IV_MONTH, name=N.FIRST_PAGE_IV_MONTH)

        self.max_symbol_12_input(*self.locator.FIRST_PAGE_V_MONTH, name=N.FIRST_PAGE_V_MONTH)
        self.check_zero_value_input(*self.locator.FIRST_PAGE_V_MONTH, name=N.FIRST_PAGE_V_MONTH)
        self.check_special_symbol_input(*self.locator.FIRST_PAGE_V_MONTH, name=N.FIRST_PAGE_V_MONTH)
        self.check_letter_input(*self.locator.FIRST_PAGE_V_MONTH, name=N.FIRST_PAGE_V_MONTH)

        self.max_symbol_12_input(*self.locator.FIRST_PAGE_VI_MONTH, name=N.FIRST_PAGE_VI_MONTH)
        self.check_zero_value_input(*self.locator.FIRST_PAGE_VI_MONTH, name=N.FIRST_PAGE_VI_MONTH)
        self.check_special_symbol_input(*self.locator.FIRST_PAGE_VI_MONTH, name=N.FIRST_PAGE_VI_MONTH)
        self.check_letter_input(*self.locator.FIRST_PAGE_VI_MONTH, name=N.FIRST_PAGE_VI_MONTH)
        self.find_element(*self.locator.AFTER).click()

    def app_1_validation(self):
        sleep(1)
        self.scroll('400')
        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_I_MONTH, name=N.APP_1_FIELD_1_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_I_MONTH, name=N.APP_1_FIELD_1_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_I_MONTH, name=N.APP_1_FIELD_1_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_I_MONTH, name=N.APP_1_FIELD_1_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_II_MONTH, name=N.APP_1_FIELD_1_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_II_MONTH, name=N.APP_1_FIELD_1_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_II_MONTH, name=N.APP_1_FIELD_1_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_II_MONTH, name=N.APP_1_FIELD_1_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_III_MONTH, name=N.APP_1_FIELD_1_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_III_MONTH, name=N.APP_1_FIELD_1_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_III_MONTH, name=N.APP_1_FIELD_1_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_III_MONTH, name=N.APP_1_FIELD_1_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_A, name=N.APP_1_FIELD_1_A)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_A, name=N.APP_1_FIELD_1_A)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_A, name=N.APP_1_FIELD_1_A)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_A, name=N.APP_1_FIELD_1_A)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_B, name=N.APP_1_FIELD_1_B)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_B, name=N.APP_1_FIELD_1_B)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_B, name=N.APP_1_FIELD_1_B)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_B, name=N.APP_1_FIELD_1_B)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_C, name=N.APP_1_FIELD_1_C)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_C, name=N.APP_1_FIELD_1_C)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_C, name=N.APP_1_FIELD_1_C)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_C, name=N.APP_1_FIELD_1_C)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_D, name=N.APP_1_FIELD_1_D)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_D, name=N.APP_1_FIELD_1_D)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_D, name=N.APP_1_FIELD_1_D)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_D, name=N.APP_1_FIELD_1_D)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_1_E, name=N.APP_1_FIELD_1_E)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_1_E, name=N.APP_1_FIELD_1_E)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_1_E, name=N.APP_1_FIELD_1_E)
        self.check_letter_input(*self.locator.APP_1_FIELD_1_E, name=N.APP_1_FIELD_1_E)
        self.scroll('600')

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_3_I_MONTH, name=N.APP_1_FIELD_3_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_3_I_MONTH, name=N.APP_1_FIELD_3_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_3_I_MONTH, name=N.APP_1_FIELD_3_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_3_I_MONTH, name=N.APP_1_FIELD_3_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_3_II_MONTH, name=N.APP_1_FIELD_3_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_3_II_MONTH, name=N.APP_1_FIELD_3_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_3_II_MONTH, name=N.APP_1_FIELD_3_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_3_II_MONTH, name=N.APP_1_FIELD_3_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_3_III_MONTH, name=N.APP_1_FIELD_3_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_3_III_MONTH, name=N.APP_1_FIELD_3_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_3_III_MONTH, name=N.APP_1_FIELD_3_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_3_III_MONTH, name=N.APP_1_FIELD_3_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_4, name=N.APP_1_FIELD_4)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_4, name=N.APP_1_FIELD_4)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_4, name=N.APP_1_FIELD_4)
        self.check_letter_input(*self.locator.APP_1_FIELD_4, name=N.APP_1_FIELD_4)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_5, name=N.APP_1_FIELD_5)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_5, name=N.APP_1_FIELD_5)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_5, name=N.APP_1_FIELD_5)
        self.check_letter_input(*self.locator.APP_1_FIELD_5, name=N.APP_1_FIELD_5)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_6, name=N.APP_1_FIELD_6)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_6, name=N.APP_1_FIELD_6)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_6, name=N.APP_1_FIELD_6)
        self.check_letter_input(*self.locator.APP_1_FIELD_6, name=N.APP_1_FIELD_6)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.APP_1_FIELD_7_I_MONTH, name=N.APP_1_FIELD_7_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_7_I_MONTH, name=N.APP_1_FIELD_7_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_7_I_MONTH, name=N.APP_1_FIELD_7_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_7_I_MONTH, name=N.APP_1_FIELD_7_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_7_II_MONTH, name=N.APP_1_FIELD_7_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_7_II_MONTH, name=N.APP_1_FIELD_7_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_7_II_MONTH, name=N.APP_1_FIELD_7_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_7_II_MONTH, name=N.APP_1_FIELD_7_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_7_III_MONTH, name=N.APP_1_FIELD_7_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_7_III_MONTH, name=N.APP_1_FIELD_7_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_7_III_MONTH, name=N.APP_1_FIELD_7_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_7_III_MONTH, name=N.APP_1_FIELD_7_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_8_I_MONTH, name=N.APP_1_FIELD_8_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_8_I_MONTH, name=N.APP_1_FIELD_8_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_8_I_MONTH, name=N.APP_1_FIELD_8_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_8_I_MONTH, name=N.APP_1_FIELD_8_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_8_II_MONTH, name=N.APP_1_FIELD_8_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_8_II_MONTH, name=N.APP_1_FIELD_8_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_8_II_MONTH, name=N.APP_1_FIELD_8_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_8_II_MONTH, name=N.APP_1_FIELD_8_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_8_III_MONTH, name=N.APP_1_FIELD_8_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_8_III_MONTH, name=N.APP_1_FIELD_8_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_8_III_MONTH, name=N.APP_1_FIELD_8_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_8_III_MONTH, name=N.APP_1_FIELD_8_III_MONTH)
        self.scroll('500')
        self.max_symbol_12_input(*self.locator.APP_1_FIELD_9_I_MONTH, name=N.APP_1_FIELD_9_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_9_I_MONTH, name=N.APP_1_FIELD_9_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_9_I_MONTH, name=N.APP_1_FIELD_9_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_9_I_MONTH, name=N.APP_1_FIELD_9_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_9_II_MONTH, name=N.APP_1_FIELD_9_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_9_II_MONTH, name=N.APP_1_FIELD_9_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_9_II_MONTH, name=N.APP_1_FIELD_9_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_9_II_MONTH, name=N.APP_1_FIELD_9_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_9_III_MONTH, name=N.APP_1_FIELD_9_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_9_III_MONTH, name=N.APP_1_FIELD_9_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_9_III_MONTH, name=N.APP_1_FIELD_9_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_9_III_MONTH, name=N.APP_1_FIELD_9_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_10_I_MONTH, name=N.APP_1_FIELD_10_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_10_I_MONTH, name=N.APP_1_FIELD_10_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_10_I_MONTH, name=N.APP_1_FIELD_10_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_10_I_MONTH, name=N.APP_1_FIELD_10_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_10_II_MONTH, name=N.APP_1_FIELD_10_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_10_II_MONTH, name=N.APP_1_FIELD_10_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_10_II_MONTH, name=N.APP_1_FIELD_10_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_10_II_MONTH, name=N.APP_1_FIELD_10_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_10_III_MONTH, name=N.APP_1_FIELD_10_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_10_III_MONTH, name=N.APP_1_FIELD_10_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_10_III_MONTH, name=N.APP_1_FIELD_10_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_10_III_MONTH, name=N.APP_1_FIELD_10_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_11_I_MONTH, name=N.APP_1_FIELD_11_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_11_I_MONTH, name=N.APP_1_FIELD_11_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_11_I_MONTH, name=N.APP_1_FIELD_11_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_11_I_MONTH, name=N.APP_1_FIELD_11_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_11_II_MONTH, name=N.APP_1_FIELD_11_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_11_II_MONTH, name=N.APP_1_FIELD_11_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_11_II_MONTH, name=N.APP_1_FIELD_11_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_11_II_MONTH, name=N.APP_1_FIELD_11_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_11_III_MONTH, name=N.APP_1_FIELD_11_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_11_III_MONTH, name=N.APP_1_FIELD_11_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_11_III_MONTH, name=N.APP_1_FIELD_11_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_11_III_MONTH, name=N.APP_1_FIELD_11_III_MONTH)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.APP_1_FIELD_12_I_MONTH, name=N.APP_1_FIELD_12_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_12_I_MONTH, name=N.APP_1_FIELD_12_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_12_I_MONTH, name=N.APP_1_FIELD_12_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_12_I_MONTH, name=N.APP_1_FIELD_12_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_12_II_MONTH, name=N.APP_1_FIELD_12_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_12_II_MONTH, name=N.APP_1_FIELD_12_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_12_II_MONTH, name=N.APP_1_FIELD_12_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_12_II_MONTH, name=N.APP_1_FIELD_12_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_12_III_MONTH, name=N.APP_1_FIELD_12_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_12_III_MONTH, name=N.APP_1_FIELD_12_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_12_III_MONTH, name=N.APP_1_FIELD_12_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_12_III_MONTH, name=N.APP_1_FIELD_12_III_MONTH)

        self.max_symbol_6_input(*self.locator.APP_1_FIELD_13_I_MONTH, name=N.APP_1_FIELD_13_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_13_I_MONTH, name=N.APP_1_FIELD_13_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_13_I_MONTH, name=N.APP_1_FIELD_13_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_13_I_MONTH, name=N.APP_1_FIELD_13_I_MONTH)

        self.max_symbol_6_input(*self.locator.APP_1_FIELD_13_II_MONTH, name=N.APP_1_FIELD_13_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_13_II_MONTH, name=N.APP_1_FIELD_13_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_13_II_MONTH, name=N.APP_1_FIELD_13_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_13_II_MONTH, name=N.APP_1_FIELD_13_II_MONTH)

        self.max_symbol_6_input(*self.locator.APP_1_FIELD_13_III_MONTH, name=N.APP_1_FIELD_13_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_13_III_MONTH, name=N.APP_1_FIELD_13_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_13_III_MONTH, name=N.APP_1_FIELD_13_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_13_III_MONTH, name=N.APP_1_FIELD_13_III_MONTH)
        # ДОДЕЛАТЬ С 14 ПО 15
        self.max_symbol_2_input(*self.locator.APP_1_FIELD_14_I_MONTH, name=N.APP_1_FIELD_14_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_14_I_MONTH, name=N.APP_1_FIELD_14_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_14_I_MONTH, name=N.APP_1_FIELD_14_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_14_I_MONTH, name=N.APP_1_FIELD_14_I_MONTH)

        self.max_symbol_2_input(*self.locator.APP_1_FIELD_14_II_MONTH, name=N.APP_1_FIELD_14_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_14_II_MONTH, name=N.APP_1_FIELD_14_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_14_II_MONTH, name=N.APP_1_FIELD_14_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_14_II_MONTH, name=N.APP_1_FIELD_14_II_MONTH)

        self.max_symbol_2_input(*self.locator.APP_1_FIELD_14_III_MONTH, name=N.APP_1_FIELD_14_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_14_III_MONTH, name=N.APP_1_FIELD_14_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_14_III_MONTH, name=N.APP_1_FIELD_14_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_14_III_MONTH, name=N.APP_1_FIELD_14_III_MONTH)
        self.scroll('600')
        self.max_symbol_2_input(*self.locator.APP_1_FIELD_15_I_MONTH, name=N.APP_1_FIELD_15_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_15_I_MONTH, name=N.APP_1_FIELD_15_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_15_I_MONTH, name=N.APP_1_FIELD_15_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_15_I_MONTH, name=N.APP_1_FIELD_15_I_MONTH)

        self.max_symbol_2_input(*self.locator.APP_1_FIELD_15_II_MONTH, name=N.APP_1_FIELD_15_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_15_II_MONTH, name=N.APP_1_FIELD_15_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_15_II_MONTH, name=N.APP_1_FIELD_15_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_15_II_MONTH, name=N.APP_1_FIELD_15_II_MONTH)

        self.max_symbol_2_input(*self.locator.APP_1_FIELD_15_III_MONTH, name=N.APP_1_FIELD_15_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_15_III_MONTH, name=N.APP_1_FIELD_15_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_15_III_MONTH, name=N.APP_1_FIELD_15_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_15_III_MONTH, name=N.APP_1_FIELD_15_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_16_I_MONTH, name=N.APP_1_FIELD_16_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_16_I_MONTH, name=N.APP_1_FIELD_16_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_16_I_MONTH, name=N.APP_1_FIELD_16_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_16_I_MONTH, name=N.APP_1_FIELD_16_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_16_II_MONTH, name=N.APP_1_FIELD_16_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_16_II_MONTH, name=N.APP_1_FIELD_16_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_16_II_MONTH, name=N.APP_1_FIELD_16_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_16_II_MONTH, name=N.APP_1_FIELD_16_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_16_III_MONTH, name=N.APP_1_FIELD_16_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_16_III_MONTH, name=N.APP_1_FIELD_16_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_16_III_MONTH, name=N.APP_1_FIELD_16_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_16_III_MONTH, name=N.APP_1_FIELD_16_III_MONTH)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.APP_1_FIELD_17_I_MONTH, name=N.APP_1_FIELD_17_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_17_I_MONTH, name=N.APP_1_FIELD_17_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_17_I_MONTH, name=N.APP_1_FIELD_17_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_17_I_MONTH, name=N.APP_1_FIELD_17_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_17_II_MONTH, name=N.APP_1_FIELD_17_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_17_II_MONTH, name=N.APP_1_FIELD_17_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_17_II_MONTH, name=N.APP_1_FIELD_17_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_17_II_MONTH, name=N.APP_1_FIELD_17_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_17_III_MONTH, name=N.APP_1_FIELD_17_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_17_III_MONTH, name=N.APP_1_FIELD_17_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_17_III_MONTH, name=N.APP_1_FIELD_17_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_17_III_MONTH, name=N.APP_1_FIELD_17_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_18_I_MONTH, name=N.APP_1_FIELD_18_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_18_I_MONTH, name=N.APP_1_FIELD_18_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_18_I_MONTH, name=N.APP_1_FIELD_18_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_18_I_MONTH, name=N.APP_1_FIELD_18_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_18_II_MONTH, name=N.APP_1_FIELD_18_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_18_II_MONTH, name=N.APP_1_FIELD_18_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_18_II_MONTH, name=N.APP_1_FIELD_18_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_18_II_MONTH, name=N.APP_1_FIELD_18_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_18_III_MONTH, name=N.APP_1_FIELD_18_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_18_III_MONTH, name=N.APP_1_FIELD_18_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_18_III_MONTH, name=N.APP_1_FIELD_18_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_18_III_MONTH, name=N.APP_1_FIELD_18_III_MONTH)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.APP_1_FIELD_19_I_MONTH, name=N.APP_1_FIELD_19_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_19_I_MONTH, name=N.APP_1_FIELD_19_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_19_I_MONTH, name=N.APP_1_FIELD_19_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_19_I_MONTH, name=N.APP_1_FIELD_19_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_19_II_MONTH, name=N.APP_1_FIELD_19_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_19_II_MONTH, name=N.APP_1_FIELD_19_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_19_II_MONTH, name=N.APP_1_FIELD_19_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_19_II_MONTH, name=N.APP_1_FIELD_19_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_19_III_MONTH, name=N.APP_1_FIELD_19_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_19_III_MONTH, name=N.APP_1_FIELD_19_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_19_III_MONTH, name=N.APP_1_FIELD_19_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_19_III_MONTH, name=N.APP_1_FIELD_19_III_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_20_I_MONTH, name=N.APP_1_FIELD_20_I_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_20_I_MONTH, name=N.APP_1_FIELD_20_I_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_20_I_MONTH, name=N.APP_1_FIELD_20_I_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_20_I_MONTH, name=N.APP_1_FIELD_20_I_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_20_II_MONTH, name=N.APP_1_FIELD_20_II_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_20_II_MONTH, name=N.APP_1_FIELD_20_II_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_20_II_MONTH, name=N.APP_1_FIELD_20_II_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_20_II_MONTH, name=N.APP_1_FIELD_20_II_MONTH)

        self.max_symbol_12_input(*self.locator.APP_1_FIELD_20_III_MONTH, name=N.APP_1_FIELD_20_III_MONTH)
        self.check_zero_value_input(*self.locator.APP_1_FIELD_20_III_MONTH, name=N.APP_1_FIELD_20_III_MONTH)
        self.check_special_symbol_input(*self.locator.APP_1_FIELD_20_III_MONTH, name=N.APP_1_FIELD_20_III_MONTH)
        self.check_letter_input(*self.locator.APP_1_FIELD_20_III_MONTH, name=N.APP_1_FIELD_20_III_MONTH)
        self.scroll('600')
        self.find_element(*self.locator.AFTER).click()

    def app_2_validation(self):
        self.scroll('500')
        self.find_element(*self.locator.ADD_STR).click()
        sleep(0.3)
        self.max_symbol_12_input(*self.locator.SECOND_APP_C, name=N.SECOND_APP_C)
        self.check_zero_value_input(*self.locator.SECOND_APP_C, name=N.SECOND_APP_C)
        self.check_special_symbol_input(*self.locator.SECOND_APP_C, name=N.SECOND_APP_C)
        self.check_letter_input(*self.locator.SECOND_APP_C, name=N.SECOND_APP_C)

        self.max_symbol_18_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)
        self.check_zero_value_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)
        #self.check_special_symbol_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)
        self.check_letter_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)

        self.find_element(*self.locator.SECOND_APP_G_2).send_keys('11dsvxc//=-][11001')
        sleep(0.3)
        assert '1111001' in self.browser.page_source

        element = self.browser.find_element_by_xpath('//*[@name="T"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)

        self.max_symbol_3_input(*self.locator.SECOND_APP_N, name=N.SECOND_APP_N)
        self.check_zero_value_input(*self.locator.SECOND_APP_N, name=N.SECOND_APP_N)
        self.check_special_symbol_input(*self.locator.SECOND_APP_N, name=N.SECOND_APP_N)
        self.check_letter_input(*self.locator.SECOND_APP_N, name=N.SECOND_APP_N)

        self.max_symbol_12_input(*self.locator.SECOND_APP_O, name=N.SECOND_APP_O)
        self.check_zero_value_input(*self.locator.SECOND_APP_O, name=N.SECOND_APP_O)
        self.check_special_symbol_input(*self.locator.SECOND_APP_O, name=N.SECOND_APP_O)
        self.check_letter_input(*self.locator.SECOND_APP_O, name=N.SECOND_APP_O)

        self.max_symbol_12_input(*self.locator.SECOND_APP_P, name=N.SECOND_APP_P)
        self.check_zero_value_input(*self.locator.SECOND_APP_P, name=N.SECOND_APP_P)
        self.check_special_symbol_input(*self.locator.SECOND_APP_P, name=N.SECOND_APP_P)
        self.check_letter_input(*self.locator.SECOND_APP_P, name=N.SECOND_APP_P)

        self.max_symbol_12_input(*self.locator.SECOND_APP_Q, name=N.SECOND_APP_Q)
        self.check_zero_value_input(*self.locator.SECOND_APP_Q, name=N.SECOND_APP_Q)
        self.check_special_symbol_input(*self.locator.SECOND_APP_Q, name=N.SECOND_APP_Q)
        self.check_letter_input(*self.locator.SECOND_APP_Q, name=N.SECOND_APP_Q)

        self.max_symbol_12_input(*self.locator.SECOND_APP_R, name=N.SECOND_APP_R)
        self.check_zero_value_input(*self.locator.SECOND_APP_R, name=N.SECOND_APP_R)
        self.check_special_symbol_input(*self.locator.SECOND_APP_R, name=N.SECOND_APP_R)
        self.check_letter_input(*self.locator.SECOND_APP_R, name=N.SECOND_APP_R)

        self.max_symbol_12_input(*self.locator.SECOND_APP_S, name=N.SECOND_APP_S)
        self.check_zero_value_input(*self.locator.SECOND_APP_S, name=N.SECOND_APP_S)
        self.check_special_symbol_input(*self.locator.SECOND_APP_S, name=N.SECOND_APP_S)
        self.check_letter_input(*self.locator.SECOND_APP_S, name=N.SECOND_APP_S)

        self.max_symbol_12_input(*self.locator.SECOND_APP_T, name=N.SECOND_APP_T)
        self.check_zero_value_input(*self.locator.SECOND_APP_T, name=N.SECOND_APP_T)
        self.check_special_symbol_input(*self.locator.SECOND_APP_T, name=N.SECOND_APP_T)
        self.check_letter_input(*self.locator.SECOND_APP_T, name=N.SECOND_APP_T)

        self.max_symbol_12_input(*self.locator.SECOND_APP_U, name=N.SECOND_APP_U)
        self.check_zero_value_input(*self.locator.SECOND_APP_U, name=N.SECOND_APP_U)
        self.check_special_symbol_input(*self.locator.SECOND_APP_U, name=N.SECOND_APP_U)
        self.check_letter_input(*self.locator.SECOND_APP_U, name=N.SECOND_APP_U)

        element = self.browser.find_element_by_xpath('//*[text()="Добавить"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)

        self.max_symbol_12_input(*self.locator.SECOND_APP_V, name=N.SECOND_APP_V)
        self.check_zero_value_input(*self.locator.SECOND_APP_V, name=N.SECOND_APP_V)
        self.check_special_symbol_input(*self.locator.SECOND_APP_V, name=N.SECOND_APP_V)
        self.check_letter_input(*self.locator.SECOND_APP_V, name=N.SECOND_APP_V)

        self.max_symbol_12_input(*self.locator.SECOND_APP_W, name=N.SECOND_APP_W)
        self.check_zero_value_input(*self.locator.SECOND_APP_W, name=N.SECOND_APP_W)
        self.check_special_symbol_input(*self.locator.SECOND_APP_W, name=N.SECOND_APP_W)
        self.check_letter_input(*self.locator.SECOND_APP_W, name=N.SECOND_APP_W)

        self.max_symbol_12_input(*self.locator.SECOND_APP_X, name=N.SECOND_APP_X)
        self.check_zero_value_input(*self.locator.SECOND_APP_X, name=N.SECOND_APP_X)
        self.check_special_symbol_input(*self.locator.SECOND_APP_X, name=N.SECOND_APP_X)
        self.check_letter_input(*self.locator.SECOND_APP_X, name=N.SECOND_APP_X)

        self.max_symbol_12_input(*self.locator.SECOND_APP_Y, name=N.SECOND_APP_Y)
        self.check_zero_value_input(*self.locator.SECOND_APP_Y, name=N.SECOND_APP_Y)
        self.check_special_symbol_input(*self.locator.SECOND_APP_Y, name=N.SECOND_APP_Y)
        self.check_letter_input(*self.locator.SECOND_APP_Y, name=N.SECOND_APP_Y)

        self.max_symbol_12_input(*self.locator.SECOND_APP_Z, name=N.SECOND_APP_Z)
        self.check_zero_value_input(*self.locator.SECOND_APP_Z, name=N.SECOND_APP_Z)
        self.check_special_symbol_input(*self.locator.SECOND_APP_Z, name=N.SECOND_APP_Z)
        self.check_letter_input(*self.locator.SECOND_APP_Z, name=N.SECOND_APP_Z)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AA, name=N.SECOND_APP_AA)
        self.check_zero_value_input(*self.locator.SECOND_APP_AA, name=N.SECOND_APP_AA)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AA, name=N.SECOND_APP_AA)
        self.check_letter_input(*self.locator.SECOND_APP_AA, name=N.SECOND_APP_AA)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AC, name=N.SECOND_APP_AC)
        self.check_zero_value_input(*self.locator.SECOND_APP_AC, name=N.SECOND_APP_AC)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AC, name=N.SECOND_APP_AC)
        self.check_letter_input(*self.locator.SECOND_APP_AC, name=N.SECOND_APP_AC)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AD, name=N.SECOND_APP_AD)
        self.check_zero_value_input(*self.locator.SECOND_APP_AD, name=N.SECOND_APP_AD)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AD, name=N.SECOND_APP_AD)
        self.check_letter_input(*self.locator.SECOND_APP_AD, name=N.SECOND_APP_AD)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AE, name=N.SECOND_APP_AE)
        self.check_zero_value_input(*self.locator.SECOND_APP_AE, name=N.SECOND_APP_AE)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AE, name=N.SECOND_APP_AE)
        self.check_letter_input(*self.locator.SECOND_APP_AE, name=N.SECOND_APP_AE)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AF, name=N.SECOND_APP_AF)
        self.check_zero_value_input(*self.locator.SECOND_APP_AF, name=N.SECOND_APP_AF)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AF, name=N.SECOND_APP_AF)
        self.check_letter_input(*self.locator.SECOND_APP_AF, name=N.SECOND_APP_AF)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AG, name=N.SECOND_APP_AG)
        self.check_zero_value_input(*self.locator.SECOND_APP_AG, name=N.SECOND_APP_AG)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AG, name=N.SECOND_APP_AG)
        self.check_letter_input(*self.locator.SECOND_APP_AG, name=N.SECOND_APP_AG)

        self.max_symbol_12_input(*self.locator.SECOND_APP_AI, name=N.SECOND_APP_AI)
        self.check_zero_value_input(*self.locator.SECOND_APP_AI, name=N.SECOND_APP_AI)
        self.check_special_symbol_input(*self.locator.SECOND_APP_AI, name=N.SECOND_APP_AI)
        self.check_letter_input(*self.locator.SECOND_APP_AI, name=N.SECOND_APP_AI)

        self.find_element(*self.locator.CANCEL_ADD_STR).click()
        self.find_element(*self.locator.AFTER).click()

    def app_3_validation(self):
        self.max_symbol_12_input(*self.locator.BIN, name=N.BIN)
        self.check_zero_value_input(*self.locator.BIN, name=N.BIN)
        self.check_special_symbol_input(*self.locator.BIN, name=N.BIN)
        self.check_letter_input(*self.locator.BIN, name=N.BIN)
        self.find_element(*self.locator.NAME_OF_FILIAL).send_keys('Aa/][/1')
        sleep(0.3)
        assert 'Aa/][/1' in self.browser.page_source
        self.scroll('500')
        self.max_symbol_6_input(*self.locator.WORKERS_1, name=N.WORKERS_1)
        self.check_zero_value_input(*self.locator.WORKERS_1, name=N.WORKERS_1)
        self.check_special_symbol_input(*self.locator.WORKERS_1, name=N.WORKERS_1)
        self.check_letter_input(*self.locator.WORKERS_1, name=N.WORKERS_1)

        self.max_symbol_6_input(*self.locator.WORKERS_2, name=N.WORKERS_2)
        self.check_zero_value_input(*self.locator.WORKERS_2, name=N.WORKERS_2)
        self.check_special_symbol_input(*self.locator.WORKERS_2, name=N.WORKERS_2)
        self.check_letter_input(*self.locator.WORKERS_2, name=N.WORKERS_2)

        self.max_symbol_6_input(*self.locator.WORKERS_3, name=N.WORKERS_3)
        self.check_zero_value_input(*self.locator.WORKERS_3, name=N.WORKERS_3)
        self.check_special_symbol_input(*self.locator.WORKERS_3, name=N.WORKERS_3)
        self.check_letter_input(*self.locator.WORKERS_3, name=N.WORKERS_3)
        self.scroll('700')
        self.max_symbol_12_input(*self.locator.THIRD_APP_1_I_MONTH, name=N.THIRD_APP_1_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_1_I_MONTH, name=N.THIRD_APP_1_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_1_I_MONTH, name=N.THIRD_APP_1_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_1_I_MONTH, name=N.THIRD_APP_1_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_1_II_MONTH, name=N.THIRD_APP_1_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_1_II_MONTH, name=N.THIRD_APP_1_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_1_II_MONTH, name=N.THIRD_APP_1_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_1_II_MONTH, name=N.THIRD_APP_1_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_1_III_MONTH, name=N.THIRD_APP_1_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_1_III_MONTH, name=N.THIRD_APP_1_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_1_III_MONTH, name=N.THIRD_APP_1_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_1_III_MONTH, name=N.THIRD_APP_1_III_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_2_I_MONTH, name=N.THIRD_APP_2_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_2_I_MONTH, name=N.THIRD_APP_2_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_2_I_MONTH, name=N.THIRD_APP_2_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_2_I_MONTH, name=N.THIRD_APP_2_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_2_II_MONTH, name=N.THIRD_APP_2_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_2_II_MONTH, name=N.THIRD_APP_2_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_2_II_MONTH, name=N.THIRD_APP_2_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_2_II_MONTH, name=N.THIRD_APP_2_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_2_III_MONTH, name=N.THIRD_APP_2_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_2_III_MONTH, name=N.THIRD_APP_2_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_2_III_MONTH, name=N.THIRD_APP_2_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_2_III_MONTH, name=N.THIRD_APP_2_III_MONTH)
        self.scroll('400')
        self.max_symbol_12_input(*self.locator.THIRD_APP_3_I_MONTH, name=N.THIRD_APP_3_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_3_I_MONTH, name=N.THIRD_APP_3_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_3_I_MONTH, name=N.THIRD_APP_3_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_3_I_MONTH, name=N.THIRD_APP_3_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_3_II_MONTH, name=N.THIRD_APP_3_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_3_II_MONTH, name=N.THIRD_APP_3_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_3_II_MONTH, name=N.THIRD_APP_3_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_3_II_MONTH, name=N.THIRD_APP_3_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_3_III_MONTH, name=N.THIRD_APP_3_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_3_III_MONTH, name=N.THIRD_APP_3_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_3_III_MONTH, name=N.THIRD_APP_3_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_3_III_MONTH, name=N.THIRD_APP_3_III_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_4_I_MONTH, name=N.THIRD_APP_4_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_4_I_MONTH, name=N.THIRD_APP_4_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_4_I_MONTH, name=N.THIRD_APP_4_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_4_I_MONTH, name=N.THIRD_APP_4_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_4_II_MONTH, name=N.THIRD_APP_4_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_4_II_MONTH, name=N.THIRD_APP_4_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_4_II_MONTH, name=N.THIRD_APP_4_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_4_II_MONTH, name=N.THIRD_APP_4_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_4_III_MONTH, name=N.THIRD_APP_4_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_4_III_MONTH, name=N.THIRD_APP_4_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_4_III_MONTH, name=N.THIRD_APP_4_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_4_III_MONTH, name=N.THIRD_APP_4_III_MONTH)
        self.scroll('400')
        self.max_symbol_12_input(*self.locator.THIRD_APP_5_I_MONTH, name=N.THIRD_APP_5_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_5_I_MONTH, name=N.THIRD_APP_5_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_5_I_MONTH, name=N.THIRD_APP_5_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_5_I_MONTH, name=N.THIRD_APP_5_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_5_II_MONTH, name=N.THIRD_APP_5_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_5_II_MONTH, name=N.THIRD_APP_5_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_5_II_MONTH, name=N.THIRD_APP_5_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_5_II_MONTH, name=N.THIRD_APP_5_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_5_III_MONTH, name=N.THIRD_APP_5_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_5_III_MONTH, name=N.THIRD_APP_5_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_5_III_MONTH, name=N.THIRD_APP_5_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_5_III_MONTH, name=N.THIRD_APP_5_III_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_6_I_MONTH, name=N.THIRD_APP_6_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_6_I_MONTH, name=N.THIRD_APP_6_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_6_I_MONTH, name=N.THIRD_APP_6_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_6_I_MONTH, name=N.THIRD_APP_6_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_6_II_MONTH, name=N.THIRD_APP_6_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_6_II_MONTH, name=N.THIRD_APP_6_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_6_II_MONTH, name=N.THIRD_APP_6_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_6_II_MONTH, name=N.THIRD_APP_6_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_6_III_MONTH, name=N.THIRD_APP_6_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_6_III_MONTH, name=N.THIRD_APP_6_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_6_III_MONTH, name=N.THIRD_APP_6_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_6_III_MONTH, name=N.THIRD_APP_6_III_MONTH)
        self.scroll('400')
        self.max_symbol_12_input(*self.locator.THIRD_APP_7_I_MONTH, name=N.THIRD_APP_7_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_7_I_MONTH, name=N.THIRD_APP_7_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_7_I_MONTH, name=N.THIRD_APP_7_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_7_I_MONTH, name=N.THIRD_APP_7_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_7_II_MONTH, name=N.THIRD_APP_7_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_7_II_MONTH, name=N.THIRD_APP_7_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_7_II_MONTH, name=N.THIRD_APP_7_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_7_II_MONTH, name=N.THIRD_APP_7_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_7_III_MONTH, name=N.THIRD_APP_7_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_7_III_MONTH, name=N.THIRD_APP_7_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_7_III_MONTH, name=N.THIRD_APP_7_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_7_III_MONTH, name=N.THIRD_APP_7_III_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_8_I_MONTH, name=N.THIRD_APP_8_I_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_8_I_MONTH, name=N.THIRD_APP_8_I_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_8_I_MONTH, name=N.THIRD_APP_8_I_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_8_I_MONTH, name=N.THIRD_APP_8_I_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_8_II_MONTH, name=N.THIRD_APP_8_II_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_8_II_MONTH, name=N.THIRD_APP_8_II_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_8_II_MONTH, name=N.THIRD_APP_8_II_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_8_II_MONTH, name=N.THIRD_APP_8_II_MONTH)

        self.max_symbol_12_input(*self.locator.THIRD_APP_8_III_MONTH, name=N.THIRD_APP_8_III_MONTH)
        self.check_zero_value_input(*self.locator.THIRD_APP_8_III_MONTH, name=N.THIRD_APP_8_III_MONTH)
        self.check_special_symbol_input(*self.locator.THIRD_APP_8_III_MONTH, name=N.THIRD_APP_8_III_MONTH)
        self.check_letter_input(*self.locator.THIRD_APP_8_III_MONTH, name=N.THIRD_APP_8_III_MONTH)
        self.scroll('500')
        self.find_element(*self.locator.AFTER).click()

    def app_4_validation(self):
        self.scroll('400')
        self.find_element(*self.locator.NUMBER_OF_CONTRACT).send_keys('123][=-')
        assert '123][=-' in self.browser.page_source
        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_1_I, name=N.EMPLOYEES_NUMBER_1_I)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_1_I, name=N.EMPLOYEES_NUMBER_1_I)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_1_I, name=N.EMPLOYEES_NUMBER_1_I)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_1_I, name=N.EMPLOYEES_NUMBER_1_I)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_1_II, name=N.EMPLOYEES_NUMBER_1_II)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_1_II, name=N.EMPLOYEES_NUMBER_1_II)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_1_II, name=N.EMPLOYEES_NUMBER_1_II)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_1_II, name=N.EMPLOYEES_NUMBER_1_II)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_1_III, name=N.EMPLOYEES_NUMBER_1_III)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_1_III, name=N.EMPLOYEES_NUMBER_1_III)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_1_III, name=N.EMPLOYEES_NUMBER_1_III)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_1_III, name=N.EMPLOYEES_NUMBER_1_III)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_2_I, name=N.EMPLOYEES_NUMBER_2_I)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_2_I, name=N.EMPLOYEES_NUMBER_2_I)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_2_I, name=N.EMPLOYEES_NUMBER_2_I)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_2_I, name=N.EMPLOYEES_NUMBER_2_I)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_2_II, name=N.EMPLOYEES_NUMBER_2_II)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_2_II, name=N.EMPLOYEES_NUMBER_2_II)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_2_II, name=N.EMPLOYEES_NUMBER_2_II)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_2_II, name=N.EMPLOYEES_NUMBER_2_II)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_2_III, name=N.EMPLOYEES_NUMBER_2_III)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_2_III, name=N.EMPLOYEES_NUMBER_2_III)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_2_III, name=N.EMPLOYEES_NUMBER_2_III)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_2_III, name=N.EMPLOYEES_NUMBER_2_III)
        self.scroll('500')
        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_3_I, name=N.EMPLOYEES_NUMBER_3_I)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_3_I, name=N.EMPLOYEES_NUMBER_3_I)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_3_I, name=N.EMPLOYEES_NUMBER_3_I)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_3_I, name=N.EMPLOYEES_NUMBER_3_I)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_3_II, name=N.EMPLOYEES_NUMBER_3_II)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_3_II, name=N.EMPLOYEES_NUMBER_3_II)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_3_II, name=N.EMPLOYEES_NUMBER_3_II)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_3_II, name=N.EMPLOYEES_NUMBER_3_II)

        self.max_symbol_6_input(*self.locator.EMPLOYEES_NUMBER_3_III, name=N.EMPLOYEES_NUMBER_3_III)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_3_III, name=N.EMPLOYEES_NUMBER_3_III)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_3_III, name=N.EMPLOYEES_NUMBER_3_III)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_3_III, name=N.EMPLOYEES_NUMBER_3_III)

        self.max_symbol_12_input(*self.locator.EMPLOYEES_NUMBER_4_I, name=N.EMPLOYEES_NUMBER_4_I)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_4_I, name=N.EMPLOYEES_NUMBER_4_I)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_4_I, name=N.EMPLOYEES_NUMBER_4_I)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_4_I, name=N.EMPLOYEES_NUMBER_4_I)

        self.max_symbol_12_input(*self.locator.EMPLOYEES_NUMBER_4_II, name=N.EMPLOYEES_NUMBER_4_II)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_4_II, name=N.EMPLOYEES_NUMBER_4_II)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_4_II, name=N.EMPLOYEES_NUMBER_4_II)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_4_II, name=N.EMPLOYEES_NUMBER_4_II)

        self.max_symbol_12_input(*self.locator.EMPLOYEES_NUMBER_4_III, name=N.EMPLOYEES_NUMBER_4_III)
        self.check_zero_value_input(*self.locator.EMPLOYEES_NUMBER_4_III, name=N.EMPLOYEES_NUMBER_4_III)
        self.check_special_symbol_input(*self.locator.EMPLOYEES_NUMBER_4_III, name=N.EMPLOYEES_NUMBER_4_III)
        self.check_letter_input(*self.locator.EMPLOYEES_NUMBER_4_III, name=N.EMPLOYEES_NUMBER_4_III)

        self.max_symbol_3_input(*self.locator.TAX_PERCENT_1, name=N.TAX_PERCENT_1)
        self.check_zero_value_input(*self.locator.TAX_PERCENT_1, name=N.TAX_PERCENT_1)
        self.check_special_symbol_input(*self.locator.TAX_PERCENT_1, name=N.TAX_PERCENT_1)
        self.check_letter_input(*self.locator.TAX_PERCENT_1, name=N.TAX_PERCENT_1)

        self.max_symbol_3_input(*self.locator.TAX_PERCENT_2, name=N.TAX_PERCENT_2)
        self.check_zero_value_input(*self.locator.TAX_PERCENT_2, name=N.TAX_PERCENT_2)
        self.check_special_symbol_input(*self.locator.TAX_PERCENT_2, name=N.TAX_PERCENT_2)
        self.check_letter_input(*self.locator.TAX_PERCENT_2, name=N.TAX_PERCENT_2)

        self.max_symbol_3_input(*self.locator.TAX_PERCENT_3, name=N.TAX_PERCENT_3)
        self.check_zero_value_input(*self.locator.TAX_PERCENT_3, name=N.TAX_PERCENT_3)
        self.check_special_symbol_input(*self.locator.TAX_PERCENT_3, name=N.TAX_PERCENT_3)
        self.check_letter_input(*self.locator.TAX_PERCENT_3, name=N.TAX_PERCENT_3)

        self.scroll('500')
        self.find_element(*self.locator.AFTER).click()

    def app_5_validation(self):
        self.scroll('500')
        self.find_element(*self.locator.ADD_STR).click()
        sleep(0.3)
        self.max_symbol_12_input(*self.locator.FIFTH_APP_C, name=N.FIFTH_APP_C)
        self.check_zero_value_input(*self.locator.FIFTH_APP_C, name=N.FIFTH_APP_C)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_C, name=N.FIFTH_APP_C)
        self.check_letter_input(*self.locator.FIFTH_APP_C, name=N.FIFTH_APP_C)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_G, name=N.FIFTH_APP_G)
        self.check_zero_value_input(*self.locator.FIFTH_APP_G, name=N.FIFTH_APP_G)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_G, name=N.FIFTH_APP_G)
        self.check_letter_input(*self.locator.FIFTH_APP_G, name=N.FIFTH_APP_G)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_H, name=N.FIFTH_APP_H)
        self.check_zero_value_input(*self.locator.FIFTH_APP_H, name=N.FIFTH_APP_H)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_H, name=N.FIFTH_APP_H)
        self.check_letter_input(*self.locator.FIFTH_APP_H, name=N.FIFTH_APP_H)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_I, name=N.FIFTH_APP_I)
        self.check_zero_value_input(*self.locator.FIFTH_APP_I, name=N.FIFTH_APP_I)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_I, name=N.FIFTH_APP_I)
        self.check_letter_input(*self.locator.FIFTH_APP_I, name=N.FIFTH_APP_I)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_J, name=N.FIFTH_APP_J)
        self.check_zero_value_input(*self.locator.FIFTH_APP_J, name=N.FIFTH_APP_J)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_J, name=N.FIFTH_APP_J)
        self.check_letter_input(*self.locator.FIFTH_APP_J, name=N.FIFTH_APP_J)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_K, name=N.FIFTH_APP_K)
        self.check_zero_value_input(*self.locator.FIFTH_APP_K, name=N.FIFTH_APP_K)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_K, name=N.FIFTH_APP_K)
        self.check_letter_input(*self.locator.FIFTH_APP_K, name=N.FIFTH_APP_K)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_L, name=N.FIFTH_APP_L)
        self.check_zero_value_input(*self.locator.FIFTH_APP_L, name=N.FIFTH_APP_L)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_L, name=N.FIFTH_APP_L)
        self.check_letter_input(*self.locator.FIFTH_APP_L, name=N.FIFTH_APP_L)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_M, name=N.FIFTH_APP_M)
        self.check_zero_value_input(*self.locator.FIFTH_APP_M, name=N.FIFTH_APP_M)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_M, name=N.FIFTH_APP_M)
        self.check_letter_input(*self.locator.FIFTH_APP_M, name=N.FIFTH_APP_M)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_N, name=N.FIFTH_APP_N)
        self.check_zero_value_input(*self.locator.FIFTH_APP_N, name=N.FIFTH_APP_N)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_N, name=N.FIFTH_APP_N)
        self.check_letter_input(*self.locator.FIFTH_APP_N, name=N.FIFTH_APP_N)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_O, name=N.FIFTH_APP_O)
        self.check_zero_value_input(*self.locator.FIFTH_APP_O, name=N.FIFTH_APP_O)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_O, name=N.FIFTH_APP_O)
        self.check_letter_input(*self.locator.FIFTH_APP_O, name=N.FIFTH_APP_O)
        element = self.browser.find_element_by_xpath('//*[text()="Добавить"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.max_symbol_12_input(*self.locator.FIFTH_APP_P, name=N.FIFTH_APP_P)
        self.check_zero_value_input(*self.locator.FIFTH_APP_P, name=N.FIFTH_APP_P)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_P, name=N.FIFTH_APP_P)
        self.check_letter_input(*self.locator.FIFTH_APP_P, name=N.FIFTH_APP_P)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_Q, name=N.FIFTH_APP_Q)
        self.check_zero_value_input(*self.locator.FIFTH_APP_Q, name=N.FIFTH_APP_Q)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_Q, name=N.FIFTH_APP_Q)
        self.check_letter_input(*self.locator.FIFTH_APP_Q, name=N.FIFTH_APP_Q)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_R, name=N.FIFTH_APP_R)
        self.check_zero_value_input(*self.locator.FIFTH_APP_R, name=N.FIFTH_APP_R)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_R, name=N.FIFTH_APP_R)
        self.check_letter_input(*self.locator.FIFTH_APP_R, name=N.FIFTH_APP_R)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_S, name=N.FIFTH_APP_S)
        self.check_zero_value_input(*self.locator.FIFTH_APP_S, name=N.FIFTH_APP_S)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_S, name=N.FIFTH_APP_S)
        self.check_letter_input(*self.locator.FIFTH_APP_S, name=N.FIFTH_APP_S)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_T, name=N.FIFTH_APP_T)
        self.check_zero_value_input(*self.locator.FIFTH_APP_T, name=N.FIFTH_APP_T)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_T, name=N.FIFTH_APP_T)
        self.check_letter_input(*self.locator.FIFTH_APP_T, name=N.FIFTH_APP_T)

        self.max_symbol_12_input(*self.locator.FIFTH_APP_U, name=N.FIFTH_APP_U)
        self.check_zero_value_input(*self.locator.FIFTH_APP_U, name=N.FIFTH_APP_U)
        self.check_special_symbol_input(*self.locator.FIFTH_APP_U, name=N.FIFTH_APP_U)
        self.check_letter_input(*self.locator.FIFTH_APP_U, name=N.FIFTH_APP_U)
        self.find_element(*self.locator.CANCEL_ADD_STR).click()
        sleep(0.3)
        self.find_element(*self.locator.AFTER).click()

    def seventh_page_validation(self):
        self.scroll('300')
        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_1_I, name=N.SEVENTH_PAGE_1_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_1_I, name=N.SEVENTH_PAGE_1_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_1_I, name=N.SEVENTH_PAGE_1_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_1_I, name=N.SEVENTH_PAGE_1_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_1_II, name=N.SEVENTH_PAGE_1_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_1_II, name=N.SEVENTH_PAGE_1_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_1_II, name=N.SEVENTH_PAGE_1_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_1_II, name=N.SEVENTH_PAGE_1_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_1_III, name=N.SEVENTH_PAGE_1_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_1_III, name=N.SEVENTH_PAGE_1_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_1_III, name=N.SEVENTH_PAGE_1_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_1_III, name=N.SEVENTH_PAGE_1_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_2_I, name=N.SEVENTH_PAGE_2_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_2_I, name=N.SEVENTH_PAGE_2_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_2_I, name=N.SEVENTH_PAGE_2_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_2_I, name=N.SEVENTH_PAGE_2_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_2_II, name=N.SEVENTH_PAGE_2_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_2_II, name=N.SEVENTH_PAGE_2_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_2_II, name=N.SEVENTH_PAGE_2_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_2_II, name=N.SEVENTH_PAGE_2_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_2_III, name=N.SEVENTH_PAGE_2_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_2_III, name=N.SEVENTH_PAGE_2_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_2_III, name=N.SEVENTH_PAGE_2_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_2_III, name=N.SEVENTH_PAGE_2_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_3_I, name=N.SEVENTH_PAGE_3_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_3_I, name=N.SEVENTH_PAGE_3_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_3_I, name=N.SEVENTH_PAGE_3_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_3_I, name=N.SEVENTH_PAGE_3_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_3_II, name=N.SEVENTH_PAGE_3_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_3_II, name=N.SEVENTH_PAGE_3_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_3_II, name=N.SEVENTH_PAGE_3_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_3_II, name=N.SEVENTH_PAGE_3_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_3_III, name=N.SEVENTH_PAGE_3_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_3_III, name=N.SEVENTH_PAGE_3_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_3_III, name=N.SEVENTH_PAGE_3_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_3_III, name=N.SEVENTH_PAGE_3_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_4_I, name=N.SEVENTH_PAGE_4_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_4_I, name=N.SEVENTH_PAGE_4_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_4_I, name=N.SEVENTH_PAGE_4_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_4_I, name=N.SEVENTH_PAGE_4_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_4_II, name=N.SEVENTH_PAGE_4_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_4_II, name=N.SEVENTH_PAGE_4_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_4_II, name=N.SEVENTH_PAGE_4_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_4_II, name=N.SEVENTH_PAGE_4_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_4_III, name=N.SEVENTH_PAGE_4_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_4_III, name=N.SEVENTH_PAGE_4_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_4_III, name=N.SEVENTH_PAGE_4_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_4_III, name=N.SEVENTH_PAGE_4_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_5_I, name=N.SEVENTH_PAGE_5_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_5_I, name=N.SEVENTH_PAGE_5_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_5_I, name=N.SEVENTH_PAGE_5_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_5_I, name=N.SEVENTH_PAGE_5_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_5_II, name=N.SEVENTH_PAGE_5_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_5_II, name=N.SEVENTH_PAGE_5_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_5_II, name=N.SEVENTH_PAGE_5_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_5_II, name=N.SEVENTH_PAGE_5_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_5_III, name=N.SEVENTH_PAGE_5_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_5_III, name=N.SEVENTH_PAGE_5_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_5_III, name=N.SEVENTH_PAGE_5_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_5_III, name=N.SEVENTH_PAGE_5_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_6_I, name=N.SEVENTH_PAGE_6_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_6_I, name=N.SEVENTH_PAGE_6_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_6_I, name=N.SEVENTH_PAGE_6_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_6_I, name=N.SEVENTH_PAGE_6_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_6_II, name=N.SEVENTH_PAGE_6_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_6_II, name=N.SEVENTH_PAGE_6_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_6_II, name=N.SEVENTH_PAGE_6_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_6_II, name=N.SEVENTH_PAGE_6_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_6_III, name=N.SEVENTH_PAGE_6_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_6_III, name=N.SEVENTH_PAGE_6_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_6_III, name=N.SEVENTH_PAGE_6_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_6_III, name=N.SEVENTH_PAGE_6_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_7_I, name=N.SEVENTH_PAGE_7_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_7_I, name=N.SEVENTH_PAGE_7_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_7_I, name=N.SEVENTH_PAGE_7_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_7_I, name=N.SEVENTH_PAGE_7_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_7_II, name=N.SEVENTH_PAGE_7_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_7_II, name=N.SEVENTH_PAGE_7_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_7_II, name=N.SEVENTH_PAGE_7_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_7_II, name=N.SEVENTH_PAGE_7_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_7_III, name=N.SEVENTH_PAGE_7_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_7_III, name=N.SEVENTH_PAGE_7_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_7_III, name=N.SEVENTH_PAGE_7_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_7_III, name=N.SEVENTH_PAGE_7_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_8_I, name=N.SEVENTH_PAGE_8_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_8_I, name=N.SEVENTH_PAGE_8_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_8_I, name=N.SEVENTH_PAGE_8_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_8_I, name=N.SEVENTH_PAGE_8_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_8_II, name=N.SEVENTH_PAGE_8_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_8_II, name=N.SEVENTH_PAGE_8_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_8_II, name=N.SEVENTH_PAGE_8_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_8_II, name=N.SEVENTH_PAGE_8_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_8_III, name=N.SEVENTH_PAGE_8_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_8_III, name=N.SEVENTH_PAGE_8_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_8_III, name=N.SEVENTH_PAGE_8_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_8_III, name=N.SEVENTH_PAGE_8_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_9_I, name=N.SEVENTH_PAGE_9_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_9_I, name=N.SEVENTH_PAGE_9_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_9_I, name=N.SEVENTH_PAGE_9_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_9_I, name=N.SEVENTH_PAGE_9_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_9_II, name=N.SEVENTH_PAGE_9_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_9_II, name=N.SEVENTH_PAGE_9_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_9_II, name=N.SEVENTH_PAGE_9_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_9_II, name=N.SEVENTH_PAGE_9_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_9_III, name=N.SEVENTH_PAGE_9_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_9_III, name=N.SEVENTH_PAGE_9_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_9_III, name=N.SEVENTH_PAGE_9_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_9_III, name=N.SEVENTH_PAGE_9_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_10_I, name=N.SEVENTH_PAGE_10_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_10_I, name=N.SEVENTH_PAGE_10_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_10_I, name=N.SEVENTH_PAGE_10_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_10_I, name=N.SEVENTH_PAGE_10_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_10_II, name=N.SEVENTH_PAGE_10_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_10_II, name=N.SEVENTH_PAGE_10_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_10_II, name=N.SEVENTH_PAGE_10_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_10_II, name=N.SEVENTH_PAGE_10_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_10_III, name=N.SEVENTH_PAGE_10_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_10_III, name=N.SEVENTH_PAGE_10_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_10_III, name=N.SEVENTH_PAGE_10_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_10_III, name=N.SEVENTH_PAGE_10_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_11_I, name=N.SEVENTH_PAGE_11_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_11_I, name=N.SEVENTH_PAGE_11_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_11_I, name=N.SEVENTH_PAGE_11_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_11_I, name=N.SEVENTH_PAGE_11_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_11_II, name=N.SEVENTH_PAGE_11_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_11_II, name=N.SEVENTH_PAGE_11_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_11_II, name=N.SEVENTH_PAGE_11_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_11_II, name=N.SEVENTH_PAGE_11_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_11_III, name=N.SEVENTH_PAGE_11_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_11_III, name=N.SEVENTH_PAGE_11_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_11_III, name=N.SEVENTH_PAGE_11_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_11_III, name=N.SEVENTH_PAGE_11_III)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_12_I, name=N.SEVENTH_PAGE_12_I)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_12_I, name=N.SEVENTH_PAGE_12_I)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_12_I, name=N.SEVENTH_PAGE_12_I)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_12_I, name=N.SEVENTH_PAGE_12_I)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_12_II, name=N.SEVENTH_PAGE_12_II)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_12_II, name=N.SEVENTH_PAGE_12_II)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_12_II, name=N.SEVENTH_PAGE_12_II)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_12_II, name=N.SEVENTH_PAGE_12_II)

        self.max_symbol_12_input(*self.locator.SEVENTH_PAGE_12_III, name=N.SEVENTH_PAGE_12_III)
        self.check_zero_value_input(*self.locator.SEVENTH_PAGE_12_III, name=N.SEVENTH_PAGE_12_III)
        self.check_special_symbol_input(*self.locator.SEVENTH_PAGE_12_III, name=N.SEVENTH_PAGE_12_III)
        self.check_letter_input(*self.locator.SEVENTH_PAGE_12_III, name=N.SEVENTH_PAGE_12_III)


