from browser_interaction import BasePage
from time import sleep
from locators.fno_400_locators import FNO_400_01Locators, FNO_400_02Locators, FNO_400_03Locators, FNO_400_04Locators \
    , FNO_400_05Locators, FNO_400_06Locators, FNO_400_07Locators, FNO_400_08Locators
from locators.main_page_locators import MainPageLocators
from locators.fno_400_locators import FNO_400_01LocatorsName as N1, FNO_400_02LocatorsName as N2, FNO_400_03LocatorsName as N3, FNO_400_04LocatorsName as N4 \
    , FNO_400_06LocatorsName as N6, FNO_400_07LocatorsName as N7, FNO_400_08LocatorsName as N8, FNO_400_05LocatorsName as N5
import allure


class FNO400MaxSymbolAnd0ValueCheck(BasePage):
    def __init__(self, browser):
        super().__init__(browser)
        self.browser = browser
        self.locator = FNO_400_01Locators
        self.locator02 = FNO_400_02Locators
        self.locator03 = FNO_400_03Locators
        self.locator04 = FNO_400_04Locators
        self.locator05 = FNO_400_05Locators
        self.locator06 = FNO_400_06Locators
        self.locator07 = FNO_400_07Locators
        self.locator08 = FNO_400_08Locators

        '''Ниже первая страница'''

    def first_validation_page_1(self):
        self.declaration_type_additional_with_notification_second()
        self.scroll('700')
        self.find_element(*self.locator.TAXPAYER_CATEGORY).click()
        self.find_element(*self.locator.TAXPAYER_CATEGORY_SELECT).click()
        self.find_element(*self.locator.ANNEXES).click()
        self.find_element(*self.locator.ANNEXES_SELECT).click()
        self.find_element(*self.locator.CONTROL_TEXT).click()
        self.find_element(*self.locator.CONFIRM).click()
        self.scroll('1000')
        self.find_element(*self.locator.AFTER).click()

    def second_validation_page_1(self):
        self.max_symbol_18_input(*self.locator.PRODUCT_TYPE, name=N1.PRODUCT_TYPE)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.BUT_1, name=N1.BUT_1)
        self.check_zero_value_input(*self.locator.BUT_1, name=N1.BUT_1)
        self.check_special_symbol_input(*self.locator.BUT_1, name=N1.BUT_1)
        self.check_letter_input(*self.locator.BUT_1, name=N1.BUT_1)
        self.max_symbol_5_input(*self.locator.BUT_2, name=N1.BUT_2)
        self.check_zero_value_input(*self.locator.BUT_2, name=N1.BUT_2)
        self.check_special_symbol_input(*self.locator.BUT_2, name=N1.BUT_2)
        self.check_letter_input(*self.locator.BUT_2, name=N1.BUT_2)
        self.max_symbol_12_input(*self.locator.BUT_3, name=N1.BUT_3)
        self.check_zero_value_input(*self.locator.BUT_3, name=N1.BUT_3)
        self.check_special_symbol_input(*self.locator.BUT_3, name=N1.BUT_3)
        self.check_letter_input(*self.locator.BUT_3, name=N1.BUT_3)
        self.max_symbol_5_input(*self.locator.BUT_4, name=N1.BUT_4)
        self.check_zero_value_input(*self.locator.BUT_4, name=N1.BUT_4)
        self.check_special_symbol_input(*self.locator.BUT_4, name=N1.BUT_4)
        self.check_letter_input(*self.locator.BUT_4, name=N1.BUT_4)
        self.max_symbol_12_input(*self.locator.BUT_5, name=N1.BUT_5)
        self.check_zero_value_input(*self.locator.BUT_5, name=N1.BUT_5)
        self.check_special_symbol_input(*self.locator.BUT_5, name=N1.BUT_5)
        self.check_letter_input(*self.locator.BUT_5, name=N1.BUT_5)
        self.max_symbol_5_input(*self.locator.BUT_6, name=N1.BUT_6)
        self.check_zero_value_input(*self.locator.BUT_6, name=N1.BUT_6)
        self.check_special_symbol_input(*self.locator.BUT_6, name=N1.BUT_6)
        self.check_letter_input(*self.locator.BUT_6, name=N1.BUT_6)
        self.max_symbol_12_input(*self.locator.BUT_7, name=N1.BUT_7)
        self.check_zero_value_input(*self.locator.BUT_7, name=N1.BUT_7)
        self.check_special_symbol_input(*self.locator.BUT_7, name=N1.BUT_7)
        self.check_letter_input(*self.locator.BUT_7, name=N1.BUT_7)
        self.max_symbol_5_input(*self.locator.BUT_8, name=N1.BUT_8)
        self.check_zero_value_input(*self.locator.BUT_8, name=N1.BUT_8)
        self.check_special_symbol_input(*self.locator.BUT_8, name=N1.BUT_8)
        self.check_letter_input(*self.locator.BUT_8, name=N1.BUT_8)
        self.max_symbol_12_input(*self.locator.BUT_9, name=N1.BUT_9)
        self.check_zero_value_input(*self.locator.BUT_9, name=N1.BUT_9)
        self.check_special_symbol_input(*self.locator.BUT_9, name=N1.BUT_9)
        self.check_letter_input(*self.locator.BUT_9, name=N1.BUT_9)
        self.max_symbol_5_input(*self.locator.BUT_10, name=N1.BUT_10)
        self.check_zero_value_input(*self.locator.BUT_10, name=N1.BUT_10)
        self.check_special_symbol_input(*self.locator.BUT_10, name=N1.BUT_10)
        self.check_letter_input(*self.locator.BUT_10, name=N1.BUT_10)
        self.max_symbol_12_input(*self.locator.BUT_11, name=N1.BUT_11)
        self.check_zero_value_input(*self.locator.BUT_11, name=N1.BUT_11)
        self.check_special_symbol_input(*self.locator.BUT_11, name=N1.BUT_11)
        self.check_letter_input(*self.locator.BUT_11, name=N1.BUT_11)
        self.max_symbol_5_input(*self.locator.BUT_12, name=N1.BUT_12)
        self.check_zero_value_input(*self.locator.BUT_12, name=N1.BUT_12)
        self.check_special_symbol_input(*self.locator.BUT_12, name=N1.BUT_12)
        self.check_letter_input(*self.locator.BUT_12, name=N1.BUT_12)
        self.max_symbol_12_input(*self.locator.BUT_13, name=N1.BUT_13)
        self.check_zero_value_input(*self.locator.BUT_13, name=N1.BUT_13)
        self.check_special_symbol_input(*self.locator.BUT_13, name=N1.BUT_13)
        self.check_letter_input(*self.locator.BUT_13, name=N1.BUT_13)
        self.max_symbol_5_input(*self.locator.BUT_14, name=N1.BUT_14)
        self.check_zero_value_input(*self.locator.BUT_14, name=N1.BUT_14)
        self.check_special_symbol_input(*self.locator.BUT_14, name=N1.BUT_14)
        self.check_letter_input(*self.locator.BUT_14, name=N1.BUT_14)
        self.max_symbol_12_input(*self.locator.BUT_15, name=N1.BUT_15)
        self.check_zero_value_input(*self.locator.BUT_15, name=N1.BUT_15)
        self.check_special_symbol_input(*self.locator.BUT_15, name=N1.BUT_15)
        self.check_letter_input(*self.locator.BUT_15, name=N1.BUT_15)
        self.max_symbol_5_input(*self.locator.BUT_16, name=N1.BUT_16)
        self.check_zero_value_input(*self.locator.BUT_16, name=N1.BUT_16)
        self.check_special_symbol_input(*self.locator.BUT_16, name=N1.BUT_16)
        self.check_letter_input(*self.locator.BUT_16, name=N1.BUT_16)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.BUT_17, name=N1.BUT_17)
        self.check_zero_value_input(*self.locator.BUT_17, name=N1.BUT_17)
        self.check_special_symbol_input(*self.locator.BUT_17, name=N1.BUT_17)
        self.check_letter_input(*self.locator.BUT_17, name=N1.BUT_17)
        self.max_symbol_5_input(*self.locator.BUT_18, name=N1.BUT_18)
        self.check_zero_value_input(*self.locator.BUT_18, name=N1.BUT_18)
        self.check_special_symbol_input(*self.locator.BUT_18, name=N1.BUT_18)
        self.check_letter_input(*self.locator.BUT_18, name=N1.BUT_18)
        self.max_symbol_12_input(*self.locator.BUT_19, name=N1.BUT_19)
        self.check_zero_value_input(*self.locator.BUT_19, name=N1.BUT_19)
        self.check_special_symbol_input(*self.locator.BUT_19, name=N1.BUT_19)
        self.check_letter_input(*self.locator.BUT_19, name=N1.BUT_19)
        self.max_symbol_5_input(*self.locator.BUT_20, name=N1.BUT_20)
        self.check_zero_value_input(*self.locator.BUT_20, name=N1.BUT_20)
        self.check_special_symbol_input(*self.locator.BUT_20, name=N1.BUT_20)
        self.check_letter_input(*self.locator.BUT_20, name=N1.BUT_20)
        self.max_symbol_12_input(*self.locator.BUT_21, name=N1.BUT_21)
        self.check_zero_value_input(*self.locator.BUT_21, name=N1.BUT_21)
        self.check_special_symbol_input(*self.locator.BUT_21, name=N1.BUT_21)
        self.check_letter_input(*self.locator.BUT_21, name=N1.BUT_21)
        self.max_symbol_5_input(*self.locator.BUT_22, name=N1.BUT_22)
        self.check_zero_value_input(*self.locator.BUT_22, name=N1.BUT_22)
        self.check_special_symbol_input(*self.locator.BUT_22, name=N1.BUT_22)
        self.check_letter_input(*self.locator.BUT_22, name=N1.BUT_22)
        self.max_symbol_12_input(*self.locator.BUT_23, name=N1.BUT_23)
        self.check_zero_value_input(*self.locator.BUT_23, name=N1.BUT_23)
        self.check_special_symbol_input(*self.locator.BUT_23, name=N1.BUT_23)
        self.check_letter_input(*self.locator.BUT_23, name=N1.BUT_23)
        self.max_symbol_5_input(*self.locator.BUT_24, name=N1.BUT_24)
        self.check_zero_value_input(*self.locator.BUT_24, name=N1.BUT_24)
        self.check_special_symbol_input(*self.locator.BUT_24, name=N1.BUT_24)
        self.check_letter_input(*self.locator.BUT_24, name=N1.BUT_24)
        sleep(0.5)
        self.max_symbol_15_input(*self.locator.BUT_25, name=N1.BUT_25)
        self.check_zero_value_input(*self.locator.BUT_25, name=N1.BUT_25)
        self.check_special_symbol_input(*self.locator.BUT_25, name=N1.BUT_25)
        self.check_letter_input(*self.locator.BUT_25, name=N1.BUT_25)
        self.scroll('500')
        self.find_element(*self.locator.AFTER).click()

    def validation_page_3(self):
        self.scroll('700')
        self.max_symbol_12_input(*self.locator.BUTTON_TOTAL_8, name=N1.BUTTON_TOTAL_8)
        self.check_zero_value_input(*self.locator.BUTTON_TOTAL_8, name=N1.BUTTON_TOTAL_8)
        self.check_special_symbol_input(*self.locator.BUTTON_TOTAL_8, name=N1.BUTTON_TOTAL_8)
        self.check_letter_input(*self.locator.BUTTON_TOTAL_8, name=N1.BUTTON_TOTAL_8)
        sleep(0.5)
        self.scroll('500')
        self.max_symbol_12_input(*self.locator.BUTTON_TOTAL_12, name=N1.BUTTON_TOTAL_12)
        self.check_zero_value_input(*self.locator.BUTTON_TOTAL_12, name=N1.BUTTON_TOTAL_12)
        self.check_special_symbol_input(*self.locator.BUTTON_TOTAL_12, name=N1.BUTTON_TOTAL_12)
        self.check_letter_input(*self.locator.BUTTON_TOTAL_12, name=N1.BUTTON_TOTAL_12)
        sleep(0.5)
        self.scroll('800')
        self.max_symbol_12_input(*self.locator.VAL_1, name=N1.VAL_1)
        self.check_zero_value_input(*self.locator.VAL_1, name=N1.VAL_1)
        self.check_special_symbol_input(*self.locator.VAL_1, name=N1.VAL_1)
        self.check_letter_input(*self.locator.VAL_1, name=N1.VAL_1)

        self.max_symbol_12_input(*self.locator.VAL_2, name=N1.VAL_2)
        self.check_zero_value_input(*self.locator.VAL_2, name=N1.VAL_2)
        self.check_special_symbol_input(*self.locator.VAL_2, name=N1.VAL_2)
        self.check_letter_input(*self.locator.VAL_2, name=N1.VAL_2)

        self.max_symbol_12_input(*self.locator.VAL_3, name=N1.VAL_3)
        self.check_zero_value_input(*self.locator.VAL_3, name=N1.VAL_3)
        self.check_special_symbol_input(*self.locator.BUTTON_TOTAL_12, name=N1.VAL_3)
        self.check_letter_input(*self.locator.VAL_3, name=N1.VAL_3)

        self.max_symbol_12_input(*self.locator.VAL_4, name=N1.VAL_4)
        self.check_zero_value_input(*self.locator.VAL_4, name=N1.VAL_4)
        self.check_special_symbol_input(*self.locator.VAL_4, name=N1.VAL_4)
        self.check_letter_input(*self.locator.VAL_4, name=N1.VAL_4)

        self.max_symbol_12_input(*self.locator.VAL_5, name=N1.VAL_5)
        self.check_zero_value_input(*self.locator.VAL_5, name=N1.VAL_5)
        self.check_special_symbol_input(*self.locator.VAL_5, name=N1.VAL_5)
        self.check_letter_input(*self.locator.VAL_5, name=N1.VAL_5)

        self.max_symbol_12_input(*self.locator.VAL_6, name=N1.VAL_6)
        self.check_zero_value_input(*self.locator.VAL_6, name=N1.VAL_6)
        self.check_special_symbol_input(*self.locator.VAL_6, name=N1.VAL_6)
        self.check_letter_input(*self.locator.VAL_6, name=N1.VAL_6)
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.VAL_7, name=N1.VAL_7)
        self.check_zero_value_input(*self.locator.VAL_7, name=N1.VAL_7)
        self.check_special_symbol_input(*self.locator.VAL_7, name=N1.VAL_7)
        self.check_letter_input(*self.locator.VAL_7, name=N1.VAL_7)

        self.max_symbol_12_input(*self.locator.VAL_8, name=N1.VAL_8)
        self.check_zero_value_input(*self.locator.VAL_8, name=N1.VAL_8)
        self.check_special_symbol_input(*self.locator.VAL_8, name=N1.VAL_8)
        self.check_letter_input(*self.locator.VAL_8, name=N1.VAL_8)

        self.max_symbol_12_input(*self.locator.VAL_9, name=N1.VAL_9)
        self.check_zero_value_input(*self.locator.VAL_9, name=N1.VAL_9)
        self.check_special_symbol_input(*self.locator.VAL_9, name=N1.VAL_9)
        self.check_letter_input(*self.locator.VAL_9, name=N1.VAL_9)

        self.max_symbol_12_input(*self.locator.VAL_10, name=N1.VAL_10)
        self.check_zero_value_input(*self.locator.VAL_10, name=N1.VAL_10)
        self.check_special_symbol_input(*self.locator.VAL_10, name=N1.VAL_10)
        self.check_letter_input(*self.locator.VAL_10, name=N1.VAL_10)

        self.max_symbol_12_input(*self.locator.VAL_11, name=N1.VAL_11)
        self.check_zero_value_input(*self.locator.VAL_11, name=N1.VAL_11)
        self.check_special_symbol_input(*self.locator.VAL_11, name=N1.VAL_11)
        self.check_letter_input(*self.locator.VAL_11, name=N1.VAL_11)

        self.max_symbol_12_input(*self.locator.VAL_12, name=N1.VAL_12)
        self.check_zero_value_input(*self.locator.VAL_12, name=N1.VAL_12)
        self.check_special_symbol_input(*self.locator.VAL_12, name=N1.VAL_12)
        self.check_letter_input(*self.locator.VAL_12, name=N1.VAL_12)
        self.scroll('400')
        self.max_symbol_12_input(*self.locator.VAL_13, name=N1.VAL_13)
        self.check_zero_value_input(*self.locator.VAL_13, name=N1.VAL_13)
        self.check_special_symbol_input(*self.locator.VAL_13, name=N1.VAL_13)
        self.check_letter_input(*self.locator.VAL_13, name=N1.VAL_13)

        self.max_symbol_12_input(*self.locator.VAL_14, name=N1.VAL_14)
        self.check_zero_value_input(*self.locator.VAL_14, name=N1.VAL_14)
        self.check_special_symbol_input(*self.locator.VAL_14, name=N1.VAL_14)
        self.check_letter_input(*self.locator.VAL_14, name=N1.VAL_14)
        self.find_element(*self.locator.AFTER).click()

    def second_validation_page_2(self):
        # ВИД АЛКОГОЛЬНОЙ ПРОДУКЦИИ
        self.scroll('500')
        self.max_symbol_15_input(*self.locator02.ALC_TYPE, name=N2.ALC_TYPE)
        self.check_zero_value_input(*self.locator02.ALC_TYPE, name=N2.ALC_TYPE)
        self.check_special_symbol_input(*self.locator02.ALC_TYPE, name=N2.ALC_TYPE)
        self.check_letter_input(*self.locator02.ALC_TYPE, name=N2.ALC_TYPE)
        # Облагаемые операции по алкогольной продукции
        self.max_symbol_12_input(*self.locator02.OP1, name=N2.OP1)
        self.check_zero_value_input(*self.locator02.OP1, name=N2.OP1)
        self.check_special_symbol_input(*self.locator02.OP1, name=N2.OP1)
        self.check_letter_input(*self.locator02.OP1, name=N2.OP1)

        self.max_symbol_12_input(*self.locator02.OP2, name=N2.OP2)
        self.check_zero_value_input(*self.locator02.OP2, name=N2.OP2)
        self.check_special_symbol_input(*self.locator02.OP2, name=N2.OP2)
        self.check_letter_input(*self.locator02.OP2, name=N2.OP2)

        self.max_symbol_12_input(*self.locator02.OP3, name=N2.OP3)
        self.check_zero_value_input(*self.locator02.OP3, name=N2.OP3)
        self.check_special_symbol_input(*self.locator02.OP3, name=N2.OP3)
        self.check_letter_input(*self.locator02.OP3, name=N2.OP3)

        self.max_symbol_12_input(*self.locator02.OP4, name=N2.OP4)
        self.check_zero_value_input(*self.locator02.OP4, name=N2.OP4)
        self.check_special_symbol_input(*self.locator02.OP4, name=N2.OP4)
        self.check_letter_input(*self.locator02.OP4, name=N2.OP4)

        self.max_symbol_12_input(*self.locator02.OP5, name=N2.OP5)
        self.check_zero_value_input(*self.locator02.OP5, name=N2.OP5)
        self.check_special_symbol_input(*self.locator02.OP5, name=N2.OP5)
        self.check_letter_input(*self.locator02.OP5, name=N2.OP5)

        self.max_symbol_12_input(*self.locator02.OP6, name=N2.OP6)
        self.check_zero_value_input(*self.locator02.OP6, name=N2.OP6)
        self.check_special_symbol_input(*self.locator02.OP6, name=N2.OP6)
        self.check_letter_input(*self.locator02.OP6, name=N2.OP6)

        self.max_symbol_12_input(*self.locator02.OP7, name=N2.OP7)
        self.check_zero_value_input(*self.locator02.OP7, name=N2.OP7)
        self.check_special_symbol_input(*self.locator02.OP7, name=N2.OP7)
        self.check_letter_input(*self.locator02.OP7, name=N2.OP7)

        self.max_symbol_12_input(*self.locator02.OP8, name=N2.OP8)
        self.check_zero_value_input(*self.locator02.OP8, name=N2.OP8)
        self.check_special_symbol_input(*self.locator02.OP8, name=N2.OP8)
        self.check_letter_input(*self.locator02.OP8, name=N2.OP8)
        self.scroll('700')

        self.max_symbol_12_input(*self.locator02.KM1, name=N2.KM1)
        self.check_zero_value_input(*self.locator02.KM1, name=N2.KM1)
        self.check_special_symbol_input(*self.locator02.KM1, name=N2.KM1)
        self.check_letter_input(*self.locator02.KM1, name=N2.KM1)

        self.max_symbol_12_input(*self.locator02.ET1, name=N2.ET1)
        self.check_zero_value_input(*self.locator02.ET1, name=N2.ET1)
        self.check_special_symbol_input(*self.locator02.ET1, name=N2.ET1)
        self.check_letter_input(*self.locator02.ET1, name=N2.ET1)

        self.max_symbol_12_input(*self.locator02.KM2, name=N2.KM2)
        self.check_zero_value_input(*self.locator02.KM2, name=N2.KM2)
        self.check_special_symbol_input(*self.locator02.KM2, name=N2.KM2)
        self.check_letter_input(*self.locator02.KM2, name=N2.KM2)

        self.max_symbol_12_input(*self.locator02.ET2, name=N2.ET2)
        self.check_zero_value_input(*self.locator02.ET2, name=N2.ET2)
        self.check_special_symbol_input(*self.locator02.ET2, name=N2.ET2)
        self.check_letter_input(*self.locator02.ET2, name=N2.ET2)

        self.max_symbol_12_input(*self.locator02.KM3, name=N2.KM3)
        self.check_zero_value_input(*self.locator02.KM3, name=N2.KM3)
        self.check_special_symbol_input(*self.locator02.KM3, name=N2.KM3)
        self.check_letter_input(*self.locator02.KM3, name=N2.KM3)

        self.max_symbol_12_input(*self.locator02.ET3, name=N2.ET3)
        self.check_zero_value_input(*self.locator02.ET3, name=N2.ET3)
        self.check_special_symbol_input(*self.locator02.ET3, name=N2.ET3)
        self.check_letter_input(*self.locator02.ET3, name=N2.ET3)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator02.EXCISE_RATE, name=N2.EXCISE_RATE)
        self.check_zero_value_input(*self.locator02.EXCISE_RATE, name=N2.EXCISE_RATE)
        self.check_special_symbol_input(*self.locator02.EXCISE_RATE, name=N2.EXCISE_RATE)
        self.check_letter_input(*self.locator02.EXCISE_RATE, name=N2.EXCISE_RATE)
        # ДОДЕЛАТЬ ПОСЛЕ ФИКСА






    def second_validation_page_3(self):
        self.scroll('400')
        self.max_symbol_24_input(*self.locator03.TOBACCO_TYPE, name=N3.TOBACCO_TYPE)
        self.check_zero_value_input(*self.locator03.TOBACCO_TYPE, name=N3.TOBACCO_TYPE)
        self.check_special_symbol_input(*self.locator03.TOBACCO_TYPE, name=N3.TOBACCO_TYPE)
        self.check_letter_input(*self.locator03.TOBACCO_TYPE, name=N3.TOBACCO_TYPE)

        self.max_symbol_12_input(*self.locator03.TOBACCO_OP1, name=N3.TOBACCO_OP1)
        self.check_zero_value_input(*self.locator03.TOBACCO_OP1, name=N3.TOBACCO_OP1)
        self.check_special_symbol_input(*self.locator03.TOBACCO_OP1, name=N3.TOBACCO_OP1)
        self.check_letter_input(*self.locator03.TOBACCO_OP1, name=N3.TOBACCO_OP1)

        self.max_symbol_12_input(*self.locator03.TOBACCO_OP2, name=N3.TOBACCO_OP2)
        self.check_zero_value_input(*self.locator03.TOBACCO_OP2, name=N3.TOBACCO_OP2)
        self.check_special_symbol_input(*self.locator03.TOBACCO_OP2, name=N3.TOBACCO_OP2)
        self.check_letter_input(*self.locator03.TOBACCO_OP2, name=N3.TOBACCO_OP2)

        self.max_symbol_12_input(*self.locator03.TOBACCO_OP3, name=N3.TOBACCO_OP3)
        self.check_zero_value_input(*self.locator03.TOBACCO_OP3, name=N3.TOBACCO_OP3)
        self.check_special_symbol_input(*self.locator03.TOBACCO_OP3, name=N3.TOBACCO_OP3)
        self.check_letter_input(*self.locator03.TOBACCO_OP3, name=N3.TOBACCO_OP3)

        self.max_symbol_12_input(*self.locator03.TOBACCO_OP4, name=N3.TOBACCO_OP4)
        self.check_zero_value_input(*self.locator03.TOBACCO_OP4, name=N3.TOBACCO_OP4)
        self.check_special_symbol_input(*self.locator03.TOBACCO_OP4, name=N3.TOBACCO_OP4)
        self.check_letter_input(*self.locator03.TOBACCO_OP4, name=N3.TOBACCO_OP4)

        self.max_symbol_12_input(*self.locator03.TOBACCO_OP5, name=N3.TOBACCO_OP5)
        self.check_zero_value_input(*self.locator03.TOBACCO_OP5, name=N3.TOBACCO_OP5)
        self.check_special_symbol_input(*self.locator03.TOBACCO_OP5, name=N3.TOBACCO_OP5)
        self.check_letter_input(*self.locator03.TOBACCO_OP5, name=N3.TOBACCO_OP5)

        self.max_symbol_12_input(*self.locator03.TOBACCO_OP6, name=N3.TOBACCO_OP6)
        self.check_zero_value_input(*self.locator03.TOBACCO_OP6, name=N3.TOBACCO_OP6)
        self.check_special_symbol_input(*self.locator03.TOBACCO_OP6, name=N3.TOBACCO_OP6)
        self.check_letter_input(*self.locator03.TOBACCO_OP6, name=N3.TOBACCO_OP6)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator03.KAZ_REAL, name=N3.KAZ_REAL)
        self.check_zero_value_input(*self.locator03.KAZ_REAL, name=N3.KAZ_REAL)
        self.check_special_symbol_input(*self.locator03.KAZ_REAL, name=N3.KAZ_REAL)
        self.check_letter_input(*self.locator03.KAZ_REAL, name=N3.KAZ_REAL)

        self.max_symbol_12_input(*self.locator03.EXPORT_REAL, name=N3.EXPORT_REAL)
        self.check_zero_value_input(*self.locator03.EXPORT_REAL, name=N3.EXPORT_REAL)
        self.check_special_symbol_input(*self.locator03.EXPORT_REAL, name=N3.EXPORT_REAL)
        self.check_letter_input(*self.locator03.EXPORT_REAL, name=N3.EXPORT_REAL)

        self.max_symbol_12_input(*self.locator03.TAX_CORRECT, name=N3.TAX_CORRECT)
        self.check_zero_value_input(*self.locator03.TAX_CORRECT, name=N3.TAX_CORRECT)
        self.check_special_symbol_input(*self.locator03.TAX_CORRECT, name=N3.TAX_CORRECT)
        self.check_letter_input(*self.locator03.TAX_CORRECT, name=N3.TAX_CORRECT)

        self.max_symbol_12_input(*self.locator03.DAMAGED, name=N3.DAMAGED)
        self.check_zero_value_input(*self.locator03.DAMAGED, name=N3.DAMAGED)
        self.check_special_symbol_input(*self.locator03.DAMAGED, name=N3.DAMAGED)
        self.check_letter_input(*self.locator03.DAMAGED, name=N3.DAMAGED)
        self.scroll('400')

        self.max_symbol_12_input(*self.locator03.AMOUNT1, name=N3.AMOUNT1)
        self.check_zero_value_input(*self.locator03.AMOUNT1, name=N3.AMOUNT1)
        self.check_special_symbol_input(*self.locator03.AMOUNT1, name=N3.AMOUNT1)
        self.check_letter_input(*self.locator03.AMOUNT1, name=N3.AMOUNT1)

        self.max_symbol_12_input(*self.locator03.AMOUNT2, name=N3.AMOUNT2)
        self.check_zero_value_input(*self.locator03.AMOUNT2, name=N3.AMOUNT2)
        self.check_special_symbol_input(*self.locator03.AMOUNT2, name=N3.AMOUNT2)
        self.check_letter_input(*self.locator03.AMOUNT2, name=N3.AMOUNT2)

        self.max_symbol_12_input(*self.locator03.AMOUNT3, name=N3.AMOUNT3)
        self.check_zero_value_input(*self.locator03.AMOUNT3, name=N3.AMOUNT3)
        self.check_special_symbol_input(*self.locator03.AMOUNT3, name=N3.AMOUNT3)
        self.check_letter_input(*self.locator03.AMOUNT3, name=N3.AMOUNT3)

        self.max_symbol_12_input(*self.locator03.AMOUNT4, name=N3.AMOUNT4)
        self.check_zero_value_input(*self.locator03.AMOUNT4, name=N3.AMOUNT4)
        self.check_special_symbol_input(*self.locator03.AMOUNT4, name=N3.AMOUNT4)
        self.check_letter_input(*self.locator03.AMOUNT4, name=N3.AMOUNT4)
        self.scroll('400')

        self.max_symbol_12_input(*self.locator03.EXCISE_RATE, name=N3.EXCISE_RATE)
        self.check_zero_value_input(*self.locator03.EXCISE_RATE, name=N3.EXCISE_RATE)
        self.check_special_symbol_input(*self.locator03.EXCISE_RATE, name=N3.EXCISE_RATE)
        self.check_letter_input(*self.locator03.EXCISE_RATE, name=N3.EXCISE_RATE)

        self.max_symbol_12_input(*self.locator03.EXCISE_SUM, name=N3.EXCISE_SUM)
        self.check_zero_value_input(*self.locator03.EXCISE_SUM, name=N3.EXCISE_SUM)
        self.check_special_symbol_input(*self.locator03.EXCISE_SUM, name=N3.EXCISE_SUM)
        self.check_letter_input(*self.locator03.EXCISE_SUM, name=N3.EXCISE_SUM)
        self.find_element(*self.locator.AFTER).click()

    def second_validation_page_4(self):
        self.scroll('100')
        self.max_symbol_12_input(*self.locator04.OIL_REAL, name=N4.OIL_REAL)
        self.check_zero_value_input(*self.locator04.OIL_REAL, name=N4.OIL_REAL)
        self.check_special_symbol_input(*self.locator04.OIL_REAL, name=N4.OIL_REAL)
        self.check_letter_input(*self.locator04.OIL_REAL, name=N4.OIL_REAL)

        self.max_symbol_12_input(*self.locator04.EXPORT_OIL1, name=N4.EXPORT_OIL1)
        self.check_zero_value_input(*self.locator04.EXPORT_OIL1, name=N4.EXPORT_OIL1)
        self.check_special_symbol_input(*self.locator04.EXPORT_OIL1, name=N4.EXPORT_OIL1)
        self.check_letter_input(*self.locator04.EXPORT_OIL1, name=N4.EXPORT_OIL1)

        self.max_symbol_12_input(*self.locator04.EXPORT_OIL2, name=N4.EXPORT_OIL2)
        self.check_zero_value_input(*self.locator04.EXPORT_OIL2, name=N4.EXPORT_OIL2)
        self.check_special_symbol_input(*self.locator04.EXPORT_OIL2, name=N4.EXPORT_OIL2)
        self.check_letter_input(*self.locator04.EXPORT_OIL2, name=N4.EXPORT_OIL2)
        self.scroll('500')
        self.max_symbol_12_input(*self.locator04.USING1, name=N4.USING1)
        self.check_zero_value_input(*self.locator04.USING1, name=N4.USING1)
        self.check_special_symbol_input(*self.locator04.USING1, name=N4.USING1)
        self.check_letter_input(*self.locator04.USING1, name=N4.USING1)

        self.max_symbol_12_input(*self.locator04.USING2, name=N4.USING2)
        self.check_zero_value_input(*self.locator04.USING2, name=N4.USING2)
        self.check_special_symbol_input(*self.locator04.USING2, name=N4.USING2)
        self.check_letter_input(*self.locator04.USING2, name=N4.USING2)

        self.max_symbol_12_input(*self.locator04.USING3, name=N4.USING3)
        self.check_zero_value_input(*self.locator04.USING3, name=N4.USING3)
        self.check_special_symbol_input(*self.locator04.USING3, name=N4.USING3)
        self.check_letter_input(*self.locator04.USING3, name=N4.USING3)

        self.max_symbol_12_input(*self.locator04.USING4, name=N4.USING4)
        self.check_zero_value_input(*self.locator04.USING4, name=N4.USING4)
        self.check_special_symbol_input(*self.locator04.USING4, name=N4.USING4)
        self.check_letter_input(*self.locator04.USING4, name=N4.USING4)

        self.max_symbol_12_input(*self.locator04.USING5, name=N4.USING5)
        self.check_zero_value_input(*self.locator04.USING5, name=N4.USING5)
        self.check_special_symbol_input(*self.locator04.USING5, name=N4.USING5)
        self.check_letter_input(*self.locator04.USING5, name=N4.USING5)

        self.max_symbol_12_input(*self.locator04.USING6, name=N4.USING6)
        self.check_zero_value_input(*self.locator04.USING6, name=N4.USING6)
        self.check_special_symbol_input(*self.locator04.USING6, name=N4.USING6)
        self.check_letter_input(*self.locator04.USING6, name=N4.USING6)

        self.max_symbol_12_input(*self.locator04.USING7, name=N4.USING7)
        self.check_zero_value_input(*self.locator04.USING7, name=N4.USING7)
        self.check_special_symbol_input(*self.locator04.USING7, name=N4.USING7)
        self.check_letter_input(*self.locator04.USING7, name=N4.USING7)

        self.max_symbol_12_input(*self.locator04.USING8, name=N4.USING8)
        self.check_zero_value_input(*self.locator04.USING8, name=N4.USING8)
        self.check_special_symbol_input(*self.locator04.USING8, name=N4.USING8)
        self.check_letter_input(*self.locator04.USING8, name=N4.USING8)
        self.scroll('500')

        self.max_symbol_4_input(*self.locator04.TON_RATE, name=N4.TON_RATE)
        self.check_zero_value_input(*self.locator04.TON_RATE, name=N4.TON_RATE)
        self.check_special_symbol_input(*self.locator04.TON_RATE, name=N4.TON_RATE)
        self.check_letter_input(*self.locator04.TON_RATE, name=N4.TON_RATE)
        self.find_element(*self.locator.AFTER).click()

    def second_validation_page_5(self):
        self.scroll('500')
        self.max_symbol_12_input(*self.locator05.OPT_1, name=N5.OPT_1)
        self.check_zero_value_input(*self.locator05.OPT_1, name=N5.OPT_1)
        self.check_special_symbol_input(*self.locator05.OPT_1, name=N5.OPT_1)
        self.check_letter_input(*self.locator05.OPT_1, name=N5.OPT_1)

        self.max_symbol_5_input(*self.locator05.OPT_2, name=N5.OPT_2)
        self.check_zero_value_input(*self.locator05.OPT_2, name=N5.OPT_2)
        self.check_special_symbol_input(*self.locator05.OPT_2, name=N5.OPT_2)
        self.check_letter_input(*self.locator05.OPT_2, name=N5.OPT_2)

        self.max_symbol_12_input(*self.locator05.OPT_3, name=N5.OPT_3)
        self.check_zero_value_input(*self.locator05.OPT_3, name=N5.OPT_3)
        self.check_special_symbol_input(*self.locator05.OPT_3, name=N5.OPT_3)
        self.check_letter_input(*self.locator05.OPT_3, name=N5.OPT_3)

        self.max_symbol_5_input(*self.locator05.OPT_4, name=N5.OPT_4)
        self.check_zero_value_input(*self.locator05.OPT_4, name=N5.OPT_4)
        self.check_special_symbol_input(*self.locator05.OPT_4, name=N5.OPT_4)
        self.check_letter_input(*self.locator05.OPT_4, name=N5.OPT_4)

        self.max_symbol_12_input(*self.locator05.OPT_5, name=N5.OPT_5)
        self.check_zero_value_input(*self.locator05.OPT_5, name=N5.OPT_5)
        self.check_special_symbol_input(*self.locator05.OPT_5, name=N5.OPT_5)
        self.check_letter_input(*self.locator05.OPT_5, name=N5.OPT_5)

        self.max_symbol_5_input(*self.locator05.OPT_6, name=N5.OPT_6)
        self.check_zero_value_input(*self.locator05.OPT_6, name=N5.OPT_6)
        self.check_special_symbol_input(*self.locator05.OPT_6, name=N5.OPT_6)
        self.check_letter_input(*self.locator05.OPT_6, name=N5.OPT_6)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator05.OPT_7, name=N5.OPT_7)
        self.check_zero_value_input(*self.locator05.OPT_7, name=N5.OPT_7)
        self.check_special_symbol_input(*self.locator05.OPT_7, name=N5.OPT_7)
        self.check_letter_input(*self.locator05.OPT_7, name=N5.OPT_7)

        self.max_symbol_5_input(*self.locator05.OPT_8, name=N5.OPT_8)
        self.check_zero_value_input(*self.locator05.OPT_8, name=N5.OPT_8)
        self.check_special_symbol_input(*self.locator05.OPT_8, name=N5.OPT_8)
        self.check_letter_input(*self.locator05.OPT_8, name=N5.OPT_8)

        self.max_symbol_12_input(*self.locator05.OPT_9, name=N5.OPT_9)
        self.check_zero_value_input(*self.locator05.OPT_9, name=N5.OPT_9)
        self.check_special_symbol_input(*self.locator05.OPT_9, name=N5.OPT_9)
        self.check_letter_input(*self.locator05.OPT_9, name=N5.OPT_9)

        self.max_symbol_5_input(*self.locator05.OPT_10, name=N5.OPT_10)
        self.check_zero_value_input(*self.locator05.OPT_10, name=N5.OPT_10)
        self.check_special_symbol_input(*self.locator05.OPT_10, name=N5.OPT_10)
        self.check_letter_input(*self.locator05.OPT_10, name=N5.OPT_10)
        self.scroll('600')

        self.max_symbol_12_input(*self.locator05.ROZN_1, name=N5.ROZN_1)
        self.check_zero_value_input(*self.locator05.ROZN_1, name=N5.ROZN_1)
        self.check_special_symbol_input(*self.locator05.ROZN_1, name=N5.ROZN_1)
        self.check_letter_input(*self.locator05.ROZN_1, name=N5.ROZN_1)

        self.max_symbol_5_input(*self.locator05.ROZN_2, name=N5.ROZN_2)
        self.check_zero_value_input(*self.locator05.ROZN_2, name=N5.ROZN_2)
        self.check_special_symbol_input(*self.locator05.ROZN_2, name=N5.ROZN_2)
        self.check_letter_input(*self.locator05.ROZN_2, name=N5.ROZN_2)

        self.max_symbol_12_input(*self.locator05.ROZN_3, name=N5.ROZN_3)
        self.check_zero_value_input(*self.locator05.ROZN_3, name=N5.ROZN_3)
        self.check_special_symbol_input(*self.locator05.ROZN_3, name=N5.ROZN_3)
        self.check_letter_input(*self.locator05.ROZN_3, name=N5.ROZN_3)

        self.max_symbol_5_input(*self.locator05.ROZN_4, name=N5.ROZN_4)
        self.check_zero_value_input(*self.locator05.ROZN_4, name=N5.ROZN_4)
        self.check_special_symbol_input(*self.locator05.ROZN_4, name=N5.ROZN_4)
        self.check_letter_input(*self.locator05.ROZN_4, name=N5.ROZN_4)

        self.max_symbol_12_input(*self.locator05.ROZN_5, name=N5.ROZN_5)
        self.check_zero_value_input(*self.locator05.ROZN_2, name=N5.ROZN_5)
        self.check_special_symbol_input(*self.locator05.ROZN_5, name=N5.ROZN_5)
        self.check_letter_input(*self.locator05.ROZN_5, name=N5.ROZN_5)

        self.max_symbol_5_input(*self.locator05.ROZN_6, name=N5.ROZN_6)
        self.check_zero_value_input(*self.locator05.ROZN_6, name=N5.ROZN_6)
        self.check_special_symbol_input(*self.locator05.ROZN_6, name=N5.ROZN_6)
        self.check_letter_input(*self.locator05.ROZN_6, name=N5.ROZN_6)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator05.ROZN_7, name=N5.ROZN_7)
        self.check_zero_value_input(*self.locator05.ROZN_7, name=N5.ROZN_7)
        self.check_special_symbol_input(*self.locator05.ROZN_7, name=N5.ROZN_7)
        self.check_letter_input(*self.locator05.ROZN_7, name=N5.ROZN_7)

        self.max_symbol_5_input(*self.locator05.ROZN_8, name=N5.ROZN_8)
        self.check_zero_value_input(*self.locator05.ROZN_8, name=N5.ROZN_8)
        self.check_special_symbol_input(*self.locator05.ROZN_8, name=N5.ROZN_8)
        self.check_letter_input(*self.locator05.ROZN_8, name=N5.ROZN_8)

        self.max_symbol_12_input(*self.locator05.ROZN_9, name=N5.ROZN_9)
        self.check_zero_value_input(*self.locator05.ROZN_9, name=N5.ROZN_9)
        self.check_special_symbol_input(*self.locator05.ROZN_9, name=N5.ROZN_9)
        self.check_letter_input(*self.locator05.ROZN_9, name=N5.ROZN_9)

        self.max_symbol_5_input(*self.locator05.ROZN_10, name=N5.ROZN_10)
        self.check_zero_value_input(*self.locator05.ROZN_10, name=N5.ROZN_10)
        self.check_special_symbol_input(*self.locator05.ROZN_10, name=N5.ROZN_10)
        self.check_letter_input(*self.locator05.ROZN_10, name=N5.ROZN_10)

        self.max_symbol_12_input(*self.locator05.ROZN_11, name=N5.ROZN_11)
        self.check_zero_value_input(*self.locator05.ROZN_11, name=N5.ROZN_11)
        self.check_special_symbol_input(*self.locator05.ROZN_11, name=N5.ROZN_11)
        self.check_letter_input(*self.locator05.ROZN_11, name=N5.ROZN_11)

        self.max_symbol_5_input(*self.locator05.ROZN_12, name=N5.ROZN_12)
        self.check_zero_value_input(*self.locator05.ROZN_12, name=N5.ROZN_12)
        self.check_special_symbol_input(*self.locator05.ROZN_12, name=N5.ROZN_12)
        self.check_letter_input(*self.locator05.ROZN_12, name=N5.ROZN_12)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator05.ROZN_13, name=N5.ROZN_13)
        self.check_zero_value_input(*self.locator05.ROZN_13, name=N5.ROZN_13)
        self.check_special_symbol_input(*self.locator05.ROZN_13, name=N5.ROZN_13)
        self.check_letter_input(*self.locator05.ROZN_13, name=N5.ROZN_13)

        self.max_symbol_5_input(*self.locator05.ROZN_14, name=N5.ROZN_14)
        self.check_zero_value_input(*self.locator05.ROZN_14, name=N5.ROZN_14)
        self.check_special_symbol_input(*self.locator05.ROZN_14, name=N5.ROZN_14)
        self.check_letter_input(*self.locator05.ROZN_14, name=N5.ROZN_14)
        self.scroll('600')

        self.max_symbol_12_input(*self.locator05.DOPT_1, name=N5.DOPT_1)
        self.check_zero_value_input(*self.locator05.DOPT_1, name=N5.DOPT_1)
        self.check_special_symbol_input(*self.locator05.DOPT_1, name=N5.DOPT_1)
        self.check_letter_input(*self.locator05.DOPT_1, name=N5.DOPT_1)

        self.max_symbol_5_input(*self.locator05.DOPT_2, name=N5.DOPT_2)
        self.check_zero_value_input(*self.locator05.DOPT_2, name=N5.DOPT_2)
        self.check_special_symbol_input(*self.locator05.DOPT_2, name=N5.DOPT_2)
        self.check_letter_input(*self.locator05.DOPT_2, name=N5.DOPT_2)

        self.max_symbol_12_input(*self.locator05.DOPT_3, name=N5.DOPT_3)
        self.check_zero_value_input(*self.locator05.DOPT_3, name=N5.DOPT_3)
        self.check_special_symbol_input(*self.locator05.DOPT_3, name=N5.DOPT_3)
        self.check_letter_input(*self.locator05.DOPT_3, name=N5.DOPT_3)

        self.max_symbol_5_input(*self.locator05.DOPT_4, name=N5.DOPT_4)
        self.check_zero_value_input(*self.locator05.DOPT_4, name=N5.DOPT_4)
        self.check_special_symbol_input(*self.locator05.DOPT_4, name=N5.DOPT_4)
        self.check_letter_input(*self.locator05.DOPT_4, name=N5.DOPT_4)

        self.max_symbol_12_input(*self.locator05.DOPT_5, name=N5.DOPT_5)
        self.check_zero_value_input(*self.locator05.DOPT_5, name=N5.DOPT_5)
        self.check_special_symbol_input(*self.locator05.DOPT_5, name=N5.DOPT_5)
        self.check_letter_input(*self.locator05.DOPT_5, name=N5.DOPT_5)

        self.max_symbol_5_input(*self.locator05.DOPT_6, name=N5.DOPT_6)
        self.check_zero_value_input(*self.locator05.DOPT_6, name=N5.DOPT_6)
        self.check_special_symbol_input(*self.locator05.DOPT_6, name=N5.DOPT_6)
        self.check_letter_input(*self.locator05.DOPT_6, name=N5.DOPT_6)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator05.DOPT_7, name=N5.DOPT_7)
        self.check_zero_value_input(*self.locator05.DOPT_7, name=N5.DOPT_7)
        self.check_special_symbol_input(*self.locator05.DOPT_7, name=N5.DOPT_7)
        self.check_letter_input(*self.locator05.DOPT_7, name=N5.DOPT_7)

        self.max_symbol_5_input(*self.locator05.DOPT_8, name=N5.DOPT_8)
        self.check_zero_value_input(*self.locator05.DOPT_8, name=N5.DOPT_8)
        self.check_special_symbol_input(*self.locator05.DOPT_8, name=N5.DOPT_8)
        self.check_letter_input(*self.locator05.DOPT_8, name=N5.DOPT_8)

        self.max_symbol_12_input(*self.locator05.DOPT_9, name=N5.DOPT_9)
        self.check_zero_value_input(*self.locator05.DOPT_9, name=N5.DOPT_9)
        self.check_special_symbol_input(*self.locator05.DOPT_9, name=N5.DOPT_9)
        self.check_letter_input(*self.locator05.DOPT_9, name=N5.DOPT_9)

        self.max_symbol_5_input(*self.locator05.DOPT_10, name=N5.DOPT_10)
        self.check_zero_value_input(*self.locator05.DOPT_10, name=N5.DOPT_10)
        self.check_special_symbol_input(*self.locator05.DOPT_10, name=N5.DOPT_10)
        self.check_letter_input(*self.locator05.DOPT_10, name=N5.DOPT_10)
        self.scroll('500')

        self.max_symbol_12_input(*self.locator05.DROZ_1, name=N5.DROZ_1)
        self.check_zero_value_input(*self.locator05.DROZ_1, name=N5.DROZ_1)
        self.check_special_symbol_input(*self.locator05.DROZ_1, name=N5.DROZ_1)
        self.check_letter_input(*self.locator05.DROZ_1, name=N5.DROZ_1)

        self.max_symbol_5_input(*self.locator05.DROZ_2, name=N5.DROZ_2)
        self.check_zero_value_input(*self.locator05.DROZ_2, name=N5.DROZ_2)
        self.check_special_symbol_input(*self.locator05.DROZ_2, name=N5.DROZ_2)
        self.check_letter_input(*self.locator05.DROZ_2, name=N5.DROZ_2)

        self.max_symbol_12_input(*self.locator05.DROZ_3, name=N5.DROZ_3)
        self.check_zero_value_input(*self.locator05.DROZ_3, name=N5.DROZ_3)
        self.check_special_symbol_input(*self.locator05.DROZ_3, name=N5.DROZ_3)
        self.check_letter_input(*self.locator05.DROZ_3, name=N5.DROZ_3)

        self.max_symbol_5_input(*self.locator05.DROZ_4, name=N5.DROZ_4)
        self.check_zero_value_input(*self.locator05.DROZ_4, name=N5.DROZ_4)
        self.check_special_symbol_input(*self.locator05.DROZ_4, name=N5.DROZ_4)
        self.check_letter_input(*self.locator05.DROZ_4, name=N5.DROZ_4)

        self.max_symbol_12_input(*self.locator05.DROZ_5, name=N5.DROZ_5)
        self.check_zero_value_input(*self.locator05.DROZ_5, name=N5.DROZ_5)
        self.check_special_symbol_input(*self.locator05.DROZ_5, name=N5.DROZ_5)
        self.check_letter_input(*self.locator05.DROZ_5, name=N5.DROZ_5)

        self.max_symbol_5_input(*self.locator05.DROZ_6, name=N5.DROZ_6)
        self.check_zero_value_input(*self.locator05.DROZ_2, name=N5.DROZ_6)
        self.check_special_symbol_input(*self.locator05.DROZ_6, name=N5.DROZ_6)
        self.check_letter_input(*self.locator05.DROZ_6, name=N5.DROZ_6)
        self.scroll('600')

        self.max_symbol_12_input(*self.locator05.DROZ_7, name=N5.DROZ_7)
        self.check_zero_value_input(*self.locator05.DROZ_7, name=N5.DROZ_7)
        self.check_special_symbol_input(*self.locator05.DROZ_7, name=N5.DROZ_7)
        self.check_letter_input(*self.locator05.DROZ_7, name=N5.DROZ_7)

        self.max_symbol_5_input(*self.locator05.DROZ_8, name=N5.DROZ_8)
        self.check_zero_value_input(*self.locator05.DROZ_8, name=N5.DROZ_8)
        self.check_special_symbol_input(*self.locator05.DROZ_8, name=N5.DROZ_8)
        self.check_letter_input(*self.locator05.DROZ_8, name=N5.DROZ_8)

        self.max_symbol_12_input(*self.locator05.DROZ_9, name=N5.DROZ_9)
        self.check_zero_value_input(*self.locator05.DROZ_9, name=N5.DROZ_9)
        self.check_special_symbol_input(*self.locator05.DROZ_9, name=N5.DROZ_9)
        self.check_letter_input(*self.locator05.DROZ_9, name=N5.DROZ_9)

        self.max_symbol_5_input(*self.locator05.DROZ_10, name=N5.DROZ_10)
        self.check_zero_value_input(*self.locator05.DROZ_10, name=N5.DROZ_10)
        self.check_special_symbol_input(*self.locator05.DROZ_10, name=N5.DROZ_10)
        self.check_letter_input(*self.locator05.DROZ_10, name=N5.DROZ_10)

        self.max_symbol_12_input(*self.locator05.DROZ_11, name=N5.DROZ_11)
        self.check_zero_value_input(*self.locator05.DROZ_11, name=N5.DROZ_11)
        self.check_special_symbol_input(*self.locator05.DROZ_11, name=N5.DROZ_11)
        self.check_letter_input(*self.locator05.DROZ_11, name=N5.DROZ_11)

        self.max_symbol_5_input(*self.locator05.DROZ_12, name=N5.DROZ_12)
        self.check_zero_value_input(*self.locator05.DROZ_12, name=N5.DROZ_12)
        self.check_special_symbol_input(*self.locator05.DROZ_12, name=N5.DROZ_12)
        self.check_letter_input(*self.locator05.DROZ_12, name=N5.DROZ_12)
        self.scroll('600')

        self.max_symbol_12_input(*self.locator05.DROZ_13, name=N5.DROZ_13)
        self.check_zero_value_input(*self.locator05.DROZ_13, name=N5.DROZ_13)
        self.check_special_symbol_input(*self.locator05.DROZ_13, name=N5.DROZ_13)
        self.check_letter_input(*self.locator05.DROZ_13, name=N5.DROZ_13)

        self.max_symbol_5_input(*self.locator05.DROZ_14, name=N5.DROZ_14)
        self.check_zero_value_input(*self.locator05.DROZ_14, name=N5.DROZ_14)
        self.check_special_symbol_input(*self.locator05.DROZ_14, name=N5.DROZ_14)
        self.check_letter_input(*self.locator05.DROZ_14, name=N5.DROZ_14)

        # Ислисление акциза
        self.max_symbol_12_input(*self.locator05.EXC_PAY2, name=N5.EXC_PAY2)
        self.check_zero_value_input(*self.locator05.EXC_PAY2, name=N5.EXC_PAY2)
        self.check_special_symbol_input(*self.locator05.EXC_PAY2, name=N5.EXC_PAY2)
        self.check_letter_input(*self.locator05.EXC_PAY2, name=N5.EXC_PAY2)
        self.max_symbol_12_input(*self.locator05.EXC_PAY4, name=N5.EXC_PAY4)
        self.check_zero_value_input(*self.locator05.EXC_PAY4, name=N5.EXC_PAY4)
        self.check_special_symbol_input(*self.locator05.EXC_PAY4, name=N5.EXC_PAY4)
        self.check_letter_input(*self.locator05.EXC_PAY4, name=N5.EXC_PAY4)
        self.scroll('500')
        self.max_symbol_12_input(*self.locator05.EXC_PAY6, name=N5.EXC_PAY6)
        self.check_zero_value_input(*self.locator05.EXC_PAY6, name=N5.EXC_PAY6)
        self.check_special_symbol_input(*self.locator05.EXC_PAY6, name=N5.EXC_PAY6)
        self.check_letter_input(*self.locator05.EXC_PAY6, name=N5.EXC_PAY6)
        self.max_symbol_12_input(*self.locator05.EXC_PAY8, name=N5.EXC_PAY8)
        self.check_zero_value_input(*self.locator05.EXC_PAY8, name=N5.EXC_PAY8)
        self.check_special_symbol_input(*self.locator05.EXC_PAY8, name=N5.EXC_PAY8)
        self.check_letter_input(*self.locator05.EXC_PAY8, name=N5.EXC_PAY8)
        self.max_symbol_12_input(*self.locator05.EXC_PAY10, name=N5.EXC_PAY10)
        self.check_zero_value_input(*self.locator05.EXC_PAY10, name=N5.EXC_PAY10)
        self.check_special_symbol_input(*self.locator05.EXC_PAY10, name=N5.EXC_PAY10)
        self.check_letter_input(*self.locator05.EXC_PAY10, name=N5.EXC_PAY10)
        self.max_symbol_12_input(*self.locator05.EXC_PAY12, name=N5.EXC_PAY12)
        self.check_zero_value_input(*self.locator05.EXC_PAY12, name=N5.EXC_PAY12)
        self.check_special_symbol_input(*self.locator05.EXC_PAY12, name=N5.EXC_PAY12)
        self.check_letter_input(*self.locator05.EXC_PAY12, name=N5.EXC_PAY12)
        self.max_symbol_12_input(*self.locator05.EXC_PAY14, name=N5.EXC_PAY14)
        self.check_zero_value_input(*self.locator05.EXC_PAY14, name=N5.EXC_PAY14)
        self.check_special_symbol_input(*self.locator05.EXC_PAY14, name=N5.EXC_PAY14)
        self.check_letter_input(*self.locator05.EXC_PAY14, name=N5.EXC_PAY14)
        self.scroll('500')
        self.max_symbol_12_input(*self.locator05.EXC_PAY16, name=N5.EXC_PAY16)
        self.check_zero_value_input(*self.locator05.EXC_PAY16, name=N5.EXC_PAY16)
        self.check_special_symbol_input(*self.locator05.EXC_PAY16, name=N5.EXC_PAY16)
        self.check_letter_input(*self.locator05.EXC_PAY16, name=N5.EXC_PAY16)
        self.max_symbol_12_input(*self.locator05.EXC_PAY18, name=N5.EXC_PAY18)
        self.check_zero_value_input(*self.locator05.EXC_PAY18, name=N5.EXC_PAY18)
        self.check_special_symbol_input(*self.locator05.EXC_PAY18, name=N5.EXC_PAY18)
        self.check_letter_input(*self.locator05.EXC_PAY18, name=N5.EXC_PAY18)
        self.max_symbol_12_input(*self.locator05.EXC_PAY20, name=N5.EXC_PAY20)
        self.check_zero_value_input(*self.locator05.EXC_PAY20, name=N5.EXC_PAY20)
        self.check_special_symbol_input(*self.locator05.EXC_PAY20, name=N5.EXC_PAY20)
        self.check_letter_input(*self.locator05.EXC_PAY20, name=N5.EXC_PAY20)
        self.max_symbol_12_input(*self.locator05.EXC_PAY22, name=N5.EXC_PAY22)
        self.check_zero_value_input(*self.locator05.EXC_PAY22, name=N5.EXC_PAY22)
        self.check_special_symbol_input(*self.locator05.EXC_PAY22, name=N5.EXC_PAY22)
        self.check_letter_input(*self.locator05.EXC_PAY22, name=N5.EXC_PAY22)
        self.max_symbol_12_input(*self.locator05.EXC_PAY24, name=N5.EXC_PAY24)
        self.check_zero_value_input(*self.locator05.EXC_PAY24, name=N5.EXC_PAY24)
        self.check_special_symbol_input(*self.locator05.EXC_PAY24, name=N5.EXC_PAY24)
        self.check_letter_input(*self.locator05.EXC_PAY24, name=N5.EXC_PAY24)
        self.scroll('500')
        self.find_element(*self.locator.AFTER).click()


    def second_validation_page_6(self):
        self.scroll('500')
        self.find_element(*self.locator06.ADD_STR).click()
        sleep(0.3)
        self.find_element(*self.locator06.QUAL_CODE).click()
        sleep(0.3)
        self.find_element(*self.locator06.QUAL_CODE_SELECT).click()
        sleep(0.5)
        self.max_symbol_12_input(*self.locator06.USED_MATERIALS, name=N6.USED_MATERIALS)
        self.check_zero_value_input(*self.locator06.USED_MATERIALS, name=N6.USED_MATERIALS)
        self.check_special_symbol_input(*self.locator06.USED_MATERIALS, name=N6.USED_MATERIALS)
        self.check_letter_input(*self.locator06.USED_MATERIALS, name=N6.USED_MATERIALS)
        sleep(0.5)
        self.max_symbol_8_input(*self.locator06.EXCISE_RATE, name=N6.EXCISE_RATE)
        self.check_zero_value_input(*self.locator06.EXCISE_RATE, name=N6.EXCISE_RATE)
        self.check_special_symbol_input(*self.locator06.EXCISE_RATE, name=N6.EXCISE_RATE)
        self.check_letter_input(*self.locator06.EXCISE_RATE, name=N6.EXCISE_RATE)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator06.DEDUCTION_AMOUNT, name=N6.DEDUCTION_AMOUNT)
        self.check_zero_value_input(*self.locator06.DEDUCTION_AMOUNT, name=N6.DEDUCTION_AMOUNT)
        self.check_special_symbol_input(*self.locator06.DEDUCTION_AMOUNT, name=N6.DEDUCTION_AMOUNT)
        self.check_letter_input(*self.locator06.DEDUCTION_AMOUNT, name=N6.DEDUCTION_AMOUNT)


    def second_validation_page_7(self):
        self.scroll('500')
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO1, name=N7.EXCISE_NO1)
        self.check_zero_value_input(*self.locator07.EXCISE_NO1, name=N7.EXCISE_NO1)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO1, name=N7.EXCISE_NO1)
        self.check_letter_input(*self.locator07.EXCISE_NO1, name=N7.EXCISE_NO1)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO2, name=N7.EXCISE_NO2)
        self.check_zero_value_input(*self.locator07.EXCISE_NO2, name=N7.EXCISE_NO2)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO2, name=N7.EXCISE_NO2)
        self.check_letter_input(*self.locator07.EXCISE_NO2, name=N7.EXCISE_NO2)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO3, name=N7.EXCISE_NO3)
        self.check_zero_value_input(*self.locator07.EXCISE_NO3, name=N7.EXCISE_NO3)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO3, name=N7.EXCISE_NO3)
        self.check_letter_input(*self.locator07.EXCISE_NO3, name=N7.EXCISE_NO3)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO4, name=N7.EXCISE_NO4)
        self.check_zero_value_input(*self.locator07.EXCISE_NO4, name=N7.EXCISE_NO4)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO4, name=N7.EXCISE_NO4)
        self.check_letter_input(*self.locator07.EXCISE_NO4, name=N7.EXCISE_NO4)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO5, name=N7.EXCISE_NO5)
        self.check_zero_value_input(*self.locator07.EXCISE_NO5, name=N7.EXCISE_NO5)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO5, name=N7.EXCISE_NO5)
        self.check_letter_input(*self.locator07.EXCISE_NO5, name=N7.EXCISE_NO5)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO6, name=N7.EXCISE_NO6)
        self.check_zero_value_input(*self.locator07.EXCISE_NO6, name=N7.EXCISE_NO6)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO6, name=N7.EXCISE_NO6)
        self.check_letter_input(*self.locator07.EXCISE_NO6, name=N7.EXCISE_NO6)
        self.scroll('600')
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO7, name=N7.EXCISE_NO7)
        self.check_zero_value_input(*self.locator07.EXCISE_NO7, name=N7.EXCISE_NO7)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO7, name=N7.EXCISE_NO7)
        self.check_letter_input(*self.locator07.EXCISE_NO7, name=N7.EXCISE_NO7)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO8, name=N7.EXCISE_NO8)
        self.check_zero_value_input(*self.locator07.EXCISE_NO8, name=N7.EXCISE_NO8)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO8, name=N7.EXCISE_NO8)
        self.check_letter_input(*self.locator07.EXCISE_NO8, name=N7.EXCISE_NO8)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO9, name=N7.EXCISE_NO9)
        self.check_zero_value_input(*self.locator07.EXCISE_NO9, name=N7.EXCISE_NO9)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO9, name=N7.EXCISE_NO9)
        self.check_letter_input(*self.locator07.EXCISE_NO9, name=N7.EXCISE_NO9)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO10, name=N7.EXCISE_NO10)
        self.check_zero_value_input(*self.locator07.EXCISE_NO10, name=N7.EXCISE_NO10)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO10, name=N7.EXCISE_NO10)
        self.check_letter_input(*self.locator07.EXCISE_NO10, name=N7.EXCISE_NO10)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO11, name=N7.EXCISE_NO11)
        self.check_zero_value_input(*self.locator07.EXCISE_NO11, name=N7.EXCISE_NO11)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO11, name=N7.EXCISE_NO11)
        self.check_letter_input(*self.locator07.EXCISE_NO11, name=N7.EXCISE_NO11)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO12, name=N7.EXCISE_NO12)
        self.check_zero_value_input(*self.locator07.EXCISE_NO12, name=N7.EXCISE_NO12)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO12, name=N7.EXCISE_NO12)
        self.check_letter_input(*self.locator07.EXCISE_NO12, name=N7.EXCISE_NO12)
        self.scroll('500')
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO13, name=N7.EXCISE_NO13)
        self.check_zero_value_input(*self.locator07.EXCISE_NO13, name=N7.EXCISE_NO13)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO13, name=N7.EXCISE_NO13)
        self.check_letter_input(*self.locator07.EXCISE_NO13, name=N7.EXCISE_NO13)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO14, name=N7.EXCISE_NO14)
        self.check_zero_value_input(*self.locator07.EXCISE_NO14, name=N7.EXCISE_NO14)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO14, name=N7.EXCISE_NO14)
        self.check_letter_input(*self.locator07.EXCISE_NO14, name=N7.EXCISE_NO14)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO15, name=N7.EXCISE_NO15)
        self.check_zero_value_input(*self.locator07.EXCISE_NO15, name=N7.EXCISE_NO15)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO15, name=N7.EXCISE_NO15)
        self.check_letter_input(*self.locator07.EXCISE_NO15, name=N7.EXCISE_NO15)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO16, name=N7.EXCISE_NO16)
        self.check_zero_value_input(*self.locator07.EXCISE_NO16, name=N7.EXCISE_NO16)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO16, name=N7.EXCISE_NO16)
        self.check_letter_input(*self.locator07.EXCISE_NO16, name=N7.EXCISE_NO16)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO17, name=N7.EXCISE_NO17)
        self.check_zero_value_input(*self.locator07.EXCISE_NO17, name=N7.EXCISE_NO17)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO17, name=N7.EXCISE_NO17)
        self.check_letter_input(*self.locator07.EXCISE_NO17, name=N7.EXCISE_NO17)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO18, name=N7.EXCISE_NO18)
        self.check_zero_value_input(*self.locator07.EXCISE_NO18, name=N7.EXCISE_NO18)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO18, name=N7.EXCISE_NO18)
        self.check_letter_input(*self.locator07.EXCISE_NO18, name=N7.EXCISE_NO18)
        self.scroll('600')
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO19, name=N7.EXCISE_NO19)
        self.check_zero_value_input(*self.locator07.EXCISE_NO19, name=N7.EXCISE_NO19)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO19, name=N7.EXCISE_NO19)
        self.check_letter_input(*self.locator07.EXCISE_NO19, name=N7.EXCISE_NO19)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO20, name=N7.EXCISE_NO20)
        self.check_zero_value_input(*self.locator07.EXCISE_NO20, name=N7.EXCISE_NO20)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO20, name=N7.EXCISE_NO20)
        self.check_letter_input(*self.locator07.EXCISE_NO20, name=N7.EXCISE_NO20)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO21, name=N7.EXCISE_NO21)
        self.check_zero_value_input(*self.locator07.EXCISE_NO21, name=N7.EXCISE_NO21)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO21, name=N7.EXCISE_NO21)
        self.check_letter_input(*self.locator07.EXCISE_NO21, name=N7.EXCISE_NO21)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO22, name=N7.EXCISE_NO22)
        self.check_zero_value_input(*self.locator07.EXCISE_NO22, name=N7.EXCISE_NO22)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO22, name=N7.EXCISE_NO22)
        self.check_letter_input(*self.locator07.EXCISE_NO22, name=N7.EXCISE_NO22)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO23, name=N7.EXCISE_NO23)
        self.check_zero_value_input(*self.locator07.EXCISE_NO23, name=N7.EXCISE_NO23)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO23, name=N7.EXCISE_NO23)
        self.check_letter_input(*self.locator07.EXCISE_NO23, name=N7.EXCISE_NO23)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO24, name=N7.EXCISE_NO24)
        self.check_zero_value_input(*self.locator07.EXCISE_NO24, name=N7.EXCISE_NO24)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO24, name=N7.EXCISE_NO24)
        self.check_letter_input(*self.locator07.EXCISE_NO24, name=N7.EXCISE_NO24)
        self.scroll('500')
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO25, name=N7.EXCISE_NO25)
        self.check_zero_value_input(*self.locator07.EXCISE_NO25, name=N7.EXCISE_NO25)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO25, name=N7.EXCISE_NO25)
        self.check_letter_input(*self.locator07.EXCISE_NO25, name=N7.EXCISE_NO25)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.EXCISE_NO26, name=N7.EXCISE_NO26)
        self.check_zero_value_input(*self.locator07.EXCISE_NO26, name=N7.EXCISE_NO26)
        self.check_special_symbol_input(*self.locator07.EXCISE_NO26, name=N7.EXCISE_NO26)
        self.check_letter_input(*self.locator07.EXCISE_NO26, name=N7.EXCISE_NO26)

        #400.07.002

        self.max_symbol_12_input(*self.locator07.ALC_1, name=N7.ALC_1)
        self.check_zero_value_input(*self.locator07.ALC_1, name=N7.ALC_1)
        self.check_special_symbol_input(*self.locator07.ALC_1, name=N7.ALC_1)
        self.check_letter_input(*self.locator07.ALC_1, name=N7.ALC_1)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.ALC_2, name=N7.ALC_2)
        self.check_zero_value_input(*self.locator07.ALC_2, name=N7.ALC_2)
        self.check_special_symbol_input(*self.locator07.ALC_2, name=N7.ALC_2)
        self.check_letter_input(*self.locator07.ALC_2, name=N7.ALC_2)

        #400.07.003

        self.max_symbol_12_input(*self.locator07.ALC_3, name=N7.ALC_3)
        self.check_zero_value_input(*self.locator07.ALC_3, name=N7.ALC_3)
        self.check_special_symbol_input(*self.locator07.ALC_3, name=N7.ALC_3)
        self.check_letter_input(*self.locator07.ALC_3, name=N7.ALC_3)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator07.ALC_4, name=N7.ALC_4)
        self.check_zero_value_input(*self.locator07.ALC_4, name=N7.ALC_4)
        self.check_special_symbol_input(*self.locator07.ALC_4, name=N7.ALC_4)
        self.check_letter_input(*self.locator07.ALC_4, name=N7.ALC_4)
        self.scroll('500')
        self.find_element(*self.locator.AFTER).click()

    def second_validation_page_8(self):
        self.scroll('300')
        self.max_symbol_12_input(*self.locator08.OPER1, name=N8.OPER1)
        self.check_zero_value_input(*self.locator08.OPER1, name=N8.OPER1)
        self.check_special_symbol_input(*self.locator08.OPER1, name=N8.OPER1)
        self.check_letter_input(*self.locator08.OPER1, name=N8.OPER1)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER2, name=N8.OPER2)
        self.check_zero_value_input(*self.locator08.OPER2, name=N8.OPER2)
        self.check_special_symbol_input(*self.locator08.OPER2, name=N8.OPER2)
        self.check_letter_input(*self.locator08.OPER2, name=N8.OPER2)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER3, name=N8.OPER3)
        self.check_zero_value_input(*self.locator08.OPER3, name=N8.OPER3)
        self.check_special_symbol_input(*self.locator08.OPER3, name=N8.OPER3)
        self.check_letter_input(*self.locator08.OPER3, name=N8.OPER3)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER4, name=N8.OPER4)
        self.check_zero_value_input(*self.locator08.OPER4, name=N8.OPER4)
        self.check_special_symbol_input(*self.locator08.OPER4, name=N8.OPER4)
        self.check_letter_input(*self.locator08.OPER4, name=N8.OPER4)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER5, name=N8.OPER5)
        self.check_zero_value_input(*self.locator08.OPER5, name=N8.OPER5)
        self.check_special_symbol_input(*self.locator08.OPER5, name=N8.OPER5)
        self.check_letter_input(*self.locator08.OPER5, name=N8.OPER5)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER6, name=N8.OPER6)
        self.check_zero_value_input(*self.locator08.OPER6, name=N8.OPER6)
        self.check_special_symbol_input(*self.locator08.OPER6, name=N8.OPER6)
        self.check_letter_input(*self.locator08.OPER6, name=N8.OPER6)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER7, name=N8.OPER7)
        self.check_zero_value_input(*self.locator08.OPER7, name=N8.OPER7)
        self.check_special_symbol_input(*self.locator08.OPER7, name=N8.OPER7)
        self.check_letter_input(*self.locator08.OPER7, name=N8.OPER7)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator08.OPER8, name=N8.OPER8)
        self.check_zero_value_input(*self.locator08.OPER8, name=N8.OPER8)
        self.check_special_symbol_input(*self.locator08.OPER8, name=N8.OPER8)
        self.check_letter_input(*self.locator08.OPER8, name=N8.OPER8)
        self.scroll('500')
        self.max_symbol_4_input(*self.locator08.OPER10, name=N8.OPER10)
        self.check_zero_value_input(*self.locator08.OPER10, name=N8.OPER10)
        self.check_special_symbol_input(*self.locator08.OPER10, name=N8.OPER10)
        self.check_letter_input(*self.locator08.OPER10, name=N8.OPER10)




