from browser_interaction import BasePage
from time import sleep
from locators.fno_700_locators import FNO700Locators
from locators.main_page_locators import MainPageLocators
from locators.fno_700_locators import FNO700LocatorsName as N
import allure


class FNO700MaxSymbolAnd0ValueCheck(BasePage):
    def __init__(self, browser):
        super().__init__(browser)
        self.browser = browser
        self.locator = FNO700Locators

        '''Ниже вторая страница'''

    def first_page_validation(self):
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.find_element(*self.locator.CONTROL_TEXT).click()
        self.max_symbol_20_input(*self.locator.NOTICE_NUMBER, name=N.NOTICE_NUMBER)
        self.check_zero_value_input(*self.locator.NOTICE_NUMBER, name=N.NOTICE_NUMBER)
        self.check_special_symbol_input(*self.locator.NOTICE_NUMBER, name=N.NOTICE_NUMBER)
        self.check_letter_input(*self.locator.NOTICE_NUMBER, name=N.NOTICE_NUMBER)
        self.scroll('600')
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES).click()
        sleep(0.3)
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES_SELECT).click()
        self.find_element(*self.locator.CONTROL_TEXT_2).click()
        self.find_element(*self.locator.APPS).click()
        sleep(0.3)
        self.find_element(*self.locator.APPS_SELECT_ALL).click()
        self.find_element(*self.locator.AFTER).click()

    def app_1_validation(self):
        self.find_element(*self.locator.TYPE_OF_TAX).click()
        sleep(0.3)
        self.find_element(*self.locator.TYPE_OF_TAX_SELECT).click(); self.find_element(*self.locator.CHAPTER_1).click()
        self.scroll('800')
        self.max_symbol_5_input(*self.locator.FIRST_1, name=N.FIRST_1)
        self.check_zero_value_input(*self.locator.FIRST_1, name=N.FIRST_1)
        self.check_special_symbol_input(*self.locator.FIRST_1, name=N.FIRST_1)
        self.check_letter_input(*self.locator.FIRST_1, name=N.FIRST_1)

        self.max_symbol_10_input(*self.locator.FIRST_2, name=N.FIRST_2)
        self.check_zero_value_input(*self.locator.FIRST_2, name=N.FIRST_2)
        self.check_special_symbol_input(*self.locator.FIRST_2, name=N.FIRST_2)
        self.check_letter_input(*self.locator.FIRST_2, name=N.FIRST_2)

        self.max_symbol_6_input(*self.locator.FIRST_3, name=N.FIRST_3)
        self.check_zero_value_input(*self.locator.FIRST_3, name=N.FIRST_3)
        self.check_special_symbol_input(*self.locator.FIRST_3, name=N.FIRST_3)
        self.check_letter_input(*self.locator.FIRST_3, name=N.FIRST_3)

        self.max_symbol_5_input(*self.locator.FIRST_4, name=N.FIRST_4)
        self.check_zero_value_input(*self.locator.FIRST_4, name=N.FIRST_4)
        self.check_special_symbol_input(*self.locator.FIRST_4, name=N.FIRST_4)
        self.check_letter_input(*self.locator.FIRST_4, name=N.FIRST_4)

        self.max_symbol_10_input(*self.locator.FIRST_5, name=N.FIRST_5)
        self.check_zero_value_input(*self.locator.FIRST_5, name=N.FIRST_5)
        self.check_special_symbol_input(*self.locator.FIRST_5, name=N.FIRST_5)
        self.check_letter_input(*self.locator.FIRST_5, name=N.FIRST_5)

        self.max_symbol_6_input(*self.locator.FIRST_6, name=N.FIRST_6)
        self.check_zero_value_input(*self.locator.FIRST_6, name=N.FIRST_6)
        self.check_special_symbol_input(*self.locator.FIRST_6, name=N.FIRST_6)
        self.check_letter_input(*self.locator.FIRST_6, name=N.FIRST_6)

        self.max_symbol_5_input(*self.locator.FIRST_7, name=N.FIRST_7)
        self.check_zero_value_input(*self.locator.FIRST_7, name=N.FIRST_7)
        self.check_special_symbol_input(*self.locator.FIRST_7, name=N.FIRST_7)
        self.check_letter_input(*self.locator.FIRST_7, name=N.FIRST_7)

        self.max_symbol_10_input(*self.locator.FIRST_8, name=N.FIRST_8)
        self.check_zero_value_input(*self.locator.FIRST_8, name=N.FIRST_8)
        self.check_special_symbol_input(*self.locator.FIRST_8, name=N.FIRST_8)
        self.check_letter_input(*self.locator.FIRST_8, name=N.FIRST_8)

        self.max_symbol_6_input(*self.locator.FIRST_9, name=N.FIRST_9)
        self.check_zero_value_input(*self.locator.FIRST_9, name=N.FIRST_9)
        self.check_special_symbol_input(*self.locator.FIRST_9, name=N.FIRST_9)
        self.check_letter_input(*self.locator.FIRST_9, name=N.FIRST_9)

        self.max_symbol_5_input(*self.locator.FIRST_10, name=N.FIRST_10)
        self.check_zero_value_input(*self.locator.FIRST_10, name=N.FIRST_10)
        self.check_special_symbol_input(*self.locator.FIRST_10, name=N.FIRST_10)
        self.check_letter_input(*self.locator.FIRST_10, name=N.FIRST_10)

        self.max_symbol_10_input(*self.locator.FIRST_11, name=N.FIRST_11)
        self.check_zero_value_input(*self.locator.FIRST_11, name=N.FIRST_11)
        self.check_special_symbol_input(*self.locator.FIRST_11, name=N.FIRST_11)
        self.check_letter_input(*self.locator.FIRST_11, name=N.FIRST_11)

        self.max_symbol_6_input(*self.locator.FIRST_12, name=N.FIRST_12)
        self.check_zero_value_input(*self.locator.FIRST_12, name=N.FIRST_12)
        self.check_special_symbol_input(*self.locator.FIRST_12, name=N.FIRST_12)
        self.check_letter_input(*self.locator.FIRST_12, name=N.FIRST_12)
        self.find_element(*self.locator.CHAPTER_2).click()
        self.scroll('600')
        self.max_symbol_5_input(*self.locator.SECOND_1, name=N.SECOND_1)
        self.check_zero_value_input(*self.locator.SECOND_1, name=N.SECOND_1)
        self.check_special_symbol_input(*self.locator.SECOND_1, name=N.SECOND_1)
        self.check_letter_input(*self.locator.SECOND_1, name=N.SECOND_1)

        self.max_symbol_10_input(*self.locator.SECOND_2, name=N.SECOND_2)
        self.check_zero_value_input(*self.locator.SECOND_2, name=N.SECOND_2)
        self.check_special_symbol_input(*self.locator.SECOND_2, name=N.SECOND_2)
        self.check_letter_input(*self.locator.SECOND_2, name=N.SECOND_2)

        self.max_symbol_6_input(*self.locator.SECOND_3, name=N.SECOND_3)
        self.check_zero_value_input(*self.locator.SECOND_3, name=N.SECOND_3)
        self.check_special_symbol_input(*self.locator.SECOND_3, name=N.SECOND_3)
        self.check_letter_input(*self.locator.SECOND_3, name=N.SECOND_3)
        self.find_element(*self.locator.CHAPTER_3).click()
        self.scroll('600')
        self.max_symbol_5_input(*self.locator.THIRD_1, name=N.THIRD_1)
        self.check_zero_value_input(*self.locator.THIRD_1, name=N.THIRD_1)
        self.check_special_symbol_input(*self.locator.THIRD_1, name=N.THIRD_1)
        self.check_letter_input(*self.locator.THIRD_1, name=N.THIRD_1)

        self.max_symbol_10_input(*self.locator.THIRD_2, name=N.THIRD_2)
        self.check_zero_value_input(*self.locator.SECOND_2, name=N.THIRD_2)
        self.check_special_symbol_input(*self.locator.THIRD_2, name=N.THIRD_2)
        self.check_letter_input(*self.locator.THIRD_2, name=N.THIRD_2)

        self.max_symbol_6_input(*self.locator.THIRD_3, name=N.THIRD_3)
        self.check_zero_value_input(*self.locator.THIRD_3, name=N.THIRD_3)
        self.check_special_symbol_input(*self.locator.THIRD_3, name=N.THIRD_3)
        self.check_letter_input(*self.locator.THIRD_3, name=N.THIRD_3)

        self.max_symbol_5_input(*self.locator.THIRD_4, name=N.THIRD_4)
        self.check_zero_value_input(*self.locator.THIRD_4, name=N.THIRD_4)
        self.check_special_symbol_input(*self.locator.THIRD_4, name=N.THIRD_4)
        self.check_letter_input(*self.locator.THIRD_4, name=N.THIRD_4)

        self.max_symbol_10_input(*self.locator.THIRD_5, name=N.THIRD_5)
        self.check_zero_value_input(*self.locator.THIRD_5, name=N.THIRD_5)
        self.check_special_symbol_input(*self.locator.THIRD_5, name=N.THIRD_5)
        self.check_letter_input(*self.locator.THIRD_5, name=N.THIRD_5)

        self.max_symbol_6_input(*self.locator.THIRD_6, name=N.THIRD_6)
        self.check_zero_value_input(*self.locator.THIRD_6, name=N.THIRD_6)
        self.check_special_symbol_input(*self.locator.THIRD_6, name=N.THIRD_6)
        self.check_letter_input(*self.locator.THIRD_6, name=N.THIRD_6)

        self.max_symbol_5_input(*self.locator.THIRD_7, name=N.THIRD_7)
        self.check_zero_value_input(*self.locator.THIRD_7, name=N.THIRD_7)
        self.check_special_symbol_input(*self.locator.THIRD_7, name=N.THIRD_7)
        self.check_letter_input(*self.locator.THIRD_7, name=N.THIRD_7)

        self.max_symbol_10_input(*self.locator.THIRD_8, name=N.THIRD_8)
        self.check_zero_value_input(*self.locator.THIRD_8, name=N.THIRD_8)
        self.check_special_symbol_input(*self.locator.THIRD_8, name=N.THIRD_8)
        self.check_letter_input(*self.locator.THIRD_8, name=N.THIRD_8)

        self.max_symbol_6_input(*self.locator.THIRD_9, name=N.THIRD_9)
        self.check_zero_value_input(*self.locator.THIRD_9, name=N.THIRD_9)
        self.check_special_symbol_input(*self.locator.THIRD_9, name=N.THIRD_9)
        self.check_letter_input(*self.locator.THIRD_9, name=N.THIRD_9)
        self.find_element(*self.locator.CHAPTER_4).click()
        self.scroll('600')
        self.max_symbol_5_input(*self.locator.FOURTH_1, name=N.FOURTH_1)
        self.check_zero_value_input(*self.locator.FOURTH_1, name=N.FOURTH_1)
        self.check_special_symbol_input(*self.locator.FOURTH_1, name=N.FOURTH_1)
        self.check_letter_input(*self.locator.FOURTH_1, name=N.FOURTH_1)

        self.max_symbol_10_input(*self.locator.FOURTH_2, name=N.FOURTH_2)
        self.check_zero_value_input(*self.locator.FOURTH_2, name=N.FOURTH_2)
        self.check_special_symbol_input(*self.locator.FOURTH_2, name=N.FOURTH_2)
        self.check_letter_input(*self.locator.FOURTH_2, name=N.FOURTH_2)

        self.max_symbol_6_input(*self.locator.FOURTH_3, name=N.FOURTH_3)
        self.check_zero_value_input(*self.locator.FOURTH_3, name=N.FOURTH_3)
        self.check_special_symbol_input(*self.locator.FOURTH_3, name=N.FOURTH_3)
        self.check_letter_input(*self.locator.FOURTH_3, name=N.FOURTH_3)

        self.max_symbol_5_input(*self.locator.FOURTH_4, name=N.FOURTH_4)
        self.check_zero_value_input(*self.locator.FOURTH_4, name=N.FOURTH_4)
        self.check_special_symbol_input(*self.locator.FOURTH_4, name=N.FOURTH_4)
        self.check_letter_input(*self.locator.FOURTH_4, name=N.FOURTH_4)

        self.max_symbol_10_input(*self.locator.FOURTH_5, name=N.FOURTH_5)
        self.check_zero_value_input(*self.locator.FOURTH_5, name=N.FOURTH_5)
        self.check_special_symbol_input(*self.locator.FOURTH_5, name=N.FOURTH_5)
        self.check_letter_input(*self.locator.FOURTH_5, name=N.FOURTH_5)

        self.max_symbol_6_input(*self.locator.FOURTH_6, name=N.FOURTH_6)
        self.check_zero_value_input(*self.locator.FOURTH_6, name=N.FOURTH_6)
        self.check_special_symbol_input(*self.locator.FOURTH_6, name=N.FOURTH_6)
        self.check_letter_input(*self.locator.FOURTH_6, name=N.FOURTH_6)
        self.find_element(*self.locator.CHAPTER_5).click()
        self.scroll('500')
        self.max_symbol_5_input(*self.locator.FIFTH_1, name=N.FIFTH_1)
        self.check_zero_value_input(*self.locator.FIFTH_1, name=N.FIFTH_1)
        self.check_special_symbol_input(*self.locator.FIFTH_1, name=N.FIFTH_1)
        self.check_letter_input(*self.locator.FIFTH_1, name=N.FIFTH_1)

        self.max_symbol_10_input(*self.locator.FIFTH_2, name=N.FIFTH_2)
        self.check_zero_value_input(*self.locator.FIFTH_2, name=N.FIFTH_2)
        self.check_special_symbol_input(*self.locator.FIFTH_2, name=N.FIFTH_2)
        self.check_letter_input(*self.locator.FIFTH_2, name=N.FIFTH_2)

        self.max_symbol_6_input(*self.locator.FIFTH_3, name=N.FIFTH_3)
        self.check_zero_value_input(*self.locator.FIFTH_3, name=N.FIFTH_3)
        self.check_special_symbol_input(*self.locator.FIFTH_3, name=N.FIFTH_3)
        self.check_letter_input(*self.locator.FIFTH_3, name=N.FIFTH_3)

        self.max_symbol_5_input(*self.locator.FIFTH_4, name=N.FIFTH_4)
        self.check_zero_value_input(*self.locator.FIFTH_4, name=N.FIFTH_4)
        self.check_special_symbol_input(*self.locator.FIFTH_4, name=N.FIFTH_4)
        self.check_letter_input(*self.locator.FIFTH_4, name=N.FIFTH_4)

        self.max_symbol_10_input(*self.locator.FIFTH_5, name=N.FIFTH_5)
        self.check_zero_value_input(*self.locator.FIFTH_5, name=N.FIFTH_5)
        self.check_special_symbol_input(*self.locator.FIFTH_5, name=N.FIFTH_5)
        self.check_letter_input(*self.locator.FIFTH_5, name=N.FIFTH_5)

        self.max_symbol_6_input(*self.locator.FIFTH_6, name=N.FIFTH_6)
        self.check_zero_value_input(*self.locator.FIFTH_6, name=N.FIFTH_6)
        self.check_special_symbol_input(*self.locator.FIFTH_6, name=N.FIFTH_6)
        self.check_letter_input(*self.locator.FIFTH_6, name=N.FIFTH_6)

        self.max_symbol_5_input(*self.locator.FIFTH_7, name=N.FIFTH_7)
        self.check_zero_value_input(*self.locator.FIFTH_7, name=N.FIFTH_7)
        self.check_special_symbol_input(*self.locator.FIFTH_7, name=N.FIFTH_7)
        self.check_letter_input(*self.locator.FIFTH_7, name=N.FIFTH_7)

        self.max_symbol_10_input(*self.locator.FIFTH_8, name=N.FIFTH_8)
        self.check_zero_value_input(*self.locator.FIFTH_8, name=N.FIFTH_8)
        self.check_special_symbol_input(*self.locator.FIFTH_8, name=N.FIFTH_8)
        self.check_letter_input(*self.locator.FIFTH_8, name=N.FIFTH_8)

        self.max_symbol_6_input(*self.locator.FIFTH_9, name=N.FIFTH_9)
        self.check_zero_value_input(*self.locator.FIFTH_9, name=N.FIFTH_9)
        self.check_special_symbol_input(*self.locator.FIFTH_9, name=N.FIFTH_9)
        self.check_letter_input(*self.locator.FIFTH_9, name=N.FIFTH_9)

        self.max_symbol_5_input(*self.locator.FIFTH_10, name=N.FIFTH_10)
        self.check_zero_value_input(*self.locator.FIFTH_10, name=N.FIFTH_10)
        self.check_special_symbol_input(*self.locator.FIFTH_10, name=N.FIFTH_10)
        self.check_letter_input(*self.locator.FIFTH_10, name=N.FIFTH_10)

        self.max_symbol_10_input(*self.locator.FIFTH_11, name=N.FIFTH_11)
        self.check_zero_value_input(*self.locator.FIFTH_11, name=N.FIFTH_11)
        self.check_special_symbol_input(*self.locator.FIFTH_11, name=N.FIFTH_11)
        self.check_letter_input(*self.locator.FIFTH_11, name=N.FIFTH_11)

        self.max_symbol_6_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.check_zero_value_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.check_special_symbol_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.check_letter_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.find_element(*self.locator.CHAPTER_6).click()
        self.scroll('700')
        self.max_symbol_5_input(*self.locator.FIFTH_10, name=N.FIFTH_10)
        self.check_zero_value_input(*self.locator.FIFTH_10, name=N.FIFTH_10)
        self.check_special_symbol_input(*self.locator.FIFTH_10, name=N.FIFTH_10)
        self.check_letter_input(*self.locator.FIFTH_10, name=N.FIFTH_10)

        self.max_symbol_10_input(*self.locator.FIFTH_11, name=N.FIFTH_11)
        self.check_zero_value_input(*self.locator.FIFTH_11, name=N.FIFTH_11)
        self.check_special_symbol_input(*self.locator.FIFTH_11, name=N.FIFTH_11)
        self.check_letter_input(*self.locator.FIFTH_11, name=N.FIFTH_11)

        self.max_symbol_6_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.check_zero_value_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.check_special_symbol_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.check_letter_input(*self.locator.FIFTH_12, name=N.FIFTH_12)
        self.find_element(*self.locator.CHAPTER_6).click()
        self.scroll('700')
        self.max_symbol_5_input(*self.locator.SIXTH_1, name=N.SIXTH_1)
        self.check_zero_value_input(*self.locator.SIXTH_1, name=N.SIXTH_1)
        self.check_special_symbol_input(*self.locator.SIXTH_1, name=N.SIXTH_1)
        self.check_letter_input(*self.locator.SIXTH_1, name=N.SIXTH_1)

        self.max_symbol_10_input(*self.locator.SIXTH_2, name=N.SIXTH_2)
        self.check_zero_value_input(*self.locator.SIXTH_2, name=N.SIXTH_2)
        self.check_special_symbol_input(*self.locator.SIXTH_2, name=N.SIXTH_2)
        self.check_letter_input(*self.locator.SIXTH_2, name=N.SIXTH_2)

        self.max_symbol_6_input(*self.locator.SIXTH_3, name=N.SIXTH_3)
        self.check_zero_value_input(*self.locator.SIXTH_3, name=N.SIXTH_3)
        self.check_special_symbol_input(*self.locator.SIXTH_3, name=N.SIXTH_3)
        self.check_letter_input(*self.locator.SIXTH_3, name=N.SIXTH_3)

        self.max_symbol_5_input(*self.locator.SIXTH_4, name=N.SIXTH_4)
        self.check_zero_value_input(*self.locator.SIXTH_4, name=N.SIXTH_4)
        self.check_special_symbol_input(*self.locator.SIXTH_4, name=N.SIXTH_4)
        self.check_letter_input(*self.locator.SIXTH_4, name=N.SIXTH_4)

        self.max_symbol_10_input(*self.locator.SIXTH_5, name=N.SIXTH_5)
        self.check_zero_value_input(*self.locator.SIXTH_5, name=N.SIXTH_5)
        self.check_special_symbol_input(*self.locator.SIXTH_5, name=N.SIXTH_5)
        self.check_letter_input(*self.locator.SIXTH_5, name=N.SIXTH_5)

        self.max_symbol_6_input(*self.locator.SIXTH_6, name=N.SIXTH_6)
        self.check_zero_value_input(*self.locator.SIXTH_6, name=N.SIXTH_6)
        self.check_special_symbol_input(*self.locator.SIXTH_6, name=N.SIXTH_6)
        self.check_letter_input(*self.locator.SIXTH_6, name=N.SIXTH_6)

        self.max_symbol_5_input(*self.locator.SIXTH_7, name=N.SIXTH_7)
        self.check_zero_value_input(*self.locator.SIXTH_7, name=N.SIXTH_7)
        self.check_special_symbol_input(*self.locator.SIXTH_7, name=N.SIXTH_7)
        self.check_letter_input(*self.locator.SIXTH_7, name=N.SIXTH_7)

        self.max_symbol_10_input(*self.locator.SIXTH_8, name=N.SIXTH_8)
        self.check_zero_value_input(*self.locator.SIXTH_8, name=N.SIXTH_8)
        self.check_special_symbol_input(*self.locator.SIXTH_8, name=N.SIXTH_8)
        self.check_letter_input(*self.locator.SIXTH_8, name=N.SIXTH_8)

        self.max_symbol_6_input(*self.locator.SIXTH_9, name=N.SIXTH_9)
        self.check_zero_value_input(*self.locator.SIXTH_9, name=N.SIXTH_9)
        self.check_special_symbol_input(*self.locator.SIXTH_9, name=N.SIXTH_9)
        self.check_letter_input(*self.locator.SIXTH_9, name=N.SIXTH_9)

        self.max_symbol_5_input(*self.locator.SIXTH_10, name=N.SIXTH_10)
        self.check_zero_value_input(*self.locator.SIXTH_10, name=N.SIXTH_10)
        self.check_special_symbol_input(*self.locator.SIXTH_10, name=N.SIXTH_10)
        self.check_letter_input(*self.locator.SIXTH_10, name=N.SIXTH_10)

        self.max_symbol_10_input(*self.locator.SIXTH_11, name=N.SIXTH_11)
        self.check_zero_value_input(*self.locator.SIXTH_11, name=N.SIXTH_11)
        self.check_special_symbol_input(*self.locator.SIXTH_11, name=N.SIXTH_11)
        self.check_letter_input(*self.locator.SIXTH_11, name=N.SIXTH_11)

        self.max_symbol_6_input(*self.locator.SIXTH_12, name=N.SIXTH_12)
        self.check_zero_value_input(*self.locator.SIXTH_12, name=N.SIXTH_12)
        self.check_special_symbol_input(*self.locator.SIXTH_12, name=N.SIXTH_12)
        self.check_letter_input(*self.locator.SIXTH_12, name=N.SIXTH_12)

        self.max_symbol_6_input(*self.locator.SIXTH_13, name=N.SIXTH_13)
        self.check_zero_value_input(*self.locator.SIXTH_13, name=N.SIXTH_13)
        self.check_special_symbol_input(*self.locator.SIXTH_13, name=N.SIXTH_13)
        self.check_letter_input(*self.locator.SIXTH_13, name=N.SIXTH_13)

        self.max_symbol_6_input(*self.locator.SIXTH_14, name=N.SIXTH_14)
        self.check_zero_value_input(*self.locator.SIXTH_14, name=N.SIXTH_14)
        self.check_special_symbol_input(*self.locator.SIXTH_14, name=N.SIXTH_14)
        self.check_letter_input(*self.locator.SIXTH_14, name=N.SIXTH_14)

        self.max_symbol_5_input(*self.locator.SIXTH_15, name=N.SIXTH_15)
        self.check_zero_value_input(*self.locator.SIXTH_15, name=N.SIXTH_15)
        self.check_special_symbol_input(*self.locator.SIXTH_15, name=N.SIXTH_15)
        self.check_letter_input(*self.locator.SIXTH_15, name=N.SIXTH_15)

        self.max_symbol_10_input(*self.locator.SIXTH_16, name=N.SIXTH_16)
        self.check_zero_value_input(*self.locator.SIXTH_16, name=N.SIXTH_16)
        self.check_special_symbol_input(*self.locator.SIXTH_16, name=N.SIXTH_16)
        self.check_letter_input(*self.locator.SIXTH_16, name=N.SIXTH_16)

        self.max_symbol_6_input(*self.locator.SIXTH_17, name=N.SIXTH_17)
        self.check_zero_value_input(*self.locator.SIXTH_17, name=N.SIXTH_17)
        self.check_special_symbol_input(*self.locator.SIXTH_17, name=N.SIXTH_17)
        self.check_letter_input(*self.locator.SIXTH_17, name=N.SIXTH_17)

        self.max_symbol_6_input(*self.locator.SIXTH_18, name=N.SIXTH_18)
        self.check_zero_value_input(*self.locator.SIXTH_18, name=N.SIXTH_18)
        self.check_special_symbol_input(*self.locator.SIXTH_18, name=N.SIXTH_18)
        self.check_letter_input(*self.locator.SIXTH_18, name=N.SIXTH_18)
        self.scroll('600')
        self.max_symbol_5_input(*self.locator.SIXTH_19, name=N.SIXTH_19)
        self.check_zero_value_input(*self.locator.SIXTH_19, name=N.SIXTH_19)
        self.check_special_symbol_input(*self.locator.SIXTH_19, name=N.SIXTH_19)
        self.check_letter_input(*self.locator.SIXTH_19, name=N.SIXTH_19)

        self.max_symbol_10_input(*self.locator.SIXTH_20, name=N.SIXTH_20)
        self.check_zero_value_input(*self.locator.SIXTH_20, name=N.SIXTH_20)
        self.check_special_symbol_input(*self.locator.SIXTH_20, name=N.SIXTH_20)
        self.check_letter_input(*self.locator.SIXTH_20, name=N.SIXTH_20)

        self.max_symbol_6_input(*self.locator.SIXTH_21, name=N.SIXTH_21)
        self.check_zero_value_input(*self.locator.SIXTH_21, name=N.SIXTH_21)
        self.check_special_symbol_input(*self.locator.SIXTH_21, name=N.SIXTH_21)
        self.check_letter_input(*self.locator.SIXTH_21, name=N.SIXTH_21)

        self.max_symbol_6_input(*self.locator.SIXTH_22, name=N.SIXTH_22)
        self.check_zero_value_input(*self.locator.SIXTH_22, name=N.SIXTH_22)
        self.check_special_symbol_input(*self.locator.SIXTH_22, name=N.SIXTH_22)
        self.check_letter_input(*self.locator.SIXTH_22, name=N.SIXTH_22)

        self.max_symbol_5_input(*self.locator.SIXTH_23, name=N.SIXTH_23)
        self.check_zero_value_input(*self.locator.SIXTH_23, name=N.SIXTH_23)
        self.check_special_symbol_input(*self.locator.SIXTH_23, name=N.SIXTH_23)
        self.check_letter_input(*self.locator.SIXTH_23, name=N.SIXTH_23)

        self.max_symbol_10_input(*self.locator.SIXTH_24, name=N.SIXTH_24)
        self.check_zero_value_input(*self.locator.SIXTH_24, name=N.SIXTH_24)
        self.check_special_symbol_input(*self.locator.SIXTH_24, name=N.SIXTH_24)
        self.check_letter_input(*self.locator.SIXTH_24, name=N.SIXTH_24)

        self.max_symbol_6_input(*self.locator.SIXTH_25, name=N.SIXTH_25)
        self.check_zero_value_input(*self.locator.SIXTH_25, name=N.SIXTH_25)
        self.check_special_symbol_input(*self.locator.SIXTH_25, name=N.SIXTH_25)
        self.check_letter_input(*self.locator.SIXTH_25, name=N.SIXTH_25)

        self.max_symbol_6_input(*self.locator.SIXTH_26, name=N.SIXTH_26)
        self.check_zero_value_input(*self.locator.SIXTH_26, name=N.SIXTH_26)
        self.check_special_symbol_input(*self.locator.SIXTH_26, name=N.SIXTH_26)
        self.check_letter_input(*self.locator.SIXTH_26, name=N.SIXTH_26)
        self.find_element(*self.locator.CHAPTER_7).click()
        self.scroll('600')

        self.max_symbol_5_input(*self.locator.SEVENTH_1, name=N.SEVENTH_1)
        self.check_zero_value_input(*self.locator.SEVENTH_1, name=N.SEVENTH_1)
        self.check_special_symbol_input(*self.locator.SEVENTH_1, name=N.SEVENTH_1)
        self.check_letter_input(*self.locator.SEVENTH_1, name=N.SEVENTH_1)

        self.max_symbol_10_input(*self.locator.SEVENTH_2, name=N.SEVENTH_2)
        self.check_zero_value_input(*self.locator.SEVENTH_2, name=N.SEVENTH_2)
        self.check_special_symbol_input(*self.locator.SEVENTH_2, name=N.SEVENTH_2)
        self.check_letter_input(*self.locator.SEVENTH_2, name=N.SEVENTH_2)

        self.max_symbol_6_input(*self.locator.SEVENTH_3, name=N.SEVENTH_3)
        self.check_zero_value_input(*self.locator.SEVENTH_3, name=N.SEVENTH_3)
        self.check_special_symbol_input(*self.locator.SEVENTH_3, name=N.SEVENTH_3)
        self.check_letter_input(*self.locator.SEVENTH_3, name=N.SEVENTH_3)

        self.max_symbol_6_input(*self.locator.SEVENTH_4, name=N.SEVENTH_4)
        self.check_zero_value_input(*self.locator.SEVENTH_4, name=N.SEVENTH_4)
        self.check_special_symbol_input(*self.locator.SEVENTH_4, name=N.SEVENTH_4)
        self.check_letter_input(*self.locator.SEVENTH_4, name=N.SEVENTH_4)

        self.max_symbol_5_input(*self.locator.SEVENTH_5, name=N.SEVENTH_5)
        self.check_zero_value_input(*self.locator.SEVENTH_5, name=N.SEVENTH_5)
        self.check_special_symbol_input(*self.locator.SEVENTH_5, name=N.SEVENTH_5)
        self.check_letter_input(*self.locator.SEVENTH_5, name=N.SEVENTH_5)

        self.max_symbol_10_input(*self.locator.SEVENTH_6, name=N.SEVENTH_6)
        self.check_zero_value_input(*self.locator.SEVENTH_6, name=N.SEVENTH_6)
        self.check_special_symbol_input(*self.locator.SEVENTH_6, name=N.SEVENTH_6)
        self.check_letter_input(*self.locator.SEVENTH_6, name=N.SEVENTH_6)

        self.max_symbol_6_input(*self.locator.SEVENTH_7, name=N.SEVENTH_7)
        self.check_zero_value_input(*self.locator.SEVENTH_7, name=N.SEVENTH_7)
        self.check_special_symbol_input(*self.locator.SEVENTH_7, name=N.SEVENTH_7)
        self.check_letter_input(*self.locator.SEVENTH_7, name=N.SEVENTH_7)

        self.max_symbol_6_input(*self.locator.SEVENTH_8, name=N.SEVENTH_8)
        self.check_zero_value_input(*self.locator.SEVENTH_8, name=N.SEVENTH_8)
        self.check_special_symbol_input(*self.locator.SEVENTH_8, name=N.SEVENTH_8)
        self.check_letter_input(*self.locator.SEVENTH_8, name=N.SEVENTH_8)

        self.max_symbol_5_input(*self.locator.SEVENTH_9, name=N.SEVENTH_9)
        self.check_zero_value_input(*self.locator.SEVENTH_9, name=N.SEVENTH_9)
        self.check_special_symbol_input(*self.locator.SEVENTH_9, name=N.SEVENTH_9)
        self.check_letter_input(*self.locator.SEVENTH_9, name=N.SEVENTH_9)

        self.max_symbol_10_input(*self.locator.SEVENTH_10, name=N.SEVENTH_10)
        self.check_zero_value_input(*self.locator.SEVENTH_10, name=N.SEVENTH_10)
        self.check_special_symbol_input(*self.locator.SEVENTH_10, name=N.SEVENTH_10)
        self.check_letter_input(*self.locator.SEVENTH_10, name=N.SEVENTH_10)

        self.max_symbol_6_input(*self.locator.SEVENTH_11, name=N.SEVENTH_11)
        self.check_zero_value_input(*self.locator.SEVENTH_11, name=N.SEVENTH_11)
        self.check_special_symbol_input(*self.locator.SEVENTH_11, name=N.SEVENTH_11)
        self.check_letter_input(*self.locator.SEVENTH_11, name=N.SEVENTH_11)

        self.max_symbol_6_input(*self.locator.SEVENTH_12, name=N.SEVENTH_12)
        self.check_zero_value_input(*self.locator.SEVENTH_12, name=N.SEVENTH_12)
        self.check_special_symbol_input(*self.locator.SEVENTH_12, name=N.SEVENTH_12)
        self.check_letter_input(*self.locator.SEVENTH_12, name=N.SEVENTH_12)

        self.max_symbol_5_input(*self.locator.SEVENTH_13, name=N.SEVENTH_13)
        self.check_zero_value_input(*self.locator.SEVENTH_13, name=N.SEVENTH_13)
        self.check_special_symbol_input(*self.locator.SEVENTH_13, name=N.SEVENTH_13)
        self.check_letter_input(*self.locator.SEVENTH_13, name=N.SEVENTH_13)

        self.max_symbol_10_input(*self.locator.SEVENTH_14, name=N.SEVENTH_14)
        self.check_zero_value_input(*self.locator.SEVENTH_14, name=N.SEVENTH_14)
        self.check_special_symbol_input(*self.locator.SEVENTH_14, name=N.SEVENTH_14)
        self.check_letter_input(*self.locator.SEVENTH_14, name=N.SEVENTH_14)

        self.max_symbol_6_input(*self.locator.SEVENTH_15, name=N.SEVENTH_15)
        self.check_zero_value_input(*self.locator.SEVENTH_15, name=N.SEVENTH_15)
        self.check_special_symbol_input(*self.locator.SEVENTH_15, name=N.SEVENTH_15)
        self.check_letter_input(*self.locator.SEVENTH_15, name=N.SEVENTH_15)

        self.max_symbol_6_input(*self.locator.SEVENTH_16, name=N.SEVENTH_16)
        self.check_zero_value_input(*self.locator.SEVENTH_16, name=N.SEVENTH_16)
        self.check_special_symbol_input(*self.locator.SEVENTH_16, name=N.SEVENTH_16)
        self.check_letter_input(*self.locator.SEVENTH_16, name=N.SEVENTH_16)

        self.max_symbol_5_input(*self.locator.SEVENTH_17, name=N.SEVENTH_17)
        self.check_zero_value_input(*self.locator.SEVENTH_17, name=N.SEVENTH_17)
        self.check_special_symbol_input(*self.locator.SEVENTH_17, name=N.SEVENTH_17)
        self.check_letter_input(*self.locator.SEVENTH_17, name=N.SEVENTH_17)

        self.max_symbol_10_input(*self.locator.SEVENTH_18, name=N.SEVENTH_18)
        self.check_zero_value_input(*self.locator.SEVENTH_18, name=N.SEVENTH_18)
        self.check_special_symbol_input(*self.locator.SEVENTH_18, name=N.SEVENTH_18)
        self.check_letter_input(*self.locator.SEVENTH_18, name=N.SEVENTH_18)

        self.max_symbol_6_input(*self.locator.SEVENTH_19, name=N.SEVENTH_19)
        self.check_zero_value_input(*self.locator.SEVENTH_19, name=N.SEVENTH_19)
        self.check_special_symbol_input(*self.locator.SEVENTH_19, name=N.SEVENTH_19)
        self.check_letter_input(*self.locator.SEVENTH_19, name=N.SEVENTH_19)

        self.max_symbol_6_input(*self.locator.SEVENTH_20, name=N.SEVENTH_20)
        self.check_zero_value_input(*self.locator.SEVENTH_20, name=N.SEVENTH_20)
        self.check_special_symbol_input(*self.locator.SEVENTH_20, name=N.SEVENTH_20)
        self.check_letter_input(*self.locator.SEVENTH_20, name=N.SEVENTH_20)
        self.scroll('600')
        self.find_element(*self.locator.CHAPTER_8).click()

        self.max_symbol_5_input(*self.locator.EIGHT_1, name=N.EIGHT_1)
        self.check_zero_value_input(*self.locator.EIGHT_1, name=N.EIGHT_1)
        self.check_special_symbol_input(*self.locator.EIGHT_1, name=N.EIGHT_1)
        self.check_letter_input(*self.locator.EIGHT_1, name=N.EIGHT_1)

        self.max_symbol_10_input(*self.locator.EIGHT_2, name=N.EIGHT_2)
        self.check_zero_value_input(*self.locator.EIGHT_2, name=N.EIGHT_2)
        self.check_special_symbol_input(*self.locator.EIGHT_2, name=N.EIGHT_2)
        self.check_letter_input(*self.locator.EIGHT_2, name=N.EIGHT_2)

        self.max_symbol_6_input(*self.locator.EIGHT_3, name=N.EIGHT_3)
        self.check_zero_value_input(*self.locator.EIGHT_3, name=N.EIGHT_3)
        self.check_special_symbol_input(*self.locator.EIGHT_3, name=N.EIGHT_3)
        self.check_letter_input(*self.locator.EIGHT_3, name=N.EIGHT_3)

        self.max_symbol_5_input(*self.locator.EIGHT_4, name=N.EIGHT_4)
        self.check_zero_value_input(*self.locator.EIGHT_4, name=N.EIGHT_4)
        self.check_special_symbol_input(*self.locator.EIGHT_4, name=N.EIGHT_4)
        self.check_letter_input(*self.locator.EIGHT_4, name=N.EIGHT_4)

        self.max_symbol_5_input(*self.locator.EIGHT_5, name=N.EIGHT_5)
        self.check_zero_value_input(*self.locator.EIGHT_5, name=N.EIGHT_5)
        self.check_special_symbol_input(*self.locator.EIGHT_5, name=N.EIGHT_5)
        self.check_letter_input(*self.locator.EIGHT_5, name=N.EIGHT_5)

        self.max_symbol_10_input(*self.locator.EIGHT_6, name=N.EIGHT_6)
        self.check_zero_value_input(*self.locator.EIGHT_6, name=N.EIGHT_6)
        self.check_special_symbol_input(*self.locator.EIGHT_6, name=N.EIGHT_6)
        self.check_letter_input(*self.locator.EIGHT_6, name=N.EIGHT_6)

        self.max_symbol_6_input(*self.locator.EIGHT_7, name=N.EIGHT_7)
        self.check_zero_value_input(*self.locator.EIGHT_7, name=N.EIGHT_7)
        self.check_special_symbol_input(*self.locator.EIGHT_7, name=N.EIGHT_7)
        self.check_letter_input(*self.locator.EIGHT_7, name=N.EIGHT_7)

        self.max_symbol_6_input(*self.locator.EIGHT_8, name=N.EIGHT_8)
        self.check_zero_value_input(*self.locator.EIGHT_8, name=N.EIGHT_8)
        self.check_special_symbol_input(*self.locator.EIGHT_8, name=N.EIGHT_8)
        self.check_letter_input(*self.locator.EIGHT_8, name=N.EIGHT_8)

        self.max_symbol_5_input(*self.locator.EIGHT_9, name=N.EIGHT_9)
        self.check_zero_value_input(*self.locator.EIGHT_9, name=N.EIGHT_9)
        self.check_special_symbol_input(*self.locator.EIGHT_9, name=N.EIGHT_9)
        self.check_letter_input(*self.locator.EIGHT_9, name=N.EIGHT_9)

        self.max_symbol_10_input(*self.locator.EIGHT_10, name=N.EIGHT_10)
        self.check_zero_value_input(*self.locator.EIGHT_10, name=N.EIGHT_10)
        self.check_special_symbol_input(*self.locator.EIGHT_10, name=N.EIGHT_10)
        self.check_letter_input(*self.locator.EIGHT_10, name=N.EIGHT_10)

        self.max_symbol_6_input(*self.locator.EIGHT_11, name=N.EIGHT_11)
        self.check_zero_value_input(*self.locator.EIGHT_11, name=N.EIGHT_11)
        self.check_special_symbol_input(*self.locator.EIGHT_11, name=N.EIGHT_11)
        self.check_letter_input(*self.locator.EIGHT_11, name=N.EIGHT_11)

        self.max_symbol_6_input(*self.locator.EIGHT_12, name=N.EIGHT_12)
        self.check_zero_value_input(*self.locator.EIGHT_12, name=N.EIGHT_12)
        self.check_special_symbol_input(*self.locator.EIGHT_12, name=N.EIGHT_12)
        self.check_letter_input(*self.locator.EIGHT_12, name=N.EIGHT_12)
        self.scroll('600')
        self.find_element(*self.locator.CHAPTER_9).click()

        self.max_symbol_5_input(*self.locator.NINTH_1, name=N.NINTH_1)
        self.check_zero_value_input(*self.locator.NINTH_1, name=N.NINTH_1)
        self.check_special_symbol_input(*self.locator.NINTH_1, name=N.NINTH_1)
        self.check_letter_input(*self.locator.NINTH_1, name=N.NINTH_1)

        self.max_symbol_10_input(*self.locator.NINTH_2, name=N.NINTH_2)
        self.check_zero_value_input(*self.locator.NINTH_2, name=N.NINTH_2)
        self.check_special_symbol_input(*self.locator.NINTH_2, name=N.NINTH_2)
        self.check_letter_input(*self.locator.NINTH_2, name=N.NINTH_2)

        self.max_symbol_6_input(*self.locator.NINTH_3, name=N.NINTH_3)
        self.check_zero_value_input(*self.locator.NINTH_3, name=N.NINTH_3)
        self.check_special_symbol_input(*self.locator.NINTH_3, name=N.NINTH_3)
        self.check_letter_input(*self.locator.NINTH_3, name=N.NINTH_3)

        self.max_symbol_6_input(*self.locator.NINTH_4, name=N.NINTH_4)
        self.check_zero_value_input(*self.locator.NINTH_4, name=N.NINTH_4)
        self.check_special_symbol_input(*self.locator.NINTH_4, name=N.NINTH_4)
        self.check_letter_input(*self.locator.NINTH_4, name=N.NINTH_4)

        self.max_symbol_5_input(*self.locator.NINTH_5, name=N.NINTH_5)
        self.check_zero_value_input(*self.locator.NINTH_5, name=N.NINTH_5)
        self.check_special_symbol_input(*self.locator.NINTH_5, name=N.NINTH_5)
        self.check_letter_input(*self.locator.NINTH_5, name=N.NINTH_5)

        self.max_symbol_10_input(*self.locator.NINTH_6, name=N.NINTH_6)
        self.check_zero_value_input(*self.locator.NINTH_6, name=N.NINTH_6)
        self.check_special_symbol_input(*self.locator.NINTH_6, name=N.NINTH_6)
        self.check_letter_input(*self.locator.NINTH_6, name=N.NINTH_6)

        self.max_symbol_6_input(*self.locator.NINTH_7, name=N.NINTH_7)
        self.check_zero_value_input(*self.locator.NINTH_7, name=N.NINTH_7)
        self.check_special_symbol_input(*self.locator.NINTH_7, name=N.NINTH_7)
        self.check_letter_input(*self.locator.NINTH_7, name=N.NINTH_7)

        self.max_symbol_6_input(*self.locator.NINTH_8, name=N.NINTH_8)
        self.check_zero_value_input(*self.locator.NINTH_8, name=N.NINTH_8)
        self.check_special_symbol_input(*self.locator.NINTH_8, name=N.NINTH_8)
        self.check_letter_input(*self.locator.NINTH_8, name=N.NINTH_8)

        self.max_symbol_5_input(*self.locator.NINTH_9, name=N.NINTH_9)
        self.check_zero_value_input(*self.locator.NINTH_9, name=N.NINTH_9)
        self.check_special_symbol_input(*self.locator.NINTH_9, name=N.NINTH_9)
        self.check_letter_input(*self.locator.NINTH_9, name=N.NINTH_9)

        self.max_symbol_10_input(*self.locator.NINTH_10, name=N.NINTH_10)
        self.check_zero_value_input(*self.locator.NINTH_10, name=N.NINTH_10)
        self.check_special_symbol_input(*self.locator.NINTH_10, name=N.NINTH_10)
        self.check_letter_input(*self.locator.NINTH_10, name=N.NINTH_10)

        self.max_symbol_6_input(*self.locator.NINTH_11, name=N.NINTH_11)
        self.check_zero_value_input(*self.locator.NINTH_11, name=N.NINTH_11)
        self.check_special_symbol_input(*self.locator.NINTH_11, name=N.NINTH_11)
        self.check_letter_input(*self.locator.NINTH_11, name=N.NINTH_11)

        self.max_symbol_6_input(*self.locator.NINTH_12, name=N.NINTH_12)
        self.check_zero_value_input(*self.locator.NINTH_12, name=N.NINTH_12)
        self.check_special_symbol_input(*self.locator.NINTH_12, name=N.NINTH_12)
        self.check_letter_input(*self.locator.NINTH_12, name=N.NINTH_12)
        self.scroll('600')
        self.find_element(*self.locator.CHAPTER_10).click()

        self.max_symbol_5_input(*self.locator.TENTH_1, name=N.TENTH_1)
        self.check_zero_value_input(*self.locator.TENTH_1, name=N.TENTH_1)
        self.check_special_symbol_input(*self.locator.TENTH_1, name=N.TENTH_1)
        self.check_letter_input(*self.locator.TENTH_1, name=N.TENTH_1)

        self.max_symbol_10_input(*self.locator.TENTH_2, name=N.TENTH_2)
        self.check_zero_value_input(*self.locator.TENTH_2, name=N.TENTH_2)
        self.check_special_symbol_input(*self.locator.TENTH_2, name=N.TENTH_2)
        self.check_letter_input(*self.locator.TENTH_2, name=N.TENTH_2)

        self.max_symbol_6_input(*self.locator.TENTH_3, name=N.TENTH_3)
        self.check_zero_value_input(*self.locator.TENTH_3, name=N.TENTH_3)
        self.check_special_symbol_input(*self.locator.TENTH_3, name=N.TENTH_3)
        self.check_letter_input(*self.locator.TENTH_3, name=N.TENTH_3)

        self.max_symbol_6_input(*self.locator.TENTH_4, name=N.TENTH_4)
        self.check_zero_value_input(*self.locator.TENTH_4, name=N.TENTH_4)
        self.check_special_symbol_input(*self.locator.TENTH_4, name=N.TENTH_4)
        self.check_letter_input(*self.locator.TENTH_4, name=N.TENTH_4)

        self.scroll('500')
        self.max_symbol_6_input(*self.locator.SUM, name=N.SUM)
        self.check_zero_value_input(*self.locator.SUM, name=N.SUM)
        self.check_special_symbol_input(*self.locator.SUM, name=N.SUM)
        self.check_letter_input(*self.locator.SUM, name=N.SUM)
        self.find_element(*self.locator.AFTER).click()

    def app_2_validation(self):
        self.scroll('650')
        self.max_symbol_9_input(*self.locator.FIELD_APP_2, name=N.FIELD_APP_2)
        self.check_zero_value_input(*self.locator.FIELD_APP_2, name=N.FIELD_APP_2)
        self.check_special_symbol_input(*self.locator.FIELD_APP_2, name=N.FIELD_APP_2)
        self.check_letter_input(*self.locator.FIELD_APP_2, name=N.FIELD_APP_2)
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.SECOND_APP_B).send_keys('123456789012345678901234567890')
        sleep(0.3)
        assert '12345678901234567890123456789'
        self.max_symbol_9_input(*self.locator.SECOND_APP_D, name=N.SECOND_APP_D)
        self.check_zero_value_input(*self.locator.SECOND_APP_D, name=N.SECOND_APP_D)
        self.check_special_symbol_input(*self.locator.SECOND_APP_D, name=N.SECOND_APP_D)
        self.check_letter_input(*self.locator.SECOND_APP_D, name=N.SECOND_APP_D)

        self.max_symbol_2_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)
        self.check_zero_value_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)
        self.check_special_symbol_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)
        self.check_letter_input(*self.locator.SECOND_APP_F, name=N.SECOND_APP_F)

        self.max_symbol_3_input(*self.locator.SECOND_APP_G, name=N.SECOND_APP_G)
        self.check_zero_value_input(*self.locator.SECOND_APP_G, name=N.SECOND_APP_G)
        self.check_special_symbol_input(*self.locator.SECOND_APP_G, name=N.SECOND_APP_G)
        self.check_letter_input(*self.locator.SECOND_APP_G, name=N.SECOND_APP_G)

        self.max_symbol_1_input(*self.locator.SECOND_APP_H, name=N.SECOND_APP_H)
        self.check_zero_value_input(*self.locator.SECOND_APP_H, name=N.SECOND_APP_H)
        self.check_special_symbol_input(*self.locator.SECOND_APP_H, name=N.SECOND_APP_H)
        self.check_letter_input(*self.locator.SECOND_APP_H, name=N.SECOND_APP_H)

        self.max_symbol_1_input(*self.locator.SECOND_APP_I, name=N.SECOND_APP_I)
        self.check_zero_value_input(*self.locator.SECOND_APP_I, name=N.SECOND_APP_I)
        self.check_special_symbol_input(*self.locator.SECOND_APP_I, name=N.SECOND_APP_I)
        self.check_letter_input(*self.locator.SECOND_APP_I, name=N.SECOND_APP_I)

        element = self.browser.find_element_by_xpath('//*[text()="Далее"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)

        self.max_symbol_3_input(*self.locator.SECOND_APP_J, name=N.SECOND_APP_J)
        self.check_zero_value_input(*self.locator.SECOND_APP_J, name=N.SECOND_APP_J)
        self.check_special_symbol_input(*self.locator.SECOND_APP_J, name=N.SECOND_APP_J)
        self.check_letter_input(*self.locator.SECOND_APP_J, name=N.SECOND_APP_J)

        self.max_symbol_4_input(*self.locator.SECOND_APP_K, name=N.SECOND_APP_K)
        self.check_zero_value_input(*self.locator.SECOND_APP_K, name=N.SECOND_APP_K)
        self.check_special_symbol_input(*self.locator.SECOND_APP_K, name=N.SECOND_APP_K)
        self.check_letter_input(*self.locator.SECOND_APP_K, name=N.SECOND_APP_K)

        self.max_symbol_2_input(*self.locator.SECOND_APP_L, name=N.SECOND_APP_L)
        self.check_zero_value_input(*self.locator.SECOND_APP_L, name=N.SECOND_APP_L)
        self.check_special_symbol_input(*self.locator.SECOND_APP_L, name=N.SECOND_APP_L)
        self.check_letter_input(*self.locator.SECOND_APP_L, name=N.SECOND_APP_L)

        self.max_symbol_12_input(*self.locator.SECOND_APP_M, name=N.SECOND_APP_M)
        self.check_zero_value_input(*self.locator.SECOND_APP_M, name=N.SECOND_APP_M)
        self.check_special_symbol_input(*self.locator.SECOND_APP_M, name=N.SECOND_APP_M)
        self.check_letter_input(*self.locator.SECOND_APP_M, name=N.SECOND_APP_M)
        self.find_element(*self.locator.CANCEL_ADD_STR).click()
        self.find_element(*self.locator.AFTER).click()

    def app_3_validation(self):
        self.scroll('500')
        self.max_symbol_12_input(*self.locator.FIELD_APP_3, name=N.FIELD_APP_3)
        self.check_zero_value_input(*self.locator.FIELD_APP_3, name=N.FIELD_APP_3)
        self.check_special_symbol_input(*self.locator.FIELD_APP_3, name=N.FIELD_APP_3)
        self.check_letter_input(*self.locator.FIELD_APP_3, name=N.FIELD_APP_3)
        self.scroll('5000')
        self.find_element(*self.locator.ADD_STR).click()
        self.max_symbol_12_input(*self.locator.APP_3_C, name=N.APP_3_C)
        self.check_zero_value_input(*self.locator.APP_3_C, name=N.APP_3_C)
        self.check_special_symbol_input(*self.locator.APP_3_C, name=N.APP_3_C)
        self.check_letter_input(*self.locator.APP_3_C, name=N.APP_3_C)
        self.find_element(*self.locator.CANCEL_ADD_STR).click()
        self.find_element(*self.locator.AFTER).click()

    def fifth_page_validation(self):
        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_2, name=N.FIFTH_PAGE_FIELD_2)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_2, name=N.FIFTH_PAGE_FIELD_2)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_2, name=N.FIFTH_PAGE_FIELD_2)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_2, name=N.FIFTH_PAGE_FIELD_2)

        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_4, name=N.FIFTH_PAGE_FIELD_4)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_4, name=N.FIFTH_PAGE_FIELD_4)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_4, name=N.FIFTH_PAGE_FIELD_4)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_4, name=N.FIFTH_PAGE_FIELD_4)

        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_5_I, name=N.FIFTH_PAGE_FIELD_5_I)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_5_I, name=N.FIFTH_PAGE_FIELD_5_I)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_5_I, name=N.FIFTH_PAGE_FIELD_5_I)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_5_I, name=N.FIFTH_PAGE_FIELD_5_I)

        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_5_II, name=N.FIFTH_PAGE_FIELD_5_II)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_5_II, name=N.FIFTH_PAGE_FIELD_5_II)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_5_II, name=N.FIFTH_PAGE_FIELD_5_II)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_5_II, name=N.FIFTH_PAGE_FIELD_5_II)

        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_9, name=N.FIFTH_PAGE_FIELD_9)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_9, name=N.FIFTH_PAGE_FIELD_9)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_9, name=N.FIFTH_PAGE_FIELD_9)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_9, name=N.FIFTH_PAGE_FIELD_9)
        self.scroll('5000')
        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_10, name=N.FIFTH_PAGE_FIELD_10)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_10, name=N.FIFTH_PAGE_FIELD_10)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_10, name=N.FIFTH_PAGE_FIELD_10)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_10, name=N.FIFTH_PAGE_FIELD_10)

        self.max_symbol_12_input(*self.locator.FIFTH_PAGE_FIELD_11, name=N.FIFTH_PAGE_FIELD_11)
        self.check_zero_value_input(*self.locator.FIFTH_PAGE_FIELD_11, name=N.FIFTH_PAGE_FIELD_11)
        self.check_special_symbol_input(*self.locator.FIFTH_PAGE_FIELD_11, name=N.FIFTH_PAGE_FIELD_11)
        self.check_letter_input(*self.locator.FIFTH_PAGE_FIELD_11, name=N.FIFTH_PAGE_FIELD_11)
        self.find_element(*self.locator.AFTER).click()
