from browser_interaction import BasePage
from time import sleep
from locators.fno_421_locators import FNO_421_Locators
from locators.main_page_locators import MainPageLocators
from locators.fno_421_locators import FNO_421_Locators_Name as N
import allure


class FNO421MaxSymbolAnd0ValueCheck(BasePage):
    def __init__(self, browser):
        super().__init__(browser)
        self.browser = browser
        self.locator = FNO_421_Locators

        '''Ниже первая страница'''

    def second_page(self):
        self.scroll('500')
        self.max_symbol_12_input(*self.locator.LITER_1, name=N.LITER_1)
        self.check_zero_value_input(*self.locator.LITER_1, name=N.LITER_1)
        self.check_special_symbol_input(*self.locator.LITER_1, name=N.LITER_1)
        self.check_letter_input(*self.locator.LITER_1, name=N.LITER_1)

        self.max_symbol_5_input(*self.locator.EXC_RATE_1, name=N.EXC_RATE_1)
        self.check_zero_value_input(*self.locator.EXC_RATE_1, name=N.EXC_RATE_1)
        self.check_special_symbol_input(*self.locator.EXC_RATE_1, name=N.EXC_RATE_1)
        self.check_letter_input(*self.locator.EXC_RATE_1, name=N.EXC_RATE_1)

        self.max_symbol_12_input(*self.locator.LITER_2, name=N.LITER_2)
        self.check_zero_value_input(*self.locator.LITER_2, name=N.LITER_2)
        self.check_special_symbol_input(*self.locator.LITER_2, name=N.LITER_2)
        self.check_letter_input(*self.locator.LITER_2, name=N.LITER_2)

        self.max_symbol_5_input(*self.locator.EXC_RATE_2, name=N.EXC_RATE_2)
        self.check_zero_value_input(*self.locator.EXC_RATE_2, name=N.EXC_RATE_2)
        self.check_special_symbol_input(*self.locator.EXC_RATE_2, name=N.EXC_RATE_2)
        self.check_letter_input(*self.locator.EXC_RATE_2, name=N.EXC_RATE_2)
        self.scroll('370')
        self.max_symbol_12_input(*self.locator.WINE_LITER_1, name=N.WINE_LITER_1)
        self.check_zero_value_input(*self.locator.WINE_LITER_1, name=N.WINE_LITER_1)
        self.check_special_symbol_input(*self.locator.WINE_LITER_1, name=N.WINE_LITER_1)
        self.check_letter_input(*self.locator.WINE_LITER_1, name=N.WINE_LITER_1)

        self.max_symbol_5_input(*self.locator.WINE_EXC_1, name=N.WINE_EXC_1)
        self.check_zero_value_input(*self.locator.WINE_EXC_1, name=N.WINE_EXC_1)
        self.check_special_symbol_input(*self.locator.WINE_EXC_1, name=N.WINE_EXC_1)
        self.check_letter_input(*self.locator.WINE_EXC_1, name=N.WINE_EXC_1)

        self.max_symbol_12_input(*self.locator.WINE_LITER_2, name=N.WINE_LITER_2)
        self.check_zero_value_input(*self.locator.WINE_LITER_2, name=N.WINE_LITER_2)
        self.check_special_symbol_input(*self.locator.WINE_LITER_2, name=N.WINE_LITER_2)
        self.check_letter_input(*self.locator.WINE_LITER_2, name=N.WINE_LITER_2)

        self.max_symbol_5_input(*self.locator.WINE_EXC_2, name=N.WINE_EXC_2)
        self.check_zero_value_input(*self.locator.WINE_EXC_2, name=N.WINE_EXC_2)
        self.check_special_symbol_input(*self.locator.WINE_EXC_2, name=N.WINE_EXC_2)
        self.check_letter_input(*self.locator.WINE_EXC_2, name=N.WINE_EXC_2)
        self.find_element(*self.locator.AFTER).click()

    def third_page(self):
        self.scroll('1750')
        self.max_symbol_12_input(*self.locator.BUT_1, name=N.BUT_1)
        self.check_zero_value_input(*self.locator.BUT_1, name=N.BUT_1)
        self.check_special_symbol_input(*self.locator.BUT_1, name=N.BUT_1)
        self.check_letter_input(*self.locator.BUT_1, name=N.BUT_1)

        self.max_symbol_12_input(*self.locator.BUT_2, name=N.BUT_2)
        self.check_zero_value_input(*self.locator.BUT_2, name=N.BUT_2)
        self.check_special_symbol_input(*self.locator.BUT_1, name=N.BUT_2)
        self.check_letter_input(*self.locator.BUT_2, name=N.BUT_2)

        self.max_symbol_12_input(*self.locator.BUT_3, name=N.BUT_3)
        self.check_zero_value_input(*self.locator.BUT_3, name=N.BUT_3)
        self.check_special_symbol_input(*self.locator.BUT_3, name=N.BUT_3)
        self.check_letter_input(*self.locator.BUT_3, name=N.BUT_3)

        self.max_symbol_12_input(*self.locator.BUT_4, name=N.BUT_4)
        self.check_zero_value_input(*self.locator.BUT_4, name=N.BUT_4)
        self.check_special_symbol_input(*self.locator.BUT_4, name=N.BUT_4)
        self.check_letter_input(*self.locator.BUT_4, name=N.BUT_4)

        self.max_symbol_12_input(*self.locator.BUT_5, name=N.BUT_5)
        self.check_zero_value_input(*self.locator.BUT_5, name=N.BUT_5)
        self.check_special_symbol_input(*self.locator.BUT_5, name=N.BUT_5)
        self.check_letter_input(*self.locator.BUT_5, name=N.BUT_5)

        self.max_symbol_12_input(*self.locator.BUT_6, name=N.BUT_6)
        self.check_zero_value_input(*self.locator.BUT_6, name=N.BUT_6)
        self.check_special_symbol_input(*self.locator.BUT_6, name=N.BUT_6)
        self.check_letter_input(*self.locator.BUT_6, name=N.BUT_6)

        self.max_symbol_12_input(*self.locator.BUT_7, name=N.BUT_7)
        self.check_zero_value_input(*self.locator.BUT_7, name=N.BUT_7)
        self.check_special_symbol_input(*self.locator.BUT_7, name=N.BUT_7)
        self.check_letter_input(*self.locator.BUT_7, name=N.BUT_7)

        self.max_symbol_12_input(*self.locator.BUT_8, name=N.BUT_8)
        self.check_zero_value_input(*self.locator.BUT_8, name=N.BUT_8)
        self.check_special_symbol_input(*self.locator.BUT_8, name=N.BUT_8)
        self.check_letter_input(*self.locator.BUT_8, name=N.BUT_8)

        self.max_symbol_12_input(*self.locator.BUT_9, name=N.BUT_9)
        self.check_zero_value_input(*self.locator.BUT_9, name=N.BUT_9)
        self.check_special_symbol_input(*self.locator.BUT_9, name=N.BUT_9)
        self.check_letter_input(*self.locator.BUT_9, name=N.BUT_9)

        self.max_symbol_12_input(*self.locator.BUT_10, name=N.BUT_10)
        self.check_zero_value_input(*self.locator.BUT_10, name=N.BUT_10)
        self.check_special_symbol_input(*self.locator.BUT_10, name=N.BUT_10)
        self.check_letter_input(*self.locator.BUT_10, name=N.BUT_10)

        self.max_symbol_12_input(*self.locator.BUT_11, name=N.BUT_11)
        self.check_zero_value_input(*self.locator.BUT_11, name=N.BUT_11)
        self.check_special_symbol_input(*self.locator.BUT_11, name=N.BUT_11)
        self.check_letter_input(*self.locator.BUT_11, name=N.BUT_11)

        self.max_symbol_12_input(*self.locator.BUT_12, name=N.BUT_12)
        self.check_zero_value_input(*self.locator.BUT_12, name=N.BUT_12)
        self.check_special_symbol_input(*self.locator.BUT_12, name=N.BUT_12)
        self.check_letter_input(*self.locator.BUT_12, name=N.BUT_12)


    def second_page_2(self):
        self.scroll('500')
        self.find_element(*self.locator.ADD_STR).click()
        sleep(0.5)
        self.find_element(*self.locator.B).click()
        sleep(0.5)
        self.find_element(*self.locator.B_SELECT).click()
        self.max_symbol_14_input(*self.locator.D, name=N.D)
        self.check_zero_value_input(*self.locator.D, name=N.D)
        self.check_special_symbol_input(*self.locator.D, name=N.D)
        self.check_letter_input(*self.locator.D, name=N.D)

        self.max_symbol_6_input(*self.locator.E, name=N.E)
        self.check_zero_value_input(*self.locator.E, name=N.E)
        self.check_special_symbol_input(*self.locator.E, name=N.E)
        self.check_letter_input(*self.locator.E, name=N.E)

    def second_page_3(self):
        self.scroll('500')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.B).click()
        sleep(0.5)
        self.find_element(*self.locator.B_SELECT).click()
        self.max_symbol_12_input(*self.locator.C, name=N.C)
        self.check_zero_value_input(*self.locator.C, name=N.C)
        self.check_special_symbol_input(*self.locator.C, name=N.C)
        self.check_letter_input(*self.locator.C, name=N.C)
        self.find_element(*self.locator.C).send_keys('10')
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.D, name=N.D)
        self.check_zero_value_input(*self.locator.D, name=N.D)
        self.check_special_symbol_input(*self.locator.D, name=N.D)
        self.check_letter_input(*self.locator.D, name=N.D)
        self.find_element(*self.locator.D).send_keys('5')
        sleep(1)
        self.find_element(*self.locator.ADD).click()

    def second_page_4(self):
        self.scroll('600')
        self.max_symbol_12_input(*self.locator.TAX_BASE_1, name=N.TAX_BASE_1)
        self.check_zero_value_input(*self.locator.TAX_BASE_1, name=N.TAX_BASE_1)
        self.check_special_symbol_input(*self.locator.TAX_BASE_1, name=N.TAX_BASE_1)
        self.check_letter_input(*self.locator.TAX_BASE_1, name=N.TAX_BASE_1)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_1, name=N.EXC_R_1)
        self.check_zero_value_input(*self.locator.EXC_R_1, name=N.EXC_R_1)
        self.check_special_symbol_input(*self.locator.EXC_R_1, name=N.EXC_R_1)
        self.check_letter_input(*self.locator.EXC_R_1, name=N.EXC_R_1)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_2, name=N.TAX_BASE_2)
        self.check_zero_value_input(*self.locator.TAX_BASE_2, name=N.TAX_BASE_2)
        self.check_special_symbol_input(*self.locator.TAX_BASE_2, name=N.TAX_BASE_2)
        self.check_letter_input(*self.locator.TAX_BASE_2, name=N.TAX_BASE_2)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_2, name=N.EXC_R_2)
        self.check_zero_value_input(*self.locator.EXC_R_2, name=N.EXC_R_2)
        self.check_special_symbol_input(*self.locator.EXC_R_2, name=N.EXC_R_2)
        self.check_letter_input(*self.locator.EXC_R_2, name=N.EXC_R_2)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_3, name=N.TAX_BASE_3)
        self.check_zero_value_input(*self.locator.TAX_BASE_3, name=N.TAX_BASE_3)
        self.check_special_symbol_input(*self.locator.TAX_BASE_3, name=N.TAX_BASE_3)
        self.check_letter_input(*self.locator.TAX_BASE_3, name=N.TAX_BASE_3)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_3, name=N.EXC_R_3)
        self.check_zero_value_input(*self.locator.EXC_R_3, name=N.EXC_R_3)
        self.check_special_symbol_input(*self.locator.EXC_R_3, name=N.EXC_R_3)
        self.check_letter_input(*self.locator.EXC_R_3, name=N.EXC_R_3)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_4, name=N.TAX_BASE_4)
        self.check_zero_value_input(*self.locator.TAX_BASE_4, name=N.TAX_BASE_4)
        self.check_special_symbol_input(*self.locator.TAX_BASE_4, name=N.TAX_BASE_4)
        self.check_letter_input(*self.locator.TAX_BASE_4, name=N.TAX_BASE_4)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_4, name=N.EXC_R_4)
        self.check_zero_value_input(*self.locator.EXC_R_4, name=N.EXC_R_4)
        self.check_special_symbol_input(*self.locator.EXC_R_4, name=N.EXC_R_4)
        self.check_letter_input(*self.locator.EXC_R_4, name=N.EXC_R_4)
        sleep(0.5)
        self.scroll('800')
        self.max_symbol_12_input(*self.locator.TAX_BASE_5, name=N.TAX_BASE_5)
        self.check_zero_value_input(*self.locator.TAX_BASE_5, name=N.TAX_BASE_5)
        self.check_special_symbol_input(*self.locator.TAX_BASE_5, name=N.TAX_BASE_5)
        self.check_letter_input(*self.locator.TAX_BASE_5, name=N.TAX_BASE_5)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_5, name=N.EXC_R_5)
        self.check_zero_value_input(*self.locator.EXC_R_5, name=N.EXC_R_5)
        self.check_special_symbol_input(*self.locator.EXC_R_5, name=N.EXC_R_5)
        self.check_letter_input(*self.locator.EXC_R_5, name=N.EXC_R_5)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_6, name=N.TAX_BASE_6)
        self.check_zero_value_input(*self.locator.TAX_BASE_6, name=N.TAX_BASE_6)
        self.check_special_symbol_input(*self.locator.TAX_BASE_6, name=N.TAX_BASE_6)
        self.check_letter_input(*self.locator.TAX_BASE_6, name=N.TAX_BASE_6)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_6, name=N.EXC_R_6)
        self.check_zero_value_input(*self.locator.EXC_R_6, name=N.EXC_R_6)
        self.check_special_symbol_input(*self.locator.EXC_R_6, name=N.EXC_R_6)
        self.check_letter_input(*self.locator.EXC_R_6, name=N.EXC_R_6)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_7, name=N.TAX_BASE_7)
        self.check_zero_value_input(*self.locator.TAX_BASE_7, name=N.TAX_BASE_7)
        self.check_special_symbol_input(*self.locator.TAX_BASE_7, name=N.TAX_BASE_7)
        self.check_letter_input(*self.locator.TAX_BASE_7, name=N.TAX_BASE_7)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_7, name=N.EXC_R_7)
        self.check_zero_value_input(*self.locator.EXC_R_7, name=N.EXC_R_7)
        self.check_special_symbol_input(*self.locator.EXC_R_7, name=N.EXC_R_7)
        self.check_letter_input(*self.locator.EXC_R_7, name=N.EXC_R_7)
        sleep(0.5)
        self.scroll('500')
        self.max_symbol_12_input(*self.locator.TAX_BASE_8, name=N.TAX_BASE_8)
        self.check_zero_value_input(*self.locator.TAX_BASE_8, name=N.TAX_BASE_8)
        self.check_special_symbol_input(*self.locator.TAX_BASE_8, name=N.TAX_BASE_8)
        self.check_letter_input(*self.locator.TAX_BASE_8, name=N.TAX_BASE_8)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_8, name=N.EXC_R_8)
        self.check_zero_value_input(*self.locator.EXC_R_8, name=N.EXC_R_8)
        self.check_special_symbol_input(*self.locator.EXC_R_8, name=N.EXC_R_8)
        self.check_letter_input(*self.locator.EXC_R_8, name=N.EXC_R_8)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_9, name=N.TAX_BASE_9)
        self.check_zero_value_input(*self.locator.TAX_BASE_9, name=N.TAX_BASE_9)
        self.check_special_symbol_input(*self.locator.TAX_BASE_9, name=N.TAX_BASE_9)
        self.check_letter_input(*self.locator.TAX_BASE_9, name=N.TAX_BASE_9)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_9, name=N.EXC_R_9)
        self.check_zero_value_input(*self.locator.EXC_R_9, name=N.EXC_R_9)
        self.check_special_symbol_input(*self.locator.EXC_R_9, name=N.EXC_R_9)
        self.check_letter_input(*self.locator.EXC_R_9, name=N.EXC_R_9)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_10, name=N.TAX_BASE_10)
        self.check_zero_value_input(*self.locator.TAX_BASE_10, name=N.TAX_BASE_10)
        self.check_special_symbol_input(*self.locator.TAX_BASE_10, name=N.TAX_BASE_10)
        self.check_letter_input(*self.locator.TAX_BASE_10, name=N.TAX_BASE_10)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_10, name=N.EXC_R_10)
        self.check_zero_value_input(*self.locator.EXC_R_10, name=N.EXC_R_10)
        self.check_special_symbol_input(*self.locator.EXC_R_10, name=N.EXC_R_10)
        self.check_letter_input(*self.locator.EXC_R_10, name=N.EXC_R_10)
        sleep(0.5)
        self.scroll('1000')
        self.max_symbol_12_input(*self.locator.TAX_BASE_11, name=N.TAX_BASE_11)
        self.check_zero_value_input(*self.locator.TAX_BASE_11, name=N.TAX_BASE_11)
        self.check_special_symbol_input(*self.locator.TAX_BASE_11, name=N.TAX_BASE_11)
        self.check_letter_input(*self.locator.TAX_BASE_11, name=N.TAX_BASE_11)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_11, name=N.EXC_R_11)
        self.check_zero_value_input(*self.locator.EXC_R_11, name=N.EXC_R_11)
        self.check_special_symbol_input(*self.locator.EXC_R_11, name=N.EXC_R_11)
        self.check_letter_input(*self.locator.EXC_R_11, name=N.EXC_R_11)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_12, name=N.TAX_BASE_12)
        self.check_zero_value_input(*self.locator.TAX_BASE_12, name=N.TAX_BASE_12)
        self.check_special_symbol_input(*self.locator.TAX_BASE_12, name=N.TAX_BASE_12)
        self.check_letter_input(*self.locator.TAX_BASE_12, name=N.TAX_BASE_12)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_12, name=N.EXC_R_12)
        self.check_zero_value_input(*self.locator.EXC_R_12, name=N.EXC_R_12)
        self.check_special_symbol_input(*self.locator.EXC_R_12, name=N.EXC_R_12)
        self.check_letter_input(*self.locator.EXC_R_12, name=N.EXC_R_12)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_13, name=N.TAX_BASE_13)
        self.check_zero_value_input(*self.locator.TAX_BASE_13, name=N.TAX_BASE_13)
        self.check_special_symbol_input(*self.locator.TAX_BASE_13, name=N.TAX_BASE_13)
        self.check_letter_input(*self.locator.TAX_BASE_13, name=N.TAX_BASE_13)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_13, name=N.EXC_R_13)
        self.check_zero_value_input(*self.locator.EXC_R_13, name=N.EXC_R_13)
        self.check_special_symbol_input(*self.locator.EXC_R_13, name=N.EXC_R_13)
        self.check_letter_input(*self.locator.EXC_R_13, name=N.EXC_R_13)
        sleep(0.5)
        self.max_symbol_12_input(*self.locator.TAX_BASE_14, name=N.TAX_BASE_14)
        self.check_zero_value_input(*self.locator.TAX_BASE_14, name=N.TAX_BASE_14)
        self.check_special_symbol_input(*self.locator.TAX_BASE_14, name=N.TAX_BASE_14)
        self.check_letter_input(*self.locator.TAX_BASE_14, name=N.TAX_BASE_14)
        sleep(0.5)
        self.max_symbol_5_input(*self.locator.EXC_R_14, name=N.EXC_R_14)
        self.check_zero_value_input(*self.locator.EXC_R_14, name=N.EXC_R_14)
        self.check_special_symbol_input(*self.locator.EXC_R_14, name=N.EXC_R_14)
        self.check_letter_input(*self.locator.EXC_R_14, name=N.EXC_R_14)
        sleep(0.5)









