from locators.fno_250_locators import FNO250Locators
from browser_interaction import BasePage
import allure
from time import sleep


class FNO250Page(BasePage):
    def __init__(self, browser):
        super().__init__(browser)
        self.browser = browser
        self.locator = FNO250Locators

    def first_page(self):
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.find_element(*self.locator.CONTROL_TEXT).click()
        self.find_element(*self.locator.NOTICE_NUMBER).send_keys('123zxc/.;')
        sleep(0.3)
        self.find_element(*self.locator.NOTICE_DATE).click()
        sleep(0.3)
        self.find_element(*self.locator.NOTICE_DATE_SELECT).click()
        assert '123zxc/.;' not in self.browser.page_source
        self.scroll('600')
        self.find_element(*self.locator.RESIDENTION).click()
        sleep(0.5)
        self.find_element(*self.locator.RESIDENTION_SELECT).click()
        self.find_element(*self.locator.PHONE_NUMBER).send_keys('999999999')
        self.find_element(*self.locator.E_MAIL).send_keys('D@gmail.com')
        self.find_element(*self.locator.CONFIRMATION_1).click()
        self.find_element(*self.locator.CONFIRMATION_2).click()
        self.find_element(*self.locator.CONFIRMATION_3).click()
        self.find_element(*self.locator.CONFIRMATION_4).click()
        self.scroll('600')
        self.find_element(*self.locator.CONFIRMATION_5).click()
        self.find_element(*self.locator.CONFIRMATION_6).click()
        self.find_element(*self.locator.CONFIRMATION_7).click()
        self.find_element(*self.locator.CONFIRMATION_8).click()
        self.find_element(*self.locator.CONFIRMATION_9).click()
        self.find_element(*self.locator.CONFIRMATION_10).click()
        self.find_element(*self.locator.CONFIRMATION_11).click()
        self.find_element(*self.locator.CONFIRMATION_12).click()
        self.scroll('6000')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.FIRST_PAGE_B).click()
        sleep(0.3)
        self.find_element(*self.locator.FIRST_PAGE_B_SELECT).click()
        self.find_element(*self.locator.FIRST_PAGE_C).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_1(self):
        self.scroll('600')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_1_B_1).send_keys('123')
        self.find_element(*self.locator.APP_1_C_1).click()
        sleep(0.3)
        self.find_element(*self.locator.APP_1_C_1_SELECT).click()
        self.find_element(*self.locator.APP_1_D_1).send_keys('123')
        self.find_element(*self.locator.APP_1_E_1).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_1_B_2).send_keys('123')
        self.find_element(*self.locator.APP_1_C_2).send_keys('123')
        self.find_element(*self.locator.APP_1_D_2).click()
        sleep(0.3)
        self.find_element(*self.locator.APP_1_D_2_SELECT).click()
        self.find_element(*self.locator.APP_1_E_2).send_keys('123')
        self.find_element(*self.locator.APP_1_F_2).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_2(self):
        self.scroll('600')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_2_B_1).send_keys('123')
        self.find_element(*self.locator.APP_2_C_1).send_keys('123')
        self.find_element(*self.locator.APP_2_D_1).click()
        sleep(0.3)
        self.find_element(*self.locator.APP_2_D_1_SELECT).click()
        self.find_element(*self.locator.APP_2_E_1).click()
        sleep(0.3)
        self.find_element(*self.locator.APP_2_E_1_SELECT).click()
        self.find_element(*self.locator.APP_2_F_1).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_2_B_2).send_keys('123')
        self.find_element(*self.locator.APP_2_C_2).send_keys('123')
        self.find_element(*self.locator.APP_2_D_2).click()
        sleep(0.3)
        self.find_element(*self.locator.APP_2_D_2_SELECT).click()
        self.find_element(*self.locator.APP_2_E_2).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_3(self):
        self.scroll('600')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_3_B_1).send_keys('123')
        self.find_element(*self.locator.APP_3_C_1).send_keys('123')
        self.find_element(*self.locator.APP_3_D_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_3_D_1_SELECT).click()
        self.find_element(*self.locator.APP_3_E_1).send_keys('123')
        self.find_element(*self.locator.APP_3_F_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_3_F_1_SELECT).click()
        self.find_element(*self.locator.APP_3_G_1).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_3_B_2).send_keys('123')
        self.find_element(*self.locator.APP_3_C_2).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_3_C_2_SELECT).click()
        self.find_element(*self.locator.APP_3_D_2).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_3_D_2_SELECT).click()
        self.find_element(*self.locator.APP_3_E_2).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_4(self):
        self.scroll('600')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_4_B_1).send_keys('123')
        self.find_element(*self.locator.APP_4_C_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_4_C_1_SELECT).click()
        self.find_element(*self.locator.APP_4_D_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_4_D_1_SELECT).click()
        self.find_element(*self.locator.APP_4_E_1).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_4_B_2).send_keys('123')
        self.find_element(*self.locator.APP_4_C_2).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_4_C_2_SELECT).click()
        self.find_element(*self.locator.APP_4_D_2).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_4_D_2_SELECT).click()
        self.find_element(*self.locator.APP_4_E_2).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_5(self):
        self.scroll('600')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_5_B_1).send_keys('123')
        self.find_element(*self.locator.APP_5_C_1).send_keys('123')
        self.find_element(*self.locator.APP_5_D_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_5_D_1_SELECT).click()
        self.find_element(*self.locator.APP_5_E_1).click()
        sleep(0.5)
        self.find_element(*self.locator.TODAY).click()
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_5_B_2).send_keys('123')
        self.find_element(*self.locator.APP_5_C_2).send_keys('123')
        self.find_element(*self.locator.APP_5_D_2).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_5_D_2_SELECT).click()
        self.find_element(*self.locator.APP_5_E_2).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_5_E_2_SELECT).click()
        self.find_element(*self.locator.APP_5_F_2).send_keys('123')

    def app_6(self):
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()
        self.find_element(*self.locator.APP_6_B_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_6_B_1_SELECT).click()
        self.find_element(*self.locator.APP_6_C_1).send_keys('123')
        self.find_element(*self.locator.APP_6_D_1).send_keys('123')
        self.find_element(*self.locator.APP_6_E_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_6_E_1_SELECT).click()
        self.find_element(*self.locator.APP_6_F_1).click()
        sleep(0.5)
        self.find_element(*self.locator.APP_6_F_1_SELECT).click()
        self.find_element(*self.locator.APP_6_G_1).send_keys('123')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.APP_6_B_2).send_keys('123')
        self.find_element(*self.locator.APP_6_C_2).send_keys('123')
        self.find_element(*self.locator.APP_6_D_2).send_keys('123')
        self.find_element(*self.locator.APP_6_E_2).click()
        sleep(0.5)
        self.find_element(*self.locator.TODAY).click()
        self.find_element(*self.locator.APP_6_F_2).click()
        sleep(0.5)
        self.find_element(*self.locator.TODAY).click()
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()