from locators.fno_100_locators import FNO100Locators
from browser_interaction import BasePage
import allure
from time import sleep


class FNO100Page(BasePage):
    def __init__(self, browser):
        super().__init__(browser)
        self.browser = browser
        self.locator = FNO100Locators

    # ПРОВЕРКА ТОГО ЧТО МЫ ВЫБРАЛИ ПРАВИЛЬНОЕ ФНО
    def check_tax_period_text(self):
        try:
            assert '100.00 Декларация по корпоративному подоходному налогу' \
                   in self.browser.page_source
        finally:
            allure.attach(self.browser.get_screenshot_as_png(), name='Выборка налогового периода',
                          attachment_type=allure.attachment_type.PNG)

    # ВЫБОР НАЛОГОВОГО ПЕРИОДА
    def select_date_tax_pay(self):
        self.find_element(*self.locator.QUARTER_SELECT).click()
        self.find_element(*self.locator.FIRST_QUARTER_SELECT).click()
        self.find_element(*self.locator.YEAR_SELECT).click()
        self.find_element(*self.locator.SELECT_2020).click()
        sleep(0.5)
        self.find_element(*self.locator.SEND_TAX_PERIOD).click()

    def tax_period_select(self):
        self.check_tax_period_text()
        self.select_date_tax_pay()

    # НИЖЕ ПЕРВАЯ СТРАНИЦА
    def first_page_1(self):
        self.scroll('300')
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.scroll('500')
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES).click()
        sleep(0.3)
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES_SELECT).click()
        self.find_element(*self.locator.RESIDENT).click()
        sleep(0.3)
        self.find_element(*self.locator.RESIDENT_SELECT).click()
        #self.find_element(*self.locator.CONFIRM_1).click()
        self.find_element(*self.locator.CONFIRM_2).click()
        self.scroll('500')
        self.find_element(*self.locator.APPS).click()
        sleep(0.3)
        self.scroll('500')
        sleep(1)
        self.find_element(*self.locator.APP_1).click()
        self.find_element(*self.locator.CONTROL_TEXT2).click()
        self.find_element(*self.locator.AFTER).click()

    def first_page_2(self):
        self.scroll('300')
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.scroll('500')
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES).click()
        sleep(0.3)
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES_SELECT).click()
        self.find_element(*self.locator.RESIDENT).click()
        sleep(0.3)
        self.find_element(*self.locator.RESIDENT_SELECT).click()
        self.find_element(*self.locator.CONFIRM_1).click()
        self.find_element(*self.locator.CONFIRM_2).click()
        self.scroll('500')
        self.find_element(*self.locator.APPS).click()
        sleep(0.3)
        self.scroll('500')
        self.find_element(*self.locator.APP_2).click()
        self.find_element(*self.locator.CONTROL_TEXT2).click()
        self.find_element(*self.locator.AFTER).click()

    def first_page_3(self):
        self.scroll('300')
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.scroll('500')
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES).click()
        sleep(0.3)
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES_SELECT).click()
        self.find_element(*self.locator.RESIDENT).click()
        sleep(0.3)
        self.find_element(*self.locator.RESIDENT_SELECT).click()
        self.find_element(*self.locator.CONFIRM_1).click()
        self.find_element(*self.locator.CONFIRM_2).click()
        self.scroll('500')
        self.find_element(*self.locator.APPS).click()
        sleep(0.3)
        self.scroll('500')
        self.find_element(*self.locator.APP_3).click()
        self.find_element(*self.locator.CONTROL_TEXT2).click()
        self.find_element(*self.locator.AFTER).click()

    def first_page_6(self):
        self.scroll('300')
        self.find_element(*self.locator.DECLARATION_TYPE).click()
        sleep(0.3)
        self.find_element(*self.locator.DECLARATION_TYPE_SELECT).click()
        self.scroll('500')
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES).click()
        sleep(0.3)
        self.find_element(*self.locator.TAX_PAYER_CATEGORIES_SELECT).click()
        self.find_element(*self.locator.RESIDENT).click()
        sleep(0.3)
        self.find_element(*self.locator.RESIDENT_SELECT).click()
        self.find_element(*self.locator.CONFIRM_1).click()
        self.find_element(*self.locator.CONFIRM_2).click()
        self.scroll('500')
        self.find_element(*self.locator.APPS).click()
        sleep(2)
        self.scroll('1000')
        element = self.browser.find_element_by_xpath(
            '/html/body/div[2]/div/div/div/div/div/div[3]/div[1]/div/div/div[4]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.APP_6).click()
        self.find_element(*self.locator.CONTROL_TEXT2).click()
        self.find_element(*self.locator.AFTER).click()

    # НИЖЕ ВТОРАЯ СТРАНИЦА
    def second_page(self):
        self.find_element(*self.locator.REAL_INCOME_1).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.REAL_INCOME_2).send_keys('5')
        sleep(0.3)
        self.find_element(*self.locator.REAL_INCOME_3).send_keys('20')
        sleep(0.3)
        self.find_element(*self.locator.REAL_INCOME_4).send_keys('3')
        sleep(0.5)
        assert '38' in self.browser.page_source
        self.scroll('200')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_2).send_keys('2')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_3).send_keys('4')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_4).send_keys('6')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_5).send_keys('1')
        sleep(0.3)
        self.scroll('600')
        self.find_element(*self.locator.INCOME_6).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_6_I).send_keys('4')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_7_I).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_7_II).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_8).send_keys('20')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_9).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_10).send_keys('50')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_11).send_keys('7')
        sleep(0.3)
        self.find_element(*self.locator.INCOME_12).send_keys('4')
        sleep(0.3)
        self.scroll('5000')
        self.find_element(*self.locator.INCOME_13).send_keys('10')

        sleep(1)
        assert '163' in self.browser.page_source
        self.find_element(*self.locator.AFTER).click()

    # НИЖЕ ТРЕТЬЯ СТРАНИЦА
    def third_page(self):
        sleep(1)
        self.scroll('200')
        self.find_element(*self.locator.CORR_INCOME_1).send_keys('2')
        self.find_element(*self.locator.CORR_INCOME_2).send_keys('3')
        self.find_element(*self.locator.CORR_INCOME_3).send_keys('4')
        self.find_element(*self.locator.CORR_INCOME_4).send_keys('5')
        self.find_element(*self.locator.CORR_INCOME_5).send_keys('6')
        self.find_element(*self.locator.CORR_INCOME_6).send_keys('7')
        self.find_element(*self.locator.CORR_INCOME_7).send_keys('8')
        self.scroll('600')
        self.find_element(*self.locator.CORR_INCOME_8).send_keys('10')
        self.find_element(*self.locator.CORR_INCOME_9).send_keys('30')
        self.find_element(*self.locator.CORR_INCOME_10).send_keys('40')
        self.find_element(*self.locator.CORR_INCOME_11).send_keys('50')
        self.find_element(*self.locator.CORR_INCOME_12).send_keys('60')
        self.find_element(*self.locator.CORR_INCOME_13).send_keys('70')
        self.find_element(*self.locator.CORR_INCOME_14).send_keys('80')
        self.scroll('700')
        self.find_element(*self.locator.CORR_INCOME_15).send_keys('100')
        self.find_element(*self.locator.CORR_INCOME_16).send_keys('300')
        self.find_element(*self.locator.CORR_INCOME_17).send_keys('400')
        self.find_element(*self.locator.CORR_INCOME_18).send_keys('500')
        self.find_element(*self.locator.CORR_INCOME_19).send_keys('600')
        self.find_element(*self.locator.CORR_INCOME_20).send_keys('700')
        self.find_element(*self.locator.CORR_INCOME_21).send_keys('800')
        self.find_element(*self.locator.CORR_INCOME_22).send_keys('800')
        self.scroll('700')
        self.find_element(*self.locator.CORR_INCOME_23).send_keys('6')
        self.find_element(*self.locator.CORR_INCOME_24).send_keys('7')
        self.find_element(*self.locator.CORR_INCOME_25).send_keys('8')
        self.find_element(*self.locator.CORR_INCOME_26).send_keys('10')
        self.find_element(*self.locator.CORR_INCOME_27).send_keys('5')
        sleep(1)
        self.find_element(*self.locator.AFTER).click()

        # НИЖЕ ЧЕТВЕРТАЯ СТРАНИЦА

    def fourth_page(self):
        sleep(1)
        self.scroll('300')
        self.find_element(*self.locator.STOCK_1).send_keys('5')
        self.find_element(*self.locator.STOCK_2).send_keys('2')
        #self.find_element(*self.locator.STOCK_3).send_keys('3')
        self.find_element(*self.locator.SERVICE_1).send_keys('30')
        self.find_element(*self.locator.SERVICE_2).send_keys('20')
        self.find_element(*self.locator.SERVICE_3).send_keys('10')
        self.find_element(*self.locator.SERVICE_4).send_keys('40')
        self.find_element(*self.locator.SERVICE_5).send_keys('50')
        self.find_element(*self.locator.SERVICE_6).send_keys('60')
        self.find_element(*self.locator.SERVICE_7).send_keys('36')
        self.find_element(*self.locator.SERVICE_8).send_keys('7')
        self.scroll('600')
        self.find_element(*self.locator.STOCK_4).send_keys('5')
        self.find_element(*self.locator.STOCK_5).send_keys('2')
        self.find_element(*self.locator.STOCK_6).send_keys('3')
        self.find_element(*self.locator.STOCK_7).send_keys('5')
        self.find_element(*self.locator.STOCK_8).send_keys('2')
        self.find_element(*self.locator.STOCK_9).send_keys('3')
        self.scroll('600')
        self.find_element(*self.locator.FIELD_1).send_keys('10')
        self.find_element(*self.locator.FIELD_2).send_keys('20')
        self.find_element(*self.locator.FIELD_3).send_keys('30')
        self.find_element(*self.locator.FIELD_4).send_keys('40')
        self.find_element(*self.locator.FIELD_5).send_keys('50')
        self.find_element(*self.locator.FIELD_6).send_keys('60')
        self.find_element(*self.locator.FIELD_7).send_keys('70')
        self.find_element(*self.locator.FIELD_8).send_keys('80')
        sleep(1)
        self.scroll('600')
        self.find_element(*self.locator.LOANS_1).send_keys('50')
        self.find_element(*self.locator.LOANS_2).send_keys('60')
        self.find_element(*self.locator.LOANS_3).send_keys('70')
        self.find_element(*self.locator.LOANS_4).send_keys('80')
        self.scroll('500')
        self.find_element(*self.locator.FIELD_9).send_keys('10')
        self.find_element(*self.locator.FIELD_10).send_keys('20')
        self.find_element(*self.locator.FIELD_11).send_keys('30')
        self.find_element(*self.locator.FIELD_12).send_keys('40')
        self.find_element(*self.locator.FIELD_13).send_keys('50')
        self.scroll('500')
        self.find_element(*self.locator.FIELD_14).send_keys('60')
        self.find_element(*self.locator.FIELD_15).send_keys('70')
        self.find_element(*self.locator.FIELD_16).send_keys('80')
        self.scroll('700')
        self.find_element(*self.locator.FIELD_17_I).send_keys('10')
        self.find_element(*self.locator.FIELD_17_II).send_keys('20')
        self.find_element(*self.locator.FIELD_18).send_keys('30')
        self.find_element(*self.locator.FIELD_19).send_keys('40')
        self.scroll('400')
        #self.find_element(*self.locator.FIELD_20_I).send_keys('40')
        #self.find_element(*self.locator.FIELD_20_II).send_keys('40')
        #self.find_element(*self.locator.FIELD_20_III).send_keys('40')
        self.find_element(*self.locator.FIELD_20_IV).send_keys('40')
        self.find_element(*self.locator.AFTER).click()

    def five_page(self):
        self.scroll('500')
        self.find_element(*self.locator.AFTER).click()

    def six_page(self):
        self.scroll('1200')
        self.find_element(*self.locator.FIELD_21_I).send_keys('10')
        self.find_element(*self.locator.FIELD_21_I_A).send_keys('11')
        self.find_element(*self.locator.FIELD_21_I_B).send_keys('12')
        self.find_element(*self.locator.FIELD_21_II).send_keys('13')
        self.scroll('600')
        self.find_element(*self.locator.FIELD_22).send_keys('10')
        self.find_element(*self.locator.FIELD_23_III).send_keys('14')
        self.find_element(*self.locator.FIELD_23_IV).send_keys('15')
        self.find_element(*self.locator.FIELD_23_V).send_keys('16')
        self.scroll('600')
        self.find_element(*self.locator.FIELD_23_VI).send_keys('17')
        self.find_element(*self.locator.FIELD_24).send_keys('18')
        self.scroll('600')
        self.find_element(*self.locator.FIELD_25_B).send_keys('19')
        self.find_element(*self.locator.FIELD_25_A).send_keys('19')
        self.find_element(*self.locator.FIELD_25_III).click()
        self.find_element(*self.locator.FIELD_25_III_SELECT).click()
        self.find_element(*self.locator.FIELD_25_IV).send_keys('21')
        self.find_element(*self.locator.AFTER).click()

    def app_one(self):
        self.scroll('400')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.B_APP_1).send_keys('123456789012')
        self.find_element(*self.locator.E_APP_1).click()
        sleep(0.5)
        self.find_element(*self.locator.E_SELECT_APP_1).click()
        self.find_element(*self.locator.D_APP_1).send_keys('2')
        self.find_element(*self.locator.F_APP_1).send_keys('3')
        self.scroll('500')
        self.find_element(*self.locator.G_APP_1).click()
        sleep(0.5)
        self.find_element(*self.locator.G_SELECT_APP_1).click()
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_two(self):
        sleep(1)
        self.scroll('400')
        self.find_element(*self.locator.GROUP_1).send_keys('5')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_2).send_keys('1')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_3).send_keys('2')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_4).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_5).send_keys('6')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_6).send_keys('4')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_7).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_8).send_keys('2')
        self.scroll('500')
        self.find_element(*self.locator.GROUP_9).send_keys('5')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_10).send_keys('1')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_11).send_keys('2')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_12).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_13).send_keys('6')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_14).send_keys('4')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_15).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_16).send_keys('2')
        sleep(0.3)
        self.scroll('500')
        self.find_element(*self.locator.GROUP_17).send_keys('50')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_18).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_19).send_keys('20')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_20).send_keys('30')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_21).send_keys('60')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_22).send_keys('40')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_23).send_keys('30')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_24).send_keys('20')
        sleep(0.3)
        self.scroll('700')
        self.find_element(*self.locator.GROUP_25).send_keys('50')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_26).send_keys('70')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_27).send_keys('80')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_28).send_keys('90')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_29).send_keys('100')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_30).send_keys('300')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_31).send_keys('600')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_32).send_keys('400')
        self.scroll('600')
        self.find_element(*self.locator.GROUP_33).send_keys('5')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_34).send_keys('7')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_35).send_keys('8')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_36).send_keys('9')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_37).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_38).send_keys('30')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_39).send_keys('20')
        sleep(0.3)
        self.find_element(*self.locator.GROUP_40).send_keys('40')
        self.scroll('500')
        self.find_element(*self.locator.EXPENSES).send_keys('90')
        self.find_element(*self.locator.AFTER).click()

    def app_three(self):
        sleep(1)
        self.scroll('122500')
        self.find_element(*self.locator.AFTER).click()

    def app_four(self):
        sleep(1)
        self.scroll('133333')
        sleep(0.2)
        self.find_element(*self.locator.ADD_STR).click()
        sleep(0.2)
        self.find_element(*self.locator.B_APP_4).click()
        sleep(0.3)
        self.find_element(*self.locator.B_SELECT_APP_4).click()
        sleep(0.3)
        self.find_element(*self.locator.C_APP_4).send_keys('1')
        self.find_element(*self.locator.D_APP_4).click()
        sleep(0.3)
        self.find_element(*self.locator.D_SELECT_APP_4).click()
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_five(self):
        sleep(1)
        self.scroll('10000')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.B_APP_5).click()
        sleep(0.3)
        self.find_element(*self.locator.B_SELECT_3).click()
        self.find_element(*self.locator.C_APP_5).click()
        sleep(0.3)
        self.find_element(*self.locator.C_SELECT_3).click()
        self.find_element(*self.locator.D_APP_5).click()
        sleep(0.3)
        self.find_element(*self.locator.D_SELECT_3).click()
        self.find_element(*self.locator.E_APP_5).send_keys('1')
        self.find_element(*self.locator.F_APP_5).send_keys('2')
        element = self.browser.find_element_by_xpath('//*[@name="K"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.G_APP_5).send_keys('3')
        self.find_element(*self.locator.H_APP_5).send_keys('4')
        self.find_element(*self.locator.J_APP_5).send_keys('5')
        self.find_element(*self.locator.I_APP_5).send_keys('6')
        self.find_element(*self.locator.K_APP_5).send_keys('7')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_six(self):
        sleep(1)
        self.scroll('400')
        self.find_element(*self.locator.ACTIVITY_TYPE).click()
        self.find_element(*self.locator.ACTIVITY_TYPE_SELECT).click()
        sleep(0.2)
        self.find_element(*self.locator.YEAR_EXPENSE).send_keys('5')
        sleep(0.2)
        self.find_element(*self.locator.STR_1).send_keys('5')
        sleep(0.2)
        self.find_element(*self.locator.STR_2).send_keys('10')
        sleep(0.2)
        self.find_element(*self.locator.STR_3_I).send_keys('10')
        sleep(0.2)
        self.find_element(*self.locator.STR_3_II).send_keys('10')
        sleep(0.2)
        self.scroll('600')
        self.find_element(*self.locator.STR_4).send_keys('2')
        sleep(0.2)
        self.find_element(*self.locator.STR_5).send_keys('3')
        sleep(0.2)
        self.find_element(*self.locator.STR_6).send_keys('4')
        sleep(0.2)
        self.find_element(*self.locator.STR_7).send_keys('5')
        sleep(0.2)
        self.scroll('600')
        self.find_element(*self.locator.STR_8).send_keys('6')
        sleep(0.2)
        self.find_element(*self.locator.STR_9_I).send_keys('7')
        sleep(0.2)
        self.find_element(*self.locator.STR_9_II).send_keys('8')
        sleep(0.3)
        self.find_element(*self.locator.STR_10).send_keys('9')
        sleep(0.3)
        self.find_element(*self.locator.STR_11).send_keys('10')
        self.scroll('700')
        self.find_element(*self.locator.STR_12).send_keys('2')
        sleep(0.3)
        self.find_element(*self.locator.STR_13).send_keys('3')
        sleep(0.2)
        self.find_element(*self.locator.STR_14).send_keys('4')
        sleep(0.3)
        self.find_element(*self.locator.STR_15).send_keys('10')
        sleep(0.3)
        self.scroll('700')
        self.find_element(*self.locator.STR_16_I).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.STR_16_II).send_keys('20')
        sleep(0.3)
        self.find_element(*self.locator.STR_16_III).send_keys('30')
        sleep(0.3)
        self.find_element(*self.locator.STR_16_IV).send_keys('40')
        sleep(0.3)
        self.find_element(*self.locator.STR_16_V).send_keys('50')
        sleep(0.3)
        self.find_element(*self.locator.STR_16_VI).send_keys('60')
        sleep(0.3)
        self.find_element(*self.locator.STR_16_VII).send_keys('70')
        sleep(0.3)
        self.scroll('500')
        sleep(0.3)
        self.find_element(*self.locator.PERCENT).send_keys('5')
        sleep(0.3)
        self.find_element(*self.locator.PERCENT_2).send_keys('10')
        sleep(0.3)
        self.find_element(*self.locator.COUNTRY).click()
        sleep(0.3)
        self.find_element(*self.locator.COUNTRY_SELECT).click()
        self.scroll('500')
        sleep(0.3)
        self.find_element(*self.locator.NAME_OF_INT_CONTRACT).send_keys('10')
        self.find_element(*self.locator.AFTER).click()

    def app_seven(self):
        self.hover(*self.locator.CONTROL_TEXT)
        sleep(1)
        self.find_element(*self.locator.CHAPTER_1).click()
        self.scroll('500')
        self.find_element(*self.locator.START_1).send_keys('10')
        sleep(0.2)
        self.find_element(*self.locator.END_1).send_keys('20')
        sleep(0.2)
        self.find_element(*self.locator.START_2).send_keys('30')
        sleep(0.2)
        self.find_element(*self.locator.END_2).send_keys('40')
        sleep(0.2)
        self.find_element(*self.locator.START_3).send_keys('50')
        sleep(0.2)
        self.find_element(*self.locator.END_3).send_keys('60')
        sleep(0.2)
        self.find_element(*self.locator.START_4).send_keys('70')
        sleep(0.2)
        self.find_element(*self.locator.END_4).send_keys('80')
        sleep(0.2)
        self.find_element(*self.locator.START_5).send_keys('90')
        sleep(0.2)
        self.find_element(*self.locator.END_5).send_keys('100')
        sleep(0.2)
        self.find_element(*self.locator.START_6).send_keys('110')
        sleep(0.2)
        self.find_element(*self.locator.END_6).send_keys('120')
        sleep(0.2)
        self.scroll('700')
        self.find_element(*self.locator.START_7).send_keys('130')
        sleep(0.2)
        self.find_element(*self.locator.END_7).send_keys('140')
        sleep(0.2)
        self.find_element(*self.locator.START_8).send_keys('150')
        sleep(0.2)
        self.find_element(*self.locator.END_8).send_keys('160')
        sleep(0.2)
        self.find_element(*self.locator.START_9).send_keys('170')
        sleep(0.2)
        self.find_element(*self.locator.END_9).send_keys('180')
        sleep(0.2)
        self.find_element(*self.locator.START_10).send_keys('190')
        sleep(0.2)
        self.find_element(*self.locator.END_10).send_keys('200')
        sleep(0.2)
        self.find_element(*self.locator.START_11).send_keys('210')
        sleep(0.2)
        self.find_element(*self.locator.END_11).send_keys('220')
        sleep(0.2)
        self.find_element(*self.locator.START_12).send_keys('230')
        sleep(0.2)
        self.find_element(*self.locator.END_12).send_keys('240')
        sleep(0.2)
        self.scroll('700')
        self.find_element(*self.locator.START_13).send_keys('250')
        sleep(0.2)
        self.find_element(*self.locator.END_13).send_keys('260')
        sleep(0.2)
        self.find_element(*self.locator.START_14).send_keys('270')
        sleep(0.2)
        self.find_element(*self.locator.END_14).send_keys('280')
        sleep(0.2)
        self.find_element(*self.locator.START_15).send_keys('290')
        sleep(0.2)
        self.find_element(*self.locator.END_15).send_keys('300')
        sleep(0.2)
        self.find_element(*self.locator.START_16).send_keys('310')
        sleep(0.2)
        self.find_element(*self.locator.END_16).send_keys('320')
        sleep(0.2)
        self.find_element(*self.locator.START_17).send_keys('330')
        sleep(0.2)
        self.find_element(*self.locator.END_17).send_keys('340')
        sleep(0.2)
        self.scroll('200')
        assert '2890' in self.browser.page_source
        assert '3060' in self.browser.page_source
        sleep(0.5)
        self.find_element(*self.locator.CHAPTER_2).click()
        sleep(0.5)
        self.scroll('700')
        self.find_element(*self.locator.START_19).send_keys('350')
        sleep(0.2)
        self.find_element(*self.locator.END_19).send_keys('360')
        sleep(0.2)
        self.find_element(*self.locator.START_20).send_keys('370')
        sleep(0.2)
        self.find_element(*self.locator.END_20).send_keys('380')
        sleep(0.2)
        self.find_element(*self.locator.START_21).send_keys('390')
        sleep(0.2)
        self.find_element(*self.locator.END_21).send_keys('400')
        sleep(0.2)
        self.find_element(*self.locator.START_22).send_keys('410')
        sleep(0.2)
        self.find_element(*self.locator.END_22).send_keys('420')
        sleep(0.2)
        self.find_element(*self.locator.START_23).send_keys('430')
        sleep(0.2)
        self.find_element(*self.locator.END_23).send_keys('440')
        sleep(0.2)
        self.find_element(*self.locator.START_24).send_keys('450')
        sleep(0.2)
        self.find_element(*self.locator.END_24).send_keys('460')
        sleep(0.2)
        self.scroll('700')
        self.find_element(*self.locator.START_25).send_keys('470')
        sleep(0.2)
        self.find_element(*self.locator.END_25).send_keys('480')
        sleep(0.2)
        self.find_element(*self.locator.START_26).send_keys('490')
        sleep(0.2)
        self.find_element(*self.locator.END_26).send_keys('500')
        sleep(0.2)
        self.find_element(*self.locator.START_27).send_keys('510')
        sleep(0.2)
        self.find_element(*self.locator.END_27).send_keys('520')
        sleep(0.2)
        self.find_element(*self.locator.START_28).send_keys('530')
        sleep(0.2)
        self.find_element(*self.locator.END_28).send_keys('540')
        sleep(0.2)
        self.find_element(*self.locator.START_29).send_keys('550')
        sleep(0.2)
        self.find_element(*self.locator.END_29).send_keys('560')
        sleep(1)
        self.scroll('200')
        assert '4950' in self.browser.page_source
        assert '5060' in self.browser.page_source
        self.find_element(*self.locator.CHAPTER_3).click()
        self.scroll('700')
        self.find_element(*self.locator.START_31).send_keys('570')
        sleep(0.2)
        self.find_element(*self.locator.END_31).send_keys('580')
        sleep(0.2)
        self.find_element(*self.locator.START_32).send_keys('590')
        sleep(0.2)
        self.find_element(*self.locator.END_32).send_keys('600')
        sleep(0.2)
        self.find_element(*self.locator.START_33).send_keys('610')
        sleep(0.2)
        self.find_element(*self.locator.END_33).send_keys('620')
        sleep(0.2)
        self.find_element(*self.locator.START_34).send_keys('630')
        sleep(0.2)
        self.find_element(*self.locator.END_34).send_keys('640')
        sleep(0.2)
        self.find_element(*self.locator.START_35).send_keys('650')
        sleep(0.2)
        self.find_element(*self.locator.END_35).send_keys('660')
        sleep(0.2)
        self.find_element(*self.locator.START_36).send_keys('670')
        sleep(0.2)
        self.find_element(*self.locator.END_36).send_keys('680')
        sleep(0.2)
        self.find_element(*self.locator.START_37).send_keys('690')
        sleep(0.2)
        self.find_element(*self.locator.END_37).send_keys('700')
        self.scroll('500')
        sleep(1)
        assert '4410' in self.browser.page_source
        assert '4480' in self.browser.page_source
        self.find_element(*self.locator.AFTER).click()

    def app_eight(self):
        sleep(1)
        self.scroll('400')
        self.find_element(*self.locator.EIGHT_PAGE_1).send_keys('10')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_2).send_keys('20')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_3).send_keys('30')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_4).send_keys('40')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_5).send_keys('50')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_6).send_keys('60')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_7).send_keys('70')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_8).send_keys('80')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_9).send_keys('90')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_10).send_keys('100')
        sleep(0.2)
        self.find_element(*self.locator.EIGHT_PAGE_11).send_keys('110')
        sleep(0.2)
        self.find_element(*self.locator.AFTER).click()

    def app_nine(self):
        sleep(1)
        self.scroll('10000')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.B_APP_9).send_keys('1')
        sleep(0.3)
        self.find_element(*self.locator.C_APP_9).click()
        sleep(0.3)
        self.find_element(*self.locator.C_SELECT_APP_9).click()
        sleep(0.3)
        self.find_element(*self.locator.D_APP_9).send_keys('1')
        sleep(0.3)
        self.find_element(*self.locator.E_APP_9).send_keys('1')
        sleep(0.3)
        self.find_element(*self.locator.F_APP_9).click()
        sleep(0.3)
        self.find_element(*self.locator.F_SELECT_APP_9).click()
        element = self.browser.find_element_by_xpath('//*[@name="Q"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.G_APP_9).send_keys('4')
        sleep(0.3)
        self.find_element(*self.locator.H_APP_9).send_keys('3')
        sleep(0.3)
        self.find_element(*self.locator.J_APP_9).send_keys('5')
        sleep(0.3)
        # self.find_element(*self.locator.I).send_keys('6')
        sleep(0.3)
        # self.find_element(*self.locator.K).send_keys('7')
        self.find_element(*self.locator.L_APP_9).send_keys('4')
        self.find_element(*self.locator.M_APP_9).send_keys('5')
        self.find_element(*self.locator.N_APP_9).send_keys('6')
        self.find_element(*self.locator.O_APP_9).send_keys('7')
        self.find_element(*self.locator.P_APP_9).send_keys('4')
        self.find_element(*self.locator.Q_APP_9).send_keys('5')
        self.find_element(*self.locator.ADD).click()
        self.find_element(*self.locator.AFTER).click()

    def app_ten(self):
        sleep(1)
        self.find_element(*self.locator.EARNING_TEN).click()
        self.scroll('400')
        self.find_element(*self.locator.TEN_PAGE_1).send_keys('1')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_2).send_keys('2')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_3).send_keys('3')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_4).send_keys('4')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_5).send_keys('5')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_6).send_keys('6')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_7).send_keys('7')
        sleep(0.2)
        self.scroll('600')
        self.find_element(*self.locator.TEN_PAGE_8).send_keys('8')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_9).send_keys('9')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_10).send_keys('10')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_12).send_keys('12')
        sleep(0.2)
        assert '55' in self.browser.page_source
        assert '67' in self.browser.page_source
        self.scroll('500')
        self.find_element(*self.locator.EXPENSES_TEN).click()
        self.find_element(*self.locator.TEN_PAGE_14_I).send_keys('141')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_II).send_keys('142')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_III).send_keys('143')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_IV).send_keys('144')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_V).send_keys('145')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_VI).send_keys('146')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_VII).send_keys('147')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_VIII).send_keys('148')
        sleep(0.2)
        self.scroll('650')
        self.find_element(*self.locator.TEN_PAGE_14_IX).send_keys('149')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_X).send_keys('150')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XI).send_keys('151')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XII).send_keys('152')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XIII).send_keys('153')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XIV).send_keys('154')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XV).send_keys('155')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XVI).send_keys('156')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XVII).send_keys('157')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XVIII).send_keys('158')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XIX_A).send_keys('1591')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XIX_B).send_keys('1592')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XIX_C).send_keys('1593')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XIX_D).send_keys('1594')
        sleep(0.2)
        self.scroll('700')
        self.find_element(*self.locator.TEN_PAGE_14_XIX_E).send_keys('1595')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XX).send_keys('160')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_14_XXI).send_keys('161')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_I).send_keys('151')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_II).send_keys('152')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_III).send_keys('153')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_IV).send_keys('154')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_V).send_keys('155')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_VI).send_keys('156')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_VII).send_keys('157')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_VIII).send_keys('158')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_IX).send_keys('159')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_X).send_keys('160')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_15_XI).send_keys('161')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_16).send_keys('160')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_17).send_keys('170')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_18).send_keys('180')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_19).send_keys('190')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_20).send_keys('200')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_21).send_keys('210')
        sleep(0.2)
        self.find_element(*self.locator.TEN_PAGE_22).send_keys('220')
        sleep(0.2)
        self.find_element(*self.locator.AFTER).click()

    def app_eleven(self):
        sleep(1)
        self.scroll('10000')
        self.find_element(*self.locator.ADD_STR).click()
        self.find_element(*self.locator.B_APP_11).send_keys('123456789012')
        self.find_element(*self.locator.C_APP_11).click()
        sleep(0.2)
        self.find_element(*self.locator.C_SELECT_APP_11).click()
        self.find_element(*self.locator.D_APP_11).send_keys('1')
        self.find_element(*self.locator.E_APP_11).click()
        sleep(0.2)
        self.find_element(*self.locator.E_SELECT_APP_11).click()
        self.find_element(*self.locator.F_APP_11).click()
        sleep(0.2)
        self.find_element(*self.locator.F_SELECT_APP_11).click()
        element = self.browser.find_element_by_xpath('//*[text()="Добавить"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.G_A_APP_11).send_keys('2')
        sleep(0.2)
        self.find_element(*self.locator.G_B_APP_11).click()
        sleep(0.5)
        self.find_element(*self.locator.G_DATE_SELECT_APP_11).click()
        self.find_element(*self.locator.H_APP_11).send_keys('3')
        sleep(0.2)
        self.find_element(*self.locator.I_APP_11).send_keys('4')
        sleep(0.2)
        self.find_element(*self.locator.ADD).click()
        sleep(0.2)
        self.find_element(*self.locator.AFTER).click()

    def app_twelve(self):
        sleep(1)
        self.find_element(*self.locator.TWELVE_CHAPTER_1).click()
        self.scroll('400')
        self.find_element(*self.locator.TWELVE_PAGE_1).send_keys('121')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_2).send_keys('122')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_3).send_keys('123')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_4).send_keys('124')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_5).send_keys('125')
        sleep(0.2)
        assert '615' in self.browser.page_source
        self.find_element(*self.locator.TWELVE_CHAPTER_2).click()
        self.scroll('500')
        self.find_element(*self.locator.TWELVE_PAGE_7).send_keys('127')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_8).send_keys('128')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_9).send_keys('129')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_PAGE_10).send_keys('130')
        sleep(0.2)
        assert '514' in self.browser.page_source
        self.find_element(*self.locator.TWELVE_CHAPTER_3).click()
        self.scroll('500')
        self.find_element(*self.locator.TWELVE_PAGE_12).send_keys('132')
        sleep(0.2)
        self.find_element(*self.locator.TWELVE_CHAPTER_4).click()
        sleep(0.2)
        assert '1261' in self.browser.page_source
        self.find_element(*self.locator.AFTER).click()

    # ДОПОЛНИТЕЛЬНО
    def go_to_app_8(self):
        element = self.browser.find_element_by_xpath('//*[text()="14"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_8).click()

    def go_to_app_7(self):
        element = self.browser.find_element_by_xpath('//*[text()="13"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_7).click()

    def go_to_app_9(self):
        element = self.browser.find_element_by_xpath('//*[text()="15"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_9).click()
        sleep(0.5)
        self.hover(*self.locator.CONTROL_TEXT)

    def go_to_app_10(self):
        element = self.browser.find_element_by_xpath('//*[text()="16"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_10).click()
        sleep(0.5)
        self.hover(*self.locator.CONTROL_TEXT)

    def go_to_app_11(self):
        element = self.browser.find_element_by_xpath('//*[text()="17"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_11).click()
        sleep(0.5)
        self.hover(*self.locator.CONTROL_TEXT)

    def go_to_app_12(self):
        element = self.browser.find_element_by_xpath('//*[text()="18"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_12).click()
        sleep(0.5)
        self.hover(*self.locator.CONTROL_TEXT)

    def go_to_app_6(self):
        element = self.browser.find_element_by_xpath('//*[text()="12"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_6).click()
        sleep(0.5)
        self.hover(*self.locator.CONTROL_TEXT)

    def go_to_app_1(self):
        element = self.browser.find_element_by_xpath('//*[text()="7"]')
        self.browser.execute_script("arguments[0].scrollIntoView(true);", element)
        self.find_element(*self.locator.GO_TO_APP_1).click()
        sleep(0.5)
        self.hover(*self.locator.CONTROL_TEXT)
